### ISSUE TITLE
Стрелки влево-вправо на узком экране

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#107]
Сейчас на узком экране стрелок влево-вправо вообще нет:
http://ilyakantor.ru/screen/2014-11-12_1432.png

Предлагаю разместить их где-то внизу страницы, в этом районе:
http://ilyakantor.ru/screen/2014-11-12_1433.png

Кстати, навигация на touch-устройствах (аналог стрелок) доступна свайпом влево-вправо, но каких-то подсказок об этом нет, так что её не находят)

**Comment by iliakan** [comment]
Была уже issue про стрелки на узком экране, эта про неё же видимо.

**Comment by tyv** [comment]
> Hover-tooltip не нужен в этих случаях
так как мы меняем стиль ссылок срелок в зависмомости от media query,  я не вижу способа кроме как в js проверять ширину экрана, что это именно стрелочки и тогда отключать tooltip

**Comment by tyv** [comment]
и мне это кажется не оч правильным

**Comment by Bezart** [comment]
Если это гемор добавляет, тогда не нужно. Я к тому писал, что тултипы в этом случае бесполезны.

**Comment by iliakan** [comment]
1) Хотелось бы показывать кнопки перед коментариями 
Сделано.

2) Hover-tooltip не нужен в этих случаях.
Не вредит, он на mouse-событиях (hoverIntent), т.е. на мобилах его просто не будет, а на компе нормально, в тему.

-----------

Осталось
3) pressed состояние (например бордеры темнее сделать)

**Comment by tyv** [comment]
ок, ща пришлю PR
