### ISSUE TITLE
Предложение.     Back to top

### ISSUE THREAD

**Issue by LeusMaximus** [iliakan/javascript-nodejs#113]
Есть предложение, сделать кнопку "back to top" на мобильных устройствах

**Comment by Bezart** [comment]
На сколько я вижу, проблема не в скролировании наверх, а в доступе к нужным пунктам после прочтения статьи. Так как кнопки шаринга скрыты в верхнем меню, предлагаю вывести их внизу:  http://take.ms/bNnM8 + добавить ссылку на карту

**Comment by iliakan** [comment]
Looks good.
@LeusMaximus это решает изначальную задачу, с которой ты открывал здесь тему?

**Comment by iliakan** [comment]
@Bezart А комментарии где будут? Под всем этим?

**Comment by Bezart** [comment]
Все верно, каменты сразу под этим блоком.

**Comment by iliakan** [comment]
tl;dr: итоговый вариант https://github.com/iliakan/javascript-nodejs/issues/113#issuecomment-77468294

**Comment by iliakan** [comment]
Баг с пустым местом справа, мб связан, на всякий случай тут пишу
http://ilyakantor.ru/screen/2015-03-13_1852.swf

**Comment by iliakan** [comment]
Пропали кнопки "поделиться теперь"
http://ilyakantor.ru/screen/2015-03-13_2018.png

**Comment by skparallax** [comment]
Столкнулся с такой же проблемой, как и @LeusMaximus - быстро найти какую-то информацию.

Грубо говоря, я захожу на сайт с мобильного, когда надо `быстро найти какую-то информацию` или `освежить что-то в голове`, а компа под рукой нет - в метро, например. То есть все сводится к `зашел-посмотрел-ушел`.

@smmurf, про кнопку быстрой прокрутки, я уверен, большинство юзеров не знают или, по крайней мере, не знают как ее вызвать. Я, например, всегда, как @iliakan, кручу-кручу. 

Получается, чтобы посмотреть что-то в разделе "Итого" (отдельное спасибо @iliakan за резюме всей информации в конце страницы - то, что надо) на странице "Массивы: методы" мне нужно прокрутить страницу `18 (!) раз` и потратить `22-24 секунды`. А если потом нужно промотать куда-то в середину, то совсем беда.

Еще нужно учитывать, что у многих 3G с невысокой скоростью и приходится ждать, когда все подгрузится. Я как юзер, прежде чем зайти на страницу снова, еще подумаю, а в 3й раз точно не приду.

Кнопка "Back-to-top", @LeusMaximus, всей проблемы не решит - наверх, как сказал @Bezart, мало кому надо, а надо что-то быстро найти.

Предлагаю для мобильной версии сделать меню, про которое я писал в #332 и прилепить его наверху:

![Alt text](https://monosnap.com/file/wtwIJYuHHePuYmI3rY0LrArnbkzo0b.png) 

![Alt text](https://monosnap.com/file/5W6lfJgpdeULOwHdlyDjXzZ36TY6uL.png)

40px сверху погоды не сделают, зато:
* навигация по учебнику будет под рукой
* плюс навигация по странице  (а это важно, учитывая объем информации на страницах)
* поиск с любого места
* плюс ссылка в личный кабинет (думаю, там будет выпадашка по разделам)

Что думаете?

**Comment by iliakan** [comment]
@skparallax вынес в #349

**Comment by tyv** [comment]
у меня есть иконки :)

**Comment by tyv** [comment]
http://screencast.com/t/5Teehwc5

**Comment by iliakan** [comment]
Тоже есть :8ball:

**Comment by iliakan** [comment]
А вот такой момент?
![image1](https://cloud.githubusercontent.com/assets/349336/6670858/497e995c-cc12-11e4-959e-bbef124165bb.PNG)

Здесь на более узком экране будет налезание карты на иконки.

**Comment by iliakan** [comment]
И по вертикали там чуть-чуть не выровнен текст.

**Comment by tyv** [comment]
это я посмотрю, да

**Comment by tyv** [comment]
@iliakan тут все?

**Comment by iliakan** [comment]
@tyv да, закрываю, ты можешь как сделал просто на меня переназначать, чтобы я в своём списке issue увидел.
