### ISSUE TITLE
Иллюстрации для учебника

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#122]
Придумать как унифицировать дизайн иллюстраций

**Comment by iliakan** [comment]
В Dropbox находится файл Diagrams/Diagrams.sketch
Он содержит мои иллюстрации.

Каждая страница по имени - как имя файла, можно на странице:

http://nightly.javascript.ru/ebook/js

```js
$('[alt="limitations.svg"]').scrollIntoView(true)
```

**Comment by iliakan** [comment]
По цвету такой feedback
=======================
скажите мне как художники художнику...
http://ilyakantor.ru/screen/2015-01-23_1513.png
какой цвет иллюстрации лучше для учебника?

Вот оригинальные ответы, ниже summary.
=============

Я люблю контрасты (за что меня не любят дизайнеры) и поэтому я бы выбрал первый. Но если "всё должно быть гармонично", то имхо второй гармоничен с остальными цветам

Мне кажется , что лучше 1 или 3

Блин, чем больше смотрю, тем сильнее сомневаюсь :) Сначала почти без сомнений выбрал предпослений вариант, а потом стал сомневаться. Но совершенно точно не второй, слишком попадает в цвет к соседним элементам, сливается, а мне субъективно хочется чтобы иллюстрации немного выделялись.

4 за первый 3 за второй 2 за последний 1 за третий 

последний, ну это же дело вкуса, первый и последний мне нравятся намного больше остальных

2 или 3

голосую за 4

Но если тебе нужен конкрентий ответ, тогда — зелений )

1 или 4
===========

Summary:
```
1 2 3 4
+
+   + 
+   + +
+ + + +
+ +   +
+ +
+
+     +
  + +
      +
      +
+     +
=======
9 4 4 7
```

То есть, 1 вариант больше всех, затем 4й.
Мне симпатичнее 1й.

**Comment by iliakan** [comment]
Вроде выбрали.
