### ISSUE TITLE
Векторный фон для покупки учебника

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#123]
Выслать Антону вектор фона используемый на странице покупки учебника

**Comment by iliakan** [comment]
квак.

**Comment by Bezart** [comment]
Добавил в исходник: PDF Book Purchaise / Background pattern

**Comment by iliakan** [comment]
Проапгрейдить стили, добавить фон в них (он справа в исходнике).

**Comment by iliakan** [comment]
Недоделан таск. Ты сам фон не выложил. Кроме того, нужно использовать asset в стилях. Попытаюсь доделать сам.

**Comment by iliakan** [comment]
Предлагаю изменить opacity до 10% вместо 18% на линиях из этого фона http://ilyakantor.ru/screen/2015-02-08_1341.png.

А то текст читается так себе.

**Comment by smmurf** [comment]
Выложил, использовал assert.

**Comment by iliakan** [comment]
@smmurf, я уже закрыл ту issue сам. Если ты тоже делал правки - будет конфликт, пожалуйста сделай pull из мастера в своей ветке и проверь.
