### ISSUE TITLE
Не работают ссылки в уроках Отладка, Автоматические тесты

### ISSUE THREAD

**Issue by LenaMenh** [iliakan/javascript-nodejs#135]
на странице http://nightly.javascript.ru/debugging-chrome нерабочие ссылки на примеры:
http://nightly.javascript.ru/debugging/pow/index.html  (404)
http://nightly.javascript.ru/debugging/pow-error/index.html (404)

http://nightly.javascript.ru/testing
пример с тестами в песочнице тоже не открываются, раздел Итого сломан
http://nightly.javascript.ru/play/beforeafter

**Comment by iliakan** [comment]
Сейчас всё ок?
