### ISSUE TITLE
Разделить задачи

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#137]
Мне кажется или задачи "сливаются"?
http://ilyakantor.ru/screen/2014-12-20_1555.png
http://nightly.javascript.ru/object-conversion

**Comment by iliakan** [comment]
@tyv - замержил, но появилась вот такая проблема: http://ilyakantor.ru/screen/2015-02-06_2214.png

То есть, после заголовка `Задачи` -- великоват промежуток.
Страница та же, http://javascript.in/object-conversion#tasks

**Comment by tyv** [comment]
я думал так и надо, ок доправлю

**Comment by iliakan** [comment]
@bezart глянь плиз.

**Comment by iliakan** [comment]
@tyv, с @Bezart сегодня созвон, я его спрошу.

**Comment by Bezart** [comment]
Отступ норм, бордер между задачам можно 2px сделать, а то сейчас теряется немного.

**Comment by tyv** [comment]
я сделал 3px  был 1px 
сделать 2?

**Comment by Bezart** [comment]
Сори, у меня был 1 px. если там 3, оставляем как есть
