### ISSUE TITLE
Разные отступы в стилях кода

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#146]
Вот на видео показал, что разное: http://ilyakantor.ru/screen/2014-12-27_1153.swf

Страница http://javascript.in/mousemove-mouseover-mouseout-mouseenter-mouseleave#события-mouseover-mouseout-свойство-relatedtarget

Может быть, в стилях CSS какой-то конфликт? Посмотри, пожалуйста.

**Comment by tyv** [comment]
это потому что в CSS трехзначные числа
я бы про это лучше побеспокоился https://yadi.sk/i/xyAPjylweNH9P
