### ISSUE TITLE
Отвязать account? Где?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#149]
Из дизайна не очевидно, как "отвязать" аккаунт?
http://ilyakantor.ru/screen/2014-12-27_2101.png

P.S. Слово Vkontakte - ссылка на http://vk.com? Имхо, ссылка на сам вконтакте как и на профиль в нём, здесь не обязательна, ну для красоты разве что.

**Comment by iliakan** [comment]
Видимо, связано с #160

**Comment by tyv** [comment]
надо накрутить js на кнопку удаления: https://github.com/iliakan/javascript-nodejs/blob/master/handlers/profile/templates/partials/account.jade#L39

**Comment by iliakan** [comment]
отрефакторить `profileAuthProviders`, сделать вывод только непривязанных провайдеров для привязки и реализовать удаление привязки.

**Comment by iliakan** [comment]
Кнопка какая-то хитрая. Она похоже не кликается, убегает из-под мышки.
http://ilyakantor.ru/screen/2015-02-20_1207.swf

**Comment by iliakan** [comment]
По виду, это быть из-за вёрстки?

**Comment by tyv** [comment]
https://github.com/iliakan/javascript-nodejs/pull/268
