### ISSUE TITLE
Дизайн английской версии

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#153]
Упрощённый layout для javascript.info, будет только учебник и поиск.

Без авторизации, без других пунктов верхнего меню, кроме учебника.

**Comment by Bezart** [comment]
http://take.ms/WANF3

**Comment by iliakan** [comment]
@bezart, прочитай свой комментарий выше, пожалуйста.
https://github.com/iliakan/javascript-nodejs/issues/153#issuecomment-68203032

**Comment by iliakan** [comment]
Мне показалось, мы хотим сделать без верхней навигации вообще (раз уж она пуста), и поиск в сайдбаре.

**Comment by Bezart** [comment]
@iliakan это я про меню говорил (ссылки) саму шапку я думаю, нужно оставить. Хотелось бы иметь один и тот же каркас по возможности

**Comment by Bezart** [comment]
И это, что на счет ссылки на англ версию, нужно добавлять на основной сайт?

**Comment by iliakan** [comment]
Она же пустая, просто отъедает место (шапка)

**Comment by Bezart** [comment]
В общем, после обсуждения в скайпе решили оставить шапку, правильно я понимаю?

**Comment by iliakan** [comment]
Да.
