### ISSUE TITLE
Поиск для десктопа

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#154]
Дизайн отличный от мобильной версии

**Comment by iliakan** [comment]
Вроде неактуально, или как? Висит почему-то такая-вот issue.

**Comment by Bezart** [comment]
Сделал, добавил в исходник: http://take.ms/crcaw

**Comment by Bezart** [comment]
Обновил, поле должно быть с фокусом: http://take.ms/zJnX1

**Comment by iliakan** [comment]
То есть, при клике такое поле выезжает?

Кстати, на iphone в лупе не было дырки. Я на почту присылал screenshot.

**Comment by Bezart** [comment]
Да, при клике. Иконку проверю

Обновил поиск в Search,  добавил логику в Responsive

**Comment by Bezart** [comment]
Иконка должна быть ок сейчас

**Comment by iliakan** [comment]
Обновить иконку в шрифте, видимо, нужно для этого, да? Взять из Search?

**Comment by Bezart** [comment]
Ура! Я победил иконку :) https://www.dropbox.com/s/togvaj969izk309/zoom12.svg?dl=0

**Comment by iliakan** [comment]
Обновил!

**Comment by Bezart** [comment]
На nightly сломанная: http://take.ms/SNCnB можешь ту с дропбокса взять?

**Comment by iliakan** [comment]
Это какую?

**Comment by iliakan** [comment]
Скажи плиз, где точно-точно последняя версия :)

**Comment by Bezart** [comment]
https://github.com/iliakan/javascript-nodejs/issues/154#issuecomment-83221562
