### ISSUE TITLE
Загрузка аватарки (crop-resize-rotate)

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#163]
При загрузке горизонтального изображения, у меня получается такое: http://monosnap.com/image/8AXt4W8VEQbEB84fVu2CtSWFItoCkZ 

Предлагаю обрезать по меньшей стороне

**Comment by Bezart** [comment]
Использовал это изображение: http://monosnap.com/image/k1F14B1emtqlCB9H952nsRe27TsvcT

**Comment by iliakan** [comment]
По результатам общения в скайп - решили сделать аватарки только квадратными. Все соц. сети предоставляют квадратный формат.

Сейчас добавил проверку при загрузке на "квадратность" на клиенте. 
Todo: сделать кроп-ресайз-ротейт для аватарки.

1) Crop - чтобы выбрать квадрат, с fixed aspect ratio
2) Resize - чтобы выбрать, что именно должно попадать в квадрат, особенно для больших фото. 
Ресайз должен поддерживать очень большие изображения, уменьшая их на экране для наглядности кропа.
3) Rotate - так как иногда фото на диске не в той ориентации (редко).

**Comment by iliakan** [comment]
Техническое задание:

Клиентская библиотека. Получает файл, например из `<input type="file">`, должна вызвать `callback(err)` с ошибкой, если есть, и `callback(null, file)` с квадратным вариантом изображения не менее заданного размера, для примера 150x150px, если всё ок.

Последовательность действий:
- Если изображение уже квадратное и нужного размера, то всё ок, вызывает `callback` сразу.
- Если размер меньше 150 по ширине или высоте, то вызывает callback с ошибкой сразу.
- Иначе создаёт модальное окошко с `<canvas>` для показа посетителю. Если картинка большая, то масштабирует, чтобы canvas влезал в окно.
- Посетитель может производить действия с картинкой:
  - Crop(выбрать квадратный участок, размер не менее 150x150px)
  - Resize (отресайзить всю картинку)
  - Rotate (поворот на 90 градусов влево или вправо)

По завершении пользователь жмёт OK и, если выбран квадрат с подходящим размером, то вызывается callback с ним.

Детали
- Поддержка старых браузеров не нужна.
- Оформление в виде es6-класса и 6to5 есть гуд

**Comment by Bezart** [comment]
Rotate функциональность не нужна, просто копируем вконтакте для кропа

**Comment by iliakan** [comment]
Update ТЗ:

Клиентская библиотека. Получает файл, например из `<input type="file">`, должна вызвать `callback(err)` с ошибкой, если есть, и `callback(null, file)` с квадратным вариантом изображения не менее заданного размера, для примера 150x150px (настраиваемо), если всё ок.

Последовательность действий:
- Если размер меньше 150 по ширине или высоте, то вызывает callback с ошибкой сразу.
- Если изображение уже квадратное и нужного размера, то всё ок, вызывает `callback` сразу.
- Иначе создаёт модальное окошко с `<canvas>` для показа посетителю. Если картинка большая, то масштабирует, чтобы canvas влезал в окно.
- Дальше редактирование аватара как вконтакте.

Детали:
- Поддержка старых браузеров не нужна.
- Оформление в виде es6-класса и 6to5 есть гуд

**Comment by iliakan** [comment]
@cyber_ua взялся сделать.

**Comment by iliakan** [comment]
Делаю новую issue.
