### ISSUE TITLE
Непонятные скролбары на профиле

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#165]
На широком экране появляются непонятные скролы: http://take.ms/JfT6n

**Comment by tyv** [comment]
какой браузер/OS

**Comment by tyv** [comment]
я не могу воспроизвести, хотя и вижу где это может быть по коду

**Comment by iliakan** [comment]
и какая ширина экрана @bezart?

**Comment by tyv** [comment]
ну ширина понятна по скриншоту +/-

31.01.2015, 18:19, "Ilya Kantor" <notifications@github.com>:

**Comment by Bezart** [comment]
Chrome последний, Mac OS, Сейчас не могу воспроизвести, дома проверю

**Comment by tyv** [comment]
я смотрел на ACD в хроме, развернув на весь экран и уменьшал — так и не воспроизвел

**Comment by smmurf** [comment]
Я тоже не смог воспроизвести, все откладывал, чтобы еще как-нибудь попробовать, но у меня в общем так и не повторилось.

**Comment by iliakan** [comment]
харашо когда баги закрываюцца сами по себе.
