### ISSUE TITLE
Привязка профиля соц. сетей. Дополнительная инфа

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#168]
Хотелось бы заполнять ту инфу которую мы можем получить от соц аккаунта, например имя: http://take.ms/abCo2. В данном случае можно смело делать name = display name. 

Дополнительно хотелось бы видеть город, дату рождения и т д

**Comment by iliakan** [comment]
Соц. сети почти все дают имя, я его интегрировал.

Места проживания гугл показывает, но там строки типа "Россия, Москва", без разбивки на части. По ходу работы мы посмотрим, что там ещё есть. Инфа от соц сети в любом случае привязывается и остаётся в базе, если мы увидим, что эти поля поддаются парсингу, то заполним их в профиль.

Дату рождения не даёт никто.

Технически, можно запросить больше информации в ряде соц. сетей, однако нам она по большому счёту не нужна, а юзеры могут заволноваться, зачем столько инфы сайт хочет.
