### ISSUE TITLE
Учебник: CSS Transitions раздела

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#169]
Сейчас работает так:
http://take.ms/kYspc

Хотелось бы примерно так:
http://whostolemyhat.github.io/css-accordion/

**Comment by iliakan** [comment]
Ты имеешь в виду `opacity` и скорость разворачивания?

**Comment by Bezart** [comment]
сейчас на видео видно как при клике контент "прыгает". Хотелось бы убрать этот эффект, сделать разворачивание более плавным и красивым. Можно использовать opacity и нелинейную скорость, но главная задача это убрать "скачки"

**Comment by iliakan** [comment]
Ага, то есть он сейчас разворачивается слишком сильно, а потом обратно схлопывается, да?

**Comment by tyv** [comment]
если я правильно понял видео, то проблема в том, что строка "Изучаем работу со страницей..."  занимает то 2 строки, то одну. так?

**Comment by tyv** [comment]
если я правильно понял проблему, то из-за того, что вертикальный скролбар появляется и пропадает. 
это лечится очень некрасиво и затронет многие страницы, а проблема очень минорная (воспроизводится в весьма специфических условиях), — предлагаю забить :) простите :)

**Comment by iliakan** [comment]
@bezart уточни проблему плиз, мне казалось - она в том, что элемент слишком сильно разворачивается вначале?

**Comment by tyv** [comment]
ping

**Comment by iliakan** [comment]
Беру себе, нужно сделать, чтобы одновременно закрывался текущий раздел, потом открывался новый, или сначала закрывался текущий раздел.

Сейчас сначала открывается новый, потом закрывается текущий, отсюда скачки.

**Comment by iliakan** [comment]
По согласованию с @Bezart убрал анимацию вообще, так лучше.
