### ISSUE TITLE
Задачи в ebook

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#171]
В последнем разговоре забыл спросить еще по экспорту один момент.

В ebook нельзя скрывать-раскрывать решения задач. 

Мы, вроде, решили, что в самой книге - только условия задач, а решения - в конце, в приложении, верно?

**Comment by Bezart** [comment]
да, верно, решения переносим в конец книги, ссылки "решение" убираем из задач

**Comment by iliakan** [comment]
Текущии версии книги PDF/EPUB находятся в дропбоксе, посмотри плиз.
==============

Предлагаю вашему вниманию несколько "оффлайн"-форматов.

1) book.epub - формат EPUB, сгенерирован при помощи ebook-convert из Calibre.

2) js.wk.pdf js.firefox.pdf js.chrome.pdf - формат PDF, сгенерирован при помощи различных инструментов.
Я попробовал всего пять, ebook-convert и Adobe Acrobat сгенерировали что-то страшное, а wkhtmltopdf и Save as Pdf из Chrome и Firefox можно оценить и выбрать лучший из них.

Скачать их можете здесь https://www.dropbox.com/sh/ys06bw5s37aqv3b/AAD1cHiKrTNR-NndE9b9qu5oa?dl=0

Обращаю ваше внимание, что учебник в процессе разработки, пожалуйста не надо распространять эту ссылку. Она исключительно для вас.

============
EPUB предназначен только для чтения, PDF - в том числе и для печати.

Ваши пожелания к книгам?
Обнаруженные недостатки?
Какой pdf-вариант лучше и почему?

**Comment by iliakan** [comment]
Там еще ссылки на решение от задачи и обратно надо, видимо, как-то отмаркировать.

**Comment by iliakan** [comment]
Update книг https://www.dropbox.com/sh/d94169j53hz0bg1/AADREdVHeNamR60Y9hJS_Ixba?dl=0

**Comment by Bezart** [comment]
Есть 2 варианта.

1. Добавить номера задач, например по номерам разделов / уроков, например 1.2.1-1. Тогда можно использовать этот номер рядом с самой задачей и в конце учебника.

2. В конце учебника, в списке всех решений сделать разбивку по разделам / урокам.

Какой вариант больше нравится?

**Comment by iliakan** [comment]
Разбивка по разделам сейчас как раз есть.

Видимо, её оформление слишком невнятное, чтобы это было заметно.

**Comment by Bezart** [comment]
Что-то типа такого: http://take.ms/rPilK ?

**Comment by iliakan** [comment]
Давай на звонке.

**Comment by iliakan** [comment]
Текущее оформление задач можно посмотреть в книге, которую я прислал.
