### ISSUE TITLE
 Чем можно помочь?

### ISSUE THREAD

**Issue by cyberua** [iliakan/javascript-nodejs#176]
Хочу помочь в разработке сайта.
С чего можно начать ,  в части front-end и back-end ?
П.с до это не участвовал в open source  проектах.

**Comment by iliakan** [comment]
Дома Mac, Linux или Windows?

**Comment by cyberua** [comment]
Основная система Linux,  но есть и винда

**Comment by iliakan** [comment]
Под Linux запустится, прямо сейчас возможна помощь:
- в вёрстке БЭМ-style (Stylus, Jade, CSS3, методология БЭМ) [нужен Mac]
- с учебником (новые разделы, улучшение старых)
- в разработке (грамотный Node.JS)

**Comment by cyberua** [comment]
"С  учебником (новые разделы, улучшение старых)"
Т.е добавление новых статей?
"в разработке (грамотный Node.JS)"
А можно более конкретные задачи? С чего начать и можно ли использовать трансляторы ?

**Comment by iliakan** [comment]
С Node.JS был опыт раньше? Сейчас нет руководства по структуре сайта.

По учебнику - да, новые статьи и улучшение старых.

**Comment by cyberua** [comment]
Да с node.js есть (не большой ) опыт. Занимаюсь своим проектом на ноде потихоньку.

**Comment by cyberua** [comment]
Со структурой думаю разберусь

**Comment by iliakan** [comment]
Ок, подними и сделай, чтобы на /hello выводило "привет, мир" :)

**Comment by iliakan** [comment]
(fork)

**Comment by cyberua** [comment]
Хорошо, завтра сделаю.

**Comment by cyberua** [comment]
Что я погорячился, пока не получается собрать проект

**Comment by cyberua** [comment]
Готово https://github.com/cyberua/javascript-nodejs/tree/b7ea611bcd9072e511f40030d84a7b465ac52079

**Comment by iliakan** [comment]
Cool, it works :)
Можно сделать раздел сайта Q & A. Напиши в Skype ilya.a.kantor.

**Comment by ColCh** [comment]
@cyberua  удачи :)

**Comment by cyberua** [comment]
@ColC , спасибо. Уже нашли мне занятие)

**Comment by iliakan** [comment]
Closing this as unfixable.
