### ISSUE TITLE
Поиск, не отклеивается поле поиска при прокрутке

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#178]
Вот тут http://javascript.in/markup/pages/search
Когда скроллю, поле поиска должно быть всегда сверху, вроде даже в дизайне было так.

Вижу, там код есть для этого, он не работает - это я что-то недопонимаю или ошибка где-то?

**Comment by smmurf** [comment]
У меня код действительно, оказывается, не работает в Safari, при этом работает в Chrome (39), Fx и Oper'е.

В Safari, похоже, проблема с getBoundingClientRect(), и я не могу пока понять, в чем дело.

**Comment by smmurf** [comment]
Видимо, сначала использовал устаревший пример кода, обновил.
