### ISSUE TITLE
Несовпадение ширин макета и реализации поиска

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#180]
В чём может быть дело?
http://ilyakantor.ru/screen/2015-01-17_1228.swf

В макете какие-то устаревшие общие стили или у меня класс забыт где-то?

**Comment by smmurf** [comment]
Скорее всего в `.main.main_width-limit` модификатор потерялся

**Comment by tyv** [comment]
что тут? я уже вижу что появился модификатор и более-менее та ширина
