### ISSUE TITLE
Поиск: "Ничего не найдено" при выборе таба

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#181]
Один из вариантов использования поиска -- это поискать что-то в одном разделе, а потом кликнуть на другой.

Например, с учебника на задачи. При этом надо показывать как-то, что ничего не найдено.
Сейчас никак не показываю, вот: http://ilyakantor.ru/screen/2015-01-17_1424.png

Убирать варианты табов, как в текущей вёрстке, при этом нельзя, т.к. юзер может захотеть переключиться обратно.

Адаптируй, пожалуйста, вариант дизайна Not Found для вкладок, они всегда будут.

**Comment by Bezart** [comment]
Привет, почему бы не использовать текущий вариант с небольшим отличием: http://take.ms/KqRaw

**Comment by iliakan** [comment]
Угу, такое с виду вроде даже не нужное, но элегантное уточнение.
