### ISSUE TITLE
Поиск: показываются первые 50 результатов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#182]
Я сделал вывод количества результатов по разделам: http://ilyakantor.ru/screen/2015-01-17_1548.png

В случае, если их больше 50, то внизу фраза:
http://ilyakantor.ru/screen/2015-01-17_1549.png

Возможно, стоит её как-то лучше оформить.

**Comment by Bezart** [comment]
Думаю, можно немного цветом выделить, как на табах: #727272
