### ISSUE TITLE
Поиск: страница поиска без запроса

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#183]
Вот такой адрес http://javascript.in/search, т.е. просто страница поиска без запроса.

Сейчас http://ilyakantor.ru/screen/2015-01-17_1607.png

Предполагаю, как это будет, но перед окончательной реализацией надо обсудить и нарисовать, чтобы потом не переделывать.

**Comment by Bezart** [comment]
Добавил в исходник: Search / Separate Page

**Comment by iliakan** [comment]
Отсутствие результатов теперь тоже по табам, по дизайну просто фразу вставь, скажи как улучшить, если надо. 
http://nightly.javascript.ru/search/?query=blablabla&type=articles

**Comment by Bezart** [comment]
Предлагаю показывать табы только после поиска. То есть, использовать тот же макет что и был до этого Search / Separate Page, так как табы не имеют смысла без поискового запроса

**Comment by iliakan** [comment]
Возможен вариант, когда результаты есть в одном табе или (на будущее) в двух других, а в текущем выбранном - нет.

Что будет, когда человек переходит в таб, в котором нет результатов? Остальные табы же не могут пропасть.

Это как раз ситуация, в которой и табы нужны и "Ничего не найдено" нужно показать.
Вот так сейчас (я просто строку текста вставил): https://nightly.javascript.ru/search/?query=blabla&type=tasks

**Comment by Bezart** [comment]
Не совсем понял юзкейс. Мы обсуждаем вариант когда нет поискового запроса. Зачем в этом случае табы, учитывая что табы это фильтрация результатов, которых не может быть без запроса

**Comment by iliakan** [comment]
Если нет запроса - табов нет, согласен.
Тут уточнение появилось, по ситуации, когда запрос есть, но в табе результатов нет.

**Comment by iliakan** [comment]
Текущая реализация: "мы ничего не нашли в статьях (в задачах) (...)".
