### ISSUE TITLE
Поиск: отступы в заголовке header не по макету

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#186]
http://nightly.javascript.ru/search/?query=%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5

Заголовок нужно, в соответствие с макетом, сместить на 5 пикселей вниз главный:
http://ilyakantor.ru/screen/2015-01-18_1359.png

**Comment by smmurf** [comment]
В поиске отступы как на других страницах, стоит все-таки ввести дополнительный модификатор и в точности согласовать отступ с макетом, а не с остальными страницами?

**Comment by iliakan** [comment]
Странно, да, @smmurf , ты ведь видишь, как сейчас выглядит? Как будто слишком приподнят хедер.
 
Может, с заголовком что-то по-другому здесь?

**Comment by iliakan** [comment]
@Bezart это из-за отсутствия хлебных крошек. Они здесь точно не нужны или всё же добавить?

**Comment by Bezart** [comment]
Крошки не нужны, заголовок самодостаточный.

**Comment by tyv** [comment]
тогда не понятно что нужно сделать с заголовком, увеличить отступ сверху на высоту крошек?

**Comment by iliakan** [comment]
Выходит, у нас есть вариант заголовка без breadcrumbs.
Заголовок должен быть визуально смещён на 5 пикселей вниз в этом случае. То есть, отступ сверху больше, снизу -- меньше.

**Comment by tyv** [comment]
сравнил макеты, у меня получается 9px, округлю до 10 :)

**Comment by iliakan** [comment]
Главное, чтобы выглядело хорошо. Имхо сдвиг на 5 пикс вниз оптимален.

**Comment by tyv** [comment]
@Bezart подтверди правильные ли тут отступы, если да, сделаю PR
https://yadi.sk/i/KfsuU6JBeUny8

**Comment by tyv** [comment]
короче делаю PR
