### ISSUE TITLE
Иконка внешней ссылки для книги

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#192]
Глянь плиз вот http://ilyakantor.ru/screen/2015-01-19_2006.png, иконка внешней ссылки для оффлайн-чтения.

Может ее не чёрной, а серой или синей сделать?

**Comment by Bezart** [comment]
Лучше цвета ссылки сделать и немного меньше.

**Comment by tyv** [comment]
это мне похоже

**Comment by iliakan** [comment]
@Bezart немного меньше - это....?

**Comment by Bezart** [comment]
80% от текущего на скиншоте

**Comment by tyv** [comment]
https://github.com/iliakan/javascript-nodejs/pull/232/
https://yadi.sk/i/JcGfbv6ReWaaT
