### ISSUE TITLE
Стрелка только вправо, на следующий урок

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#194]
Поправить вид стрелки, когда она одна.
Вот, к примеру http://ilyakantor.ru/screen/2015-01-20_1524.png

@Bezart , правильно ли мы поняли, что нужно сделать, чтобы она 50% экрана занимала и была обрублена с одного конца (не округлена)?

**Comment by tyv** [comment]
мне кажется оба края должны быть закруглены а стрелочка только в 1 сторону

**Comment by iliakan** [comment]
@Bezart  по скайпу сказал, что правильно, т.е. обрублена с 1 конца. Мне тоже кажется это логичным - просто нет одной стрелки, а вторая сохраняет привычный вид.
