### ISSUE TITLE
Неправильный пример или его объяснение

### ISSUE THREAD

**Issue by LenaMenh** [iliakan/javascript-nodejs#196]
http://nightly.javascript.ru/traversing-dom#childnodes
"Почему же перечисление узлов в примере выше заканчивается на SCRIPT? Неужели под скриптом нет пробельного узла?"
В примере выше нет SCRIPT

**Comment by LenaMenh** [comment]
Аналогично с children

**Comment by iliakan** [comment]
Надеюсь, исправлено.
