### ISSUE TITLE
Текст вылазит за приделы блока (android)

### ISSUE THREAD

**Issue by cyberua** [iliakan/javascript-nodejs#198]
Текст вылазит за приделы блока,  nexus 5 android 5.0.1 , chrome   39.0.2171
https://www.dropbox.com/s/b5z7e7cvcg4rfaq/Screenshot_2015-01-19-01-53-54.png?dl=0

**Comment by iliakan** [comment]
Может сделать их один под другим для мобильных?

**Comment by iliakan** [comment]
up
