### ISSUE TITLE
Учебник: Баг в .balance

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#199]
Когда balance в 1 колонку, список занимает только половину ширины, что приводит к переводу строки, вот к примеру:

http://ilyakantor.ru/screen/2015-01-23_1641.png

Видишь, слово "default" перенесено? Я в dev tools выделил `div`, который как раз 50% взял, а не 100.

**Comment by tyv** [comment]
вообще в стилях написано, что если есть только кплючы и минусы, то должен проставляться модифbкатор ```_single``` для блока .balance

```
	// если блок содержит и плюсы и минусы
	&__pluses,
	&__minuses
		float left
		width 50%
		box-sizing border-box
```

я могу написать что-то типа того, чтобы это автоматически делалось:
http://stackoverflow.com/questions/8720931/can-css-detect-the-number-of-children-an-element-has

но не знаю насколько вы поддерживаете print версию, это может не везде работать, какие вообще бразуеры нужно поддерживать? :)

**Comment by tyv** [comment]
как мне найти страницу с плюсами и минусами в .balance?
я нашел только плюсы

**Comment by iliakan** [comment]
Сделал добавление `single`, моя issue, закрываю.
