### ISSUE TITLE
Добавить пояснение для https://nightly.javascript.ru/logical-ops

### ISSUE THREAD

**Issue by mgrinko** [iliakan/javascript-nodejs#205]
https://nightly.javascript.ru/logical-ops

В разделе "Короткий цикл вычислений" я бы добавил пояснения (куда именнно - надо подумать)
```
a || b
эквивалентно
a ? a : b

a && b 
то же что и 
!a ? a : b

**Comment by iliakan** [comment]
Да, куда именно и нужны ли они.
