### ISSUE TITLE
Неточность в названии раздела https://nightly.javascript.ru/comparison

### ISSUE THREAD

**Issue by mgrinko** [iliakan/javascript-nodejs#206]
https://nightly.javascript.ru/comparison

В разделе "Сравнение разных типов" говорится
```
Исключение: когда оба значения — строки
```
Но две строки это же один тип!
  Поэтому я бы переименовал раздел в "Сравнение остальных типов" (или ещё как-то), поскольку сравнение строк подробно описано выше.
  Также здесь говорится обо всех сравнениях включая == и != которые для null и undefined также не делают приведения. Но информация об этом будет только позже и тут пока не очевидна (можно добавить ссылку).
  Объекты также не преобразуются при проверке равенства (но тут подразумевается что мы их даже не обсуждаем, хотя в разделе https://nightly.javascript.ru/types-intro не сказано, что дальнейшие главы относятся только  к примитивам)

   В общем этот раздел вызывает много вопросов, хотя в целом даёт важную информацию о том что основным является преобразование к числу.

*P.S. - можно перенести раздел выше "Сравнения строк" и  попробовать что-то вроде этого:*

### Правила сравнения 
  При проверке равенства/неравенства значений одного типа преобразования не происходит.
  Равенство со специальные значения **null** и **undefined** проверяется отдельно (ссылка)
  Две строки всегда сравниваются побуквенно (ссылку на раздел)
  Во всех остальных сравнениях оба аргумента преобразуются к числу и сравниваются.

*P.P.S - если всё вышеописанное - занудство, то можно просто проигнорировать :)*

**Comment by iliakan** [comment]
Убрал лишнюю фразу про строки. В остальном не очень понял, что не так.
