### ISSUE TITLE
Иллюстрации: новая картинка всех метрик

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#215]
Есть ли замена для http://ilyakantor.ru/screen/2015-02-02_0053.png ?

Вижу самое близкое - artboard с именем `11`, но там нет `scrollHeight/scrollWidth`, `scrollTop`.

Добавь пожалуйста. Это самая важная и первая в главе картинка-шпаргалка, хорошо бы чтобы всё в ней было наглядно.

**Comment by Bezart** [comment]
Кажеться пропустил эту, запилю сегодня

**Comment by Bezart** [comment]
добавил https://github.com/iliakan/javascript-tutorial/commit/0a0434d7f3ced677b293f14782f032b9406e59b2
