### ISSUE TITLE
Не работает пример

### ISSUE THREAD

**Issue by badgoto** [iliakan/javascript-nodejs#219]
Урок https://nightly.javascript.ru/mousewheel, задача "Прокрутка без влияния на страницу".
Собственно пример с прокруткой без влияния работает с влиянием.

**Comment by iliakan** [comment]
А сейчас? Можно подробнее - какой пример и в каком браузере? Скриншот с примером?

**Comment by badgoto** [comment]
Ну возможно я чего-то не понял, но под заголовком "Прокрутка без влияния на
страницу" два примера и оба при окончании внутреннего скролла, начинают
прокручивать внешний. Я думал, что во втором примере такого быть не должно.
Chrome Версия 40.0.2214.111 m.

18 февраля 2015 г., 13:08 пользователь Ilya Kantor <notifications@github.com

**Comment by iliakan** [comment]
А сейчас?
