### ISSUE TITLE
Не работает пример

### ISSUE THREAD

**Issue by badgoto** [iliakan/javascript-nodejs#221]
Урок https://nightly.javascript.ru/drag-and-drop, в нём последний пример с мячиком, мячик нельзя утащить. Падает с ошибкой "Uncaught ReferenceError: getCoords is not defined"

**Comment by badgoto** [comment]
https://nightly.javascript.ru/task/drag-heroes/solution/ - здесь тоже самое

**Comment by iliakan** [comment]
Есть мнение, что статья исправлена.

**Comment by badgoto** [comment]
хм ну сейчас там в примерах вот что http://take.ms/FxjW5

18 февраля 2015 г., 13:05 пользователь Ilya Kantor <notifications@github.com
