### ISSUE TITLE
Блок комментариев из дизайна

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#222]
Перенес комментарии из дизайна, нормально смотрятся?
http://ilyakantor.ru/screen/2015-02-03_1137.png

Это с https://nightly.javascript.ru/intro.

P.S. Убрал там стрелку вниз с "написать" и количество комментариев (оно в сайдбаре слева и блоке комментариев есть).

**Comment by Bezart** [comment]
Добавил в исходник макеты основуясь на том что мы обсуждали по скайпу: Learn / Comments,  Learn / Comments / Hover

**Comment by iliakan** [comment]
@tyv, напиши как делать соберёшься, пришлю последний sketch и диз покажу с красивой выпадашкой для комментариев.

**Comment by iliakan** [comment]
Текущий шаблон `/templates/blocks/comments.jade`, прямо в нём правь.

**Comment by iliakan** [comment]
Можно ли сделать при помощи CSS так, чтобы блок всегда был видим? То есть, находился в границах окна.

Если, как я полагаю, нельзя, тогда при помощи JS будем показывать.

**Comment by tyv** [comment]
не понял вопрос, это же hover типа

**Comment by iliakan** [comment]
Да, но он большой по размеру и зачастую не помещается на экране, если посетитель проскроллил не до самого конца окна.

**Comment by tyv** [comment]
тогда надо js делать и непонятно что с хвостиком тогда делать

**Comment by iliakan** [comment]
Может его сверху показывать?

**Comment by iliakan** [comment]
В смысле весь этот ховер

**Comment by tyv** [comment]
(ты уверен что нужно заморачиваться про такой неважный кусок?)

**Comment by tyv** [comment]
не дума
