### ISSUE TITLE
Рисунки: текст не затеняется

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#223]
Посмотри, пожалуйста, вот две иллюстрации:
http://ilyakantor.ru/screen/2015-02-03_1207.png

На правой текст корректно исчезает справа, а на левой - резко обрублен.

Не могу понять почему, подскажи и поправь, плиз.

**Comment by Bezart** [comment]
нужно текстовый слой ниже полупрозрачной плашки положить (в левой панеле)
