### ISSUE TITLE
Иллюстрации: метрики png -> svg, scrollbar, padding

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#227]
1) Сделать, чтобы .png экспортировались нормально как SVG
2) scrollbar везде `16px` в ширину.
3) Текст имеет отступ `20px` справа от границы или прокрутки. Он на ряде картинок отсутствует или меньше.

**Comment by iliakan** [comment]
ping?

**Comment by Bezart** [comment]
Обновил, запушил
