### ISSUE TITLE
Заказ ожидает оплаты

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#229]
Как выглядит страница заказа, когда он ожидает оплаты?

Особенности:
1) Заказ редактировать нельзя. Можно, наверно, даже и показывать как-то сверхминималистично.
2) Плашка с прогресс-индикатором (ждем ответа от платёжной системы)
3) Если дождались ответа (успех/отказ), то будет рефреш и показ обычной страницы заказа, если не дождались, то плашка с информацией о проблеме, пути решения:
  - обновить страницу позже
  - сменить метод оплаты
  - написать email в поддержку mk@javascript.ru

**Comment by Bezart** [comment]
Решили поступать следующим путем:
1. При успешной оплате кидаем на "Courses / Register / Success"
2. При неудачной оплате показываем сообщение об ошибке как на "PDF Book Purchaise / Payment error"
3. При ожидании оплаты кидаем на "Courses / Register / Waiting for payment"

**Comment by iliakan** [comment]
P.S. Уточняю ещё для надёжности.

То есть, никакой страницы с таймером и динамическим ожиданием оплаты нет. Есть просто страница с "оплата ожидается", и дальше уже всё по email.
