### ISSUE TITLE
Подписка: Отличное решение для борьбы с баннерной слепотой

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#230]
Страница https://blog.serverdensity.com/checking-if-a-document-exists-mongodb-slow-findone-vs-find/
Пролистай вниз.

Вот видео записал небольшое: http://ilyakantor.ru/screen/2015-02-06_1532.swf, но если полистать, то нагляднее.

Сам зашёл на эту страницу, начал читать, скроллю вниз - если бы баннер справа не закачался - я бы ни за что его не заметил. А так смотрю - да, подписаться можно, серьёзно рассмотрел эту возможность.

Это, конечно, не для какой попало рекламы (если бы отвлекали всякой фигнёй, мне бы не понравилось), но для полезных возможностей, которые иначе будут 99% пропущены - мощный метод.

**Comment by Bezart** [comment]
Если честно, я негативно отношусь к такого рода фишкам. Напоминает мне флеш-баннеры, которые пытаются привлечь внимание при помощи анимации.

В данный момент, у нас самой возможности банерной слепоты нет, так как сайбар у нас сугубо функциональный. Если рассматривать проблему самой рекламы, то мне больше нравится идея показывать информацию в контексте, например перед комментариями как здесь: http://take.ms/nBO7i
