### ISSUE TITLE
Заказ: вопрос по потоку оформления

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#235]
Use case:
1) Человек на странице оформления заказа, например `/getpdf/jsbasics`
2) Он вносит данные, жмёт "оплатить", создаётся заказ со статусом `pending` и транзакция в базе, отслеживающая оплату, в статусе `pending_online`, чел отправляется на платёжную систему.
3) Он на странице платёжки пытается оплатить, но у него не хватает денег, редиректится обратно на сайт с ошибкой, попадает на страницу заказа `/getpdf/orders/3`. Там находится уже предзаполненный заказ (если курсы, то запись на курс), он может выбрать другую оплату.
4) Он выбирает любой способ оплаты, но передумывает, и жмёт кнопку Back браузера.

В итоге он попадает на страницу заказа `/getpdf/orders/3`, который находится в ожидании ответа от платёжной системы. 
Так это выглядит сейчас: http://ilyakantor.ru/screen/2015-02-06_2203.png

При этом он отлично понимает, что не оплатил, но в текущем UI не может ничего сделать. Заказ подвисает, оформить его заново нельзя.

Предложение - добавить способ отмены ожидания онлайн-оплаты, который юзер сможет инициировать с этой страницы.

**Comment by Bezart** [comment]
Добавлю в исходник дополнительное сообщение со ссылкой на изменение оплаты

**Comment by tyv** [comment]
разве платежные системы не возвращают сообщение, что транзакция не получилась?

**Comment by iliakan** [comment]
@tyv, посмотри ещё раз, там даже дело не в системе, а в том, что посетитель просто нажал back. 

В этом случае система ничего не сообщает.

**Comment by Bezart** [comment]
Добавил в Courses / Register / Waiting for payment

**Comment by tyv** [comment]
откройте оплату в новом окне, например.

**Comment by iliakan** [comment]
Вроде, обычно сайты так не делают?

**Comment by tyv** [comment]
оплата в новом табе вообще постоянно, или даже окне

**Comment by tyv** [comment]
(ну да, это не оч красиво, но видимо ты не первый кто с такой рпоблемой столкнулся)

**Comment by iliakan** [comment]
мне казалось, там обычно наоборот редирект?

**Comment by iliakan** [comment]
Попробовал на другом сайте, там при back браузер предлагает повторно отправить форму. У меня этого нет, видимо т.к. через AJAX.

**Comment by iliakan** [comment]
На другом сайте попробовал, там вообще при таком use case адок, все заново перевбивать. У нас более-менее нормально ещё, но можно лучше.

Попадание на страницу с инициированной, но незавершённой оплатой происходит в 2х ситуациях.

1) Оплата онлайн, к примеру Яндекс.Деньгами или Webmoney или Paypal.
При успешной оплате такие системы тут же уведомляют сайт, так что попадание на такую страницу до подтверждения оплаты - редкость. Вероятность 95%, что оплаты не было. 

При заходе посетителя на страницу заказа этот случай мы можем увидеть по наличию транзакции в состоянии `pending_online`.

В этом случае показывать "Спасибо за заказ" рановато, надо показать, что произошло и дать возможность оплатить, так как именно это, скорее всего нужно. Не http://ilyakantor.ru/screen/2015-02-07_1719.png, а какой-то вариант http://ilyakantor.ru/screen/2015-02-07_1723.png .

2) Оплата оффлайн, например человек выбирает Payanyway, а затем там оплату через Евросеть или через банк. Payanyway предоставляет много способов оплаты, в том числе и такие, которые требуют похода куда-либо.
При этом Payanyway уведомляет сайт о том, что оплата "в процессе" через специальный URL. То есть, к моменту возврата посетителя на сайт, мы об этом знаем по состоянию транзакции `pending_offline`. 

И в этом случае как раз - нужно показать "Спасибо за заказ, оплата ожидается" с примечанием. То есть, http://ilyakantor.ru/screen/2015-02-07_1719.png.

**Comment by iliakan** [comment]
Решили взять стандартную страницу заказа с выбором метода оплаты + warning типа
```
Уведомление от платёжной системы не получено.

Если вы точно знаете, что оплата была - можно обновить эту страницу через 5 минут или написать в поддержку orders@javascript.ru.
```
