### ISSUE TITLE
Учебник: добавить карту на главную

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#237]
Нужен способ перейти с главной сразу на карту учебника.

P.S. Вроде у нас в одной из редакций дизайна была карта где-то здесь: http://ilyakantor.ru/screen/2015-02-07_1151.png, может место лучше есть или вернуть. А то нада-нада.

**Comment by Bezart** [comment]
Я думаю, место норм. Эта ссылка и была в макете Learn / Home. Я только ссылку поменял, чтобы соответствовать: http://take.ms/dmIKW

**Comment by iliakan** [comment]
Доб плиз.
