### ISSUE TITLE
Заказ: вид оформленной записи на курсы при выборе оффлайн-метода

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#238]
Как будет выглядеть оформленная запись на курсы при выборе:
 - Банковской квитанции?
 - Договора?

Видимо, снизу, где оплата, будет что-то типа "скачать квитанцию" или "договор и акт"?

Кстати, как вариант, в случае курсов можно кидать человека в профиль, т.к. там мы знаем, что человек зарегистрирован.

P.S. И вид при "оплатить позже" тоже надо уточнить.

**Comment by Bezart** [comment]
Да, в мообщении на последнем шаге нужна ссылка на договор / квитанцию. Можно в принципе автоматически загружать тоже.

**Comment by iliakan** [comment]
Шаблон "Спасибо за заказ", ожидается оплата.
