### ISSUE TITLE
Обложка для учебника

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#240]
Векторная. Что-нибудь попроще, черновое, чтобы конвертер наложил на книгу и посмотрим как оно будет выглядеть.

**Comment by Bezart** [comment]
Какая информация будет на главной (Название, автор, год)?

**Comment by Bezart** [comment]
Сделал черновую версию: https://www.dropbox.com/s/11s3t8crct3366m/JSR%20Book%20Cover.pdf?dl=0

**Comment by iliakan** [comment]
В svg мб?

**Comment by Bezart** [comment]
в той же папке лежит SVG версия

**Comment by Bezart** [comment]
https://www.dropbox.com/s/1x16hhjn72ci30i/JSR%20Book%20Cover.svg?dl=0

**Comment by iliakan** [comment]
Обложка на отдельной странице figures.
