### ISSUE TITLE
Заказ: выравнивание мини-логотипа

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#241]
Сейчас логотип и сумма выровнены по правому краю:
http://ilyakantor.ru/screen/2015-02-07_1714.png

Это так и задумано?

Вот логотип выделил: http://ilyakantor.ru/screen/2015-02-07_1713.png

Визуально кажется, что они наоборот не выровнены, сумма правее логотипа.

**Comment by Bezart** [comment]
Можно убрать пустые поля в изображениях, тогда визуально все будет норм. И еще обрати внимание на вертикальное выравнивание внутри блока.

**Comment by Bezart** [comment]
Обновил логотипы в скетче
