### ISSUE TITLE
Тесты: вёрстка раздела

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#245]
Тесты JavaScript ;)

**Comment by iliakan** [comment]
Вёрстку можно делать внутри `markup`, по аналогии с существующими разделами, по всем вопросам я на связи.

**Comment by tadjik1** [comment]
частично реализовано здесь
https://github.com/tadjik1/javascript-nodejs/tree/features-quiz/hmvc/quiz

в этой папке находятся шаблоны и базовый js. в папке со стилями - соответственно стили.
будет здорово, если пригодятся

**Comment by tyv** [comment]
@tadjik1 а поднять-посмотреть как-то можно?
