### ISSUE TITLE
Обратная связь / о сайте

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#247]
Нужен какой-то элемент дизайна, указывающий на возможность получить обратную связь, на почту там написать или вроде того.

Возможно, страница контактов / о сайте.

**Comment by Bezart** [comment]
Добавил в исходник: Learn / Home. Предлагаю сделать в виде футера: http://take.ms/AYaMK + ссылка на меня

**Comment by iliakan** [comment]
Предложил бы вместо UX: Bezart сделать страницу полноценную о сайте. Всё-таки есть ещё, к примеру, и администратор, которого не видно, но сервер настраивает и поддерживает, и вёрстка тоже не сама появилась.

**Comment by Bezart** [comment]
Я не против, тогда подумай над содержанием для этой странице. Когда будет содержание, я оформлю. Потом закинем ссылку в футер.

**Comment by iliakan** [comment]
По несколько слов и фотографии? :)

**Comment by Bezart** [comment]
Ну да. Просто нужно знать, какие слова, сколько фоток и т д. Сам футер я обновил в исходнике

**Comment by iliakan** [comment]
Предложение сделать в футере ссылку на github проекта.
Там уже COLLABORATORS.MD с коллабораторами.

**Comment by iliakan** [comment]
Please обнови дизайн.

**Comment by Bezart** [comment]
все-таки хотелось бы сделать на сайте статическую страницу. В гитхабе редко кто так далеко ходит. Что думаешь?

**Comment by iliakan** [comment]
Может быть на github сделать это частью основного Readme? Прямо на главной странице проекта в каком-то виде обозначить контрибьюторов?

Ссылка сразу на Github - это хорошо, т.к. люди сразу увидят, что проект опенсорсный.

**Comment by Bezart** [comment]
Даже если просто сделать ссылку "О проекте" которая будет вести на гитхаб (что есть не очень очевидная вещь), мне кажется делать это просто в текстовом формате будет скучно и не интересно. Мне больше нравится что-то такое: https://www.meteor.com/about Здесь интересно почитать, посмотреть на команду и общую статистику.

**Comment by iliakan** [comment]
Да, так конечно красивее. Что-то подобное было бы гуд ;) 
Мне в такие секции оформить текст?

**Comment by Bezart** [comment]
Да, было бы хорошо. Если есть фотки с твоих занятий / семинаров и т д, тоже присылай. Еще было бы прикольно, если бы ты смог статистику предоставить. Например, сколько куров / семинаров провел, сколько было учеников за все время и т д. Отзывы от учеников тоже очень гут

**Comment by iliakan** [comment]
Шаблон написал и разместил тут: http://nightly.javascript.ru/about

Некоторая статистика по проекту:

- 4940 участников очных мастер-классов для профессионалов по JavaScript-технологиям в 20 городах России (Москва, Екатеринбург, Ярославль, Новосибирск, Казань, Самара, Пермь, Белгород, Ростов-на-Дону, Санкт-Петербург, Калининград), Украины (Киев, Харьков, Днепропетровск, Одесса, Львов, Херсон, Донецк, Винница) и Белоруссии (Минск), всего около 138 мероприятий.

- 1255 участников онлайн-курсов JavaScript.

- 2 конференции (JS.Talks в Днепропетровске и в Москве)

- 282000 посетителей в месяц (в среднем за последние 12 месяцев)

- >24000 строк JS-кода в open-source коде сайта
- > 93000 строк в учебнике JavaScript

**Comment by Bezart** [comment]
Ок, начинаю визуализацию

**Comment by Bezart** [comment]
Набросок структуры страницы — http://take.ms/GNUwa Посмотри плиз и дай знать, что думаешь. Потом я добавлю цвета и других мелочей.

**Comment by iliakan** [comment]
Предложения такие:
- Миссия проекта -> о проекте
- Люди - предложил бы просто один под другим тех, кто сейчас работает над проектом, в одинаковом размере. Это 3 человека сейчас: @iliakan @Bezart  @tyv
Там же должна быть ссылка на `github/.../contributors.md`, который будет содержать информацию о тех, кто внёс существенный вклад в проект ранее.
- Карта - не уверен, что там нужна ;) Всё же очные мероприятия для проекта не очень перспективны и не основные. Мб цифрой города? 
- Мб статистику в 2 строки? Еще какие-то статы нужны? Которые могут быть интересны.
- Обратная связь - мб просто оставить там мои координаты? Без кнопок хитрых, это в принципе норм работает, спам гмыл отсекает.

**Comment by iliakan** [comment]
С меня
- Контакты для обратной связи
- Текст о проекте 
- Принять участие в проекте

**Comment by iliakan** [comment]
Запушил на странице /about.

**Comment by Bezart** [comment]
Обновил исходник, сделал 2 варианта:
1. http://take.ms/Sn0H6
2. http://take.ms/OhQ2Z

**Comment by iliakan** [comment]
Мне больше нравится 2й вариант.

Кстати, куда ведёт "обратная связь" в футере? http://ilyakantor.ru/screen/2015-03-23_1303.png

**Comment by iliakan** [comment]
@tyv, тебе какой вариант больше нравится из https://github.com/iliakan/javascript-nodejs/issues/247#issuecomment-84733750?

**Comment by Bezart** [comment]
"Обратная связь" – на ту же страницу, на якорь. Многие пользователи просто ищут коyкретную ссылку для контакта а не about

**Comment by iliakan** [comment]
Закрываю эту issue, остаётся по вёрстке.

**Comment by iliakan** [comment]
Какой там сайт для тебя указать у имени? Что-то не нахожу, ты писал...

**Comment by Bezart** [comment]
http://bezart.me/
