### ISSUE TITLE
Заказ отменён

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#249]
Если посетитель заходит на страницу заказа, а он отменён - что показываем?

В этом случае оплату не ожидаем, и не принимаем, то есть, нужен какой-то вариант страницы без выбора метода оплаты и без возможности редактировать заказ.

**Comment by Bezart** [comment]
http://take.ms/1v0Sj Вот стандартный аутпут. В случае если заказ отменен, мы показываем соответствующее состояние
