### ISSUE TITLE
Сделать оглавление для pdf-варианта, добавить его в outline

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#250]
1) Добавить оглавление в начало HTML.
2) Добавить генерацию outline на Java с PDFBox.

**Comment by iliakan** [comment]
@Bezart дизайн оглавления в HTML будет сейчас просто обычный UL/LI.
Мб там шрифт предусмотреть, ещё что-то.

**Comment by Bezart** [comment]
Можешь кинуть скрин, как сейчас плиз. У меня страница не хочет грузиться.

**Comment by iliakan** [comment]
Отослал файл с книгами. Ждём дизайна ;)

**Comment by Bezart** [comment]
Решили оставить как есть
