### ISSUE TITLE
Тесты: состояния кнопок

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#252]
От @tyv:
еще вопрос про кнопки: https://yadi.sk/i/VvIb6Thieb34R тот же: есть они где-то готовые? если нет, то как посмотреть состояния кнопок: hover, pressed, disabled, hovered+pressed, focused

**Comment by Bezart** [comment]
Добавил кнопки в исходник: Forms / JSR_Components_Buttons . Вот снепшот: http://monosnap.com/image/AJPMNUgkn1WAzu4pwDdNGJJdjriR79
