### ISSUE TITLE
Сломан отступ на заглавной странице

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#253]
Глянь, пожалуйста http://ilyakantor.ru/screen/2015-02-13_0045.png
https://nightly.javascript.ru/tutorial

**Comment by iliakan** [comment]
Там, видимо, из-за переделки заголовка, строка находится без отступа от шапки, по дизайну иначе (отступ был, вроде).

**Comment by tyv** [comment]
у меня вроде есть отступ
https://yadi.sk/i/vTl1P2thenQpk

**Comment by tyv** [comment]
уточни бразуер
