### ISSUE TITLE
Загрузка аватарки: выбор квадрата из изображения (canvas)

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#254]
Нужна клиентская библиотека общего характера, может быть отдельным проектом. Поддержка только современных браузеров.

Получает файл, например из `<input type="file">`.

Даёт возможность юзеру выбрать квадратик с аватаром из него.

Результат возвращает через коллбэк: `callback(err)`с ошибкой, если есть, и `callback(null, file)` с квадратным вариантом изображения не менее заданного размера, для примера 150x150px (настраиваемо), если всё ок.

Последовательность действий:
- Если размер меньше 150 по ширине или высоте, то вызывает callback с ошибкой сразу.
- Если изображение уже квадратное и нужного размера, то всё ок, вызывает `callback` сразу.
- Иначе создаёт модальное окошко с `<canvas>` для показа посетителю. Если картинка по размеру больше, чем окно (высокое разрешение), то масштабирует её, чтобы canvas влезал в окно.
- Дальше редактирование аватара как ВКонтакте и коллбэк по окончании.

**Comment by iliakan** [comment]
Дизайн для выбора аватарки?

Можно вращать на 90 градусов и выбирать квадратик. 
Такие контролы: http://ilyakantor.ru/screen/2015-05-11_1719.png

**Comment by Bezart** [comment]
http://take.ms/wGpCU

**Comment by Bezart** [comment]
Обновил после обсуждения http://take.ms/x92vm

**Comment by iliakan** [comment]
Implemented.
