### ISSUE TITLE
Книга: открыть пример в интернет

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#255]
Сейчас в учебнике онлайн живые примеры есть, а в книжном формате их нет. То есть, я просто их не показываю.

Например, вот этого прямоугольника в оффлайн-версии нет:
http://ilyakantor.ru/screen/2015-02-14_1317.png

Я бы предложил не просто его убирать, а заменять на ссылку типа "открыть в интернете". 
Что-то типа такого: http://ilyakantor.ru/screen/2015-02-14_1330.png

Может, в другом дизайне или прямо так?

**Comment by Bezart** [comment]
Думаю, дизайнить что-то особенное для таких ссылок не имеет смысла. Я бы лучше поменял саму надпись, а то "открыть в интернете" звучит не очень. Возможно, "Открыть в браузере" или "Смотреть online". Такие ссылки можно оформить как ссылки открывающиеся в новом окне.
