### ISSUE TITLE
Дизайн страницы ошибки

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#257]
Сейчас дизайн выглядит так:
http://ilyakantor.ru/screen/2015-02-15_1915.png

Наша аудитория - это, преимущественно, разработчики. Но всё равно, кто-то может не понимать, что такое 401, 404 и т.п.

Может быть, сделать код ошибки менее "выдающимся"? Или написать типа "Ошибка 401" вместо просто "401" Как считаешь?

**Comment by Bezart** [comment]
Думаю, не стоит. Все что нужно, выделено большими красными буквами. Слово "ошибка" никак пользователю не поможет
