### ISSUE TITLE
Задача: placeholder вылезает за границу

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#258]
На этом урле: https://nightly.javascript.ru/task/input-nice-placeholder есть задача.

В инпуте красный "placeholder" нормально выглядит в FF:
http://ilyakantor.ru/screen/2015-02-15_2358.png

А вот в Chrome - вылезает сверху:
http://ilyakantor.ru/screen/2015-02-15_2357.png

Почему? Есть ли нормальный способ это поправить?

**Comment by tyv** [comment]
https://github.com/iliakan/javascript-tutorial/pull/2/files
