### ISSUE TITLE
Цитаты под заголовками

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#259]
Пример цитаты: http://nightly.javascript.ru/architect-intro
http://ilyakantor.ru/screen/2015-02-16_1928.png

Нарисуй, пожалуйста, подходящее оформление для таких цитат. Могут быть в несколько строк.

**Comment by Bezart** [comment]
Добавил в исходник Learn / Quote 1, Quote 1
Вот рендер: http://take.ms/DimuX

**Comment by iliakan** [comment]
Пример цитаты https://nightly.javascript.ru/write-unmain-code#соглашения-по-настроению
Классы поправлю как скажешь, стили сделай плиз красиво, по новому дизайну.

**Comment by iliakan** [comment]
Кавычку можно в виде шрифт-иконки?

**Comment by iliakan** [comment]
Запушил `$font-ldquote`.

**Comment by iliakan** [comment]
@Bezart , посмотри, пожалуйста, http://nighlty.javascript.ru/write-unmain-code

Тебе не кажется, что цитаты слишком выпирают из текста и вместо "стильной аннотации" привлекают к себе основное внимание?

**Comment by Bezart** [comment]
Все в принципе гуд, только вот маленькое пиксельное задрочесрство:
```
.quote__footer {
....
width: 25% -> 20%
....
}
```
```
.quote__footer:before {
...
top: -11px -> -8px;
...
}
```

**Comment by Bezart** [comment]
+ border-radius = 2px

**Comment by Bezart** [comment]
Тут еще пообщались с Ильей и пришли к выводу что слишком уж цытаты много на себя внимания внутри статьи тянут. Решили что лучше убрать фон и добавить бордер как тут: http://take.ms/SPkhL

```
.quote {
padding: 25px;
border: 4px solid #FCF8EC;
border-radius: 2px;
}
```
