### ISSUE TITLE
Подсветка активного пункта в сайдбаре

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#261]
Хотелось бы чтобы активный пункт бокового меню был выделен (красным, как и верхнее меню) Поведение примерно как здесь: http://getbootstrap.com/css/#type

**Comment by iliakan** [comment]
Так нормально?
http://ilyakantor.ru/screen/2015-02-17_1840.png

Мне чего-то этот "обычный" `red` глаз режет.

**Comment by Bezart** [comment]
Пофиксили на stage
