### ISSUE TITLE
Иллюстрации: Экспортировалось странно

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#262]
https://nightly.javascript.ru/coding-style
Вот эта иллюстрация из figures странно экспортировалась:
http://ilyakantor.ru/screen/2015-02-17_1850.png

Она же в Sketch:
http://ilyakantor.ru/screen/2015-02-17_1850-1.png

**Comment by iliakan** [comment]
Только что взял из последнего Sketch'а (мы говорили по тел, он реально последний), экспортировал artboard, открыл code-style.svg в браузере - всё то же самое:
http://ilyakantor.ru/screen/2015-02-21_1905.png

**Comment by iliakan** [comment]
С соседней иллюстрацией такая же беда: http://ilyakantor.ru/screen/2015-02-21_1906.png

**Comment by Bezart** [comment]
Пофикшено в последней версии
