### ISSUE TITLE
Иконки при печати меняют цвет

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#266]
Иконки из шрифтов почему-то меняют цвет при печати.

Не все, некоторые.

Например:
http://javascript.in/ebook/intro

При печати в Chrome:
http://ilyakantor.ru/screen/2015-02-19_1820.png

Посмотри, пожалуйста, можно ли пофиксить? Мб что-то не так с конкретной иконкой?

**Comment by tyv** [comment]
там некоторые цвета почему-то не очень правильно приводятся к "печатному" цвету. Я подобрал "такой же", но который нормально работает для этой иконки, есть еще плохие?
