### ISSUE TITLE
Учебник: Купить учебник

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#271]
Нужен баннер или его аналог для покупки учебника, ты вроде уже делал, где оно сейчас?

**Comment by Bezart** [comment]
Вот вариант с верхней навигацией – http://take.ms/MAmW9

**Comment by iliakan** [comment]
Оставляю, чтобы не забыть, обсуждение в рамках #278.

**Comment by Bezart** [comment]
Обновил полностью в исходнике Responsive Logic

**Comment by iliakan** [comment]
Правильно ли я понял, что итоговая верхняя навигация доделана и находится в Responsive Logic?

**Comment by Bezart** [comment]
Правильно

**Comment by iliakan** [comment]
@Bezart В responsive нет обозначений обновлённых разделов как new.

**Comment by iliakan** [comment]
@Bezart когда придёшь глянем stage от @tyv, как там ресайз сделан (не всё помещается при 1100 -> 900), то что надо?

**Comment by iliakan** [comment]
По результатам общения с @Bezart:
1) Уменьшить место между иконками справа можно
2) Заменить полное лого на одну башню, он нарисует позже (кстати pull новое лого).

http://ilyakantor.ru/screen/2015-04-03_2127.png
