### ISSUE TITLE
Логотип для нового дизайна

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#275]
Уже обсуждали по телефону: поговорил со многими коллегами касательно визуального образа сайта, пришел к выводу что логотип не вписывается в новую, минималистичную концепцию сайта. Думаю, имеет смысл обновить к релизу.

**Comment by Bezart** [comment]
Подумал на счет простого, понятного и тематического концепта, пришла в голову идея обыграть какой-то символьный мотив связанный непосредственно с JS. 

Думал на счет:
();
&&
===
/* */

В итоге остановился на // 

После долгого веселья со шрифтами, нарисовал вот: http://take.ms/k6kj6 

Что думаешь?

**Comment by iliakan** [comment]
Fine by me.
@tyv?

**Comment by tyv** [comment]
ну комментарий сразу нет :)
например, потому что в голове разработчика комментарий это серый, незметный кусок, тут вообще непонятно что это комментарий, потому что в наших головах он такой: https://yadi.sk/i/19sFBR3TeubRn

**Comment by tyv** [comment]
но идея бодрая, можно обыграть https://yadi.sk/i/M2YZveg8eubjr

**Comment by tyv** [comment]
дурацкий диск корежит файл пока не кликнули https://downloader-default13j.disk.yandex.ru/rdisk/be0068ce6b29822f0af59e0fd2d64ec8975cbb23dcab8dc1e0d9e5f68777c1de/inf/jiiMw165KPltdKQsbesqr7MIyCZkf-UKpkAHbhhYOwowKT20XN6Ar77BebQdpK0Sq_J6bpmRyOJonT3VoXnDag==?uid=0&filename=2015-02-26%2019-09-35%20Untitled-1%20%40%20100%25%20%28Group%201%2C%20RGB%208%29.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=1652eb80306e5495d1f739bde759b335&force_default=no

**Comment by Bezart** [comment]
Ок, покопаюсь еще. Только мелкие детали как ; ' ' отпадают сразу. Скобки имхо норм.

**Comment by iliakan** [comment]
Поговорили, решили адаптировать/упростить текущий, уж больно хорош.

**Comment by Bezart** [comment]
Ок, посмотрю что можно сделать

**Comment by Bezart** [comment]
ВОТ попробовал упростить: http://take.ms/TDnH3
Пример на странице: http://take.ms/U5Qxp

**Comment by iliakan** [comment]
кружочек на башне не нужен imo

**Comment by iliakan** [comment]
@tyv?

**Comment by Bezart** [comment]
кружочек самый кайф имхо :)

**Comment by iliakan** [comment]
@tyv what ya think?

**Comment by tyv** [comment]
ну если не планировали кардинально менять то вроде ок

**Comment by tyv** [comment]
хуже не стало точно :)

**Comment by tyv** [comment]
да кстати -- кружочек хороший, играет с точкой

**Comment by iliakan** [comment]
циркуль какой-то.

**Comment by iliakan** [comment]
@Bezart плиз ещё варианты сделай.

**Comment by Bezart** [comment]
буду отстаивать этот вариант :) я присылал другие варианты уже, ты попросил текущий адаптировать. Теперь я его полюбил...

**Comment by iliakan** [comment]
@Bezart посмотри, пожалуйста, нормально? Вот варианты со старым и новым лого:
https://nightly.javascript.ru/about
https://nightly.javascript.ru/about?logo2

Правильный ли масштаб, позиция нового лого?

**Comment by iliakan** [comment]
Добавь, пожалуйста, в исходник оригинал лого, с исходным текстом в шрифте, а не compound path.

**Comment by Bezart** [comment]
Добавил Other / Logo New Header
Шрифтовой версии нет так как я его правил.

**Comment by skparallax** [comment]
первое, что бросается в глаза, то что логотип ниже строки меню

![Alt text](https://monosnap.com/file/gKWAcVbdDSnkVFapZE4lCmoW05XDO5.png)

**Comment by iliakan** [comment]
Это поправил.

@Bezart сделай, пожалуйста, одинокую башню (краткий вариант лого).

Лучики от башни плиз назови `Ray-left-top/Ray-left-bottom/...` (вместо `Fill-NN`) и разгруппируй.

Если лого на этом окончательное - я обработаю его оптимизатором прикручу анимацию.

**Comment by Bezart** [comment]
Обновил исходник
