### ISSUE TITLE
Индикация прогресса

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#277]
Для дополнительной мотивации пользователей которые проходят весь курс, есть предложение сделать общий прогресс-бар, который будет показывать текущее положение пользователя внутри курса

Вот как это выглядит: http://take.ms/oR9j8

Вычисляется довольно просто: если в курсе 50 уроков, то 1 урок = 0.5%
При наведении показываем наш стандартный тултип: "урок 10 / 50"

**Comment by iliakan** [comment]
Переменные:
```
    rendered.bookLeafCount = общее число статей в книге;
    rendered.bookChildNumber = номер текущей статьи;
```

**Comment by Bezart** [comment]
Хотелось бы чтобы прогресс бар оставался в самом верху страницы при скроле

**Comment by tyv** [comment]
хочется сделать с элементом progress но он плохоподдерживается даже в ie10
не хочется писать костыли, что у нас с поддержкой современных ИЕ?

**Comment by iliakan** [comment]
только самые современные

**Comment by iliakan** [comment]
в IE11 ok?

**Comment by iliakan** [comment]
Желательно, чтобы в старых IE оно не ломало сайт, но заморачиваться на этом не надо (хотя я, грешен, понавесил полифиллов).

**Comment by tyv** [comment]
м.. не знаю, но проверю

**Comment by iliakan** [comment]
Для ориентировки данные Я.Метрики
```
IE11.0 1,2%
IE8  0.3%
IE9  0.2%
IE10 0.2%
```

IE8 мы не поддерживаем вообще никак.

**Comment by Bezart** [comment]
для старых ие можно стандартную тенюшку делать, не критично

**Comment by iliakan** [comment]
@Bezart посмотри, пожалуйста, на nightly.

Я также сделал показ главы при наведении стандартным тултипом.

**Comment by Bezart** [comment]
Посмотрел, все гуд, только немного с сайтбаром сливается. Давай сделаем серую часть немного другого цвета: #E1E0DE

**Comment by iliakan** [comment]
Поменял, запушил, на взгляд вообще отличий никаких.
Ты точно именно так задумывал?

**Comment by Bezart** [comment]
Все гут, полоса теперь темнее и отличатся по цвету от фона сайдбара
