### ISSUE TITLE
Навигация респонсив

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#278]
По обсуждению скайп:

Делаем сверху навигацию, пункты:
```
Учебник
Форум
ES5
Чат
Курсы
Справочник
Node.JS
Тест знаний
```

Сейчас почти все они ведут на старый сайт.

Плюс точки респонсивности отрисовать для текущей навигации, мобильный дизайн у нас уже реализован.

P.S. Хорошо бы как-то обозначить, что Учебник - новый, на новом движке. Типа "new", даж не знаю, чтобы люди понимали где самый свежак :)

**Comment by iliakan** [comment]
P.P.S. Если что-то будет влезать - возможно уменьшение размера шрифта, а-ля css-tricks, но не факт что понадоибсят, скорее всего уже сразу мобильный дизайн.

**Comment by iliakan** [comment]
http://monosnap.com/image/61Whrnpc20abntz8o1aoYg0fG7AXNN

**Comment by iliakan** [comment]
Как с обновлением навигации дела? + покупка учебника ненавязчивая.

**Comment by iliakan** [comment]
По поводу кнопки "Купить учебник" ещё вот пришло в голову.

Люди не поймут. Что за "купить"? 
Если "купить оффлайн-вариант" - это одно дело, тут понятно, а тут просто "купить учебник".

**Comment by iliakan** [comment]
На звонке решили сделать несколько разных кнопок для теста.

**Comment by Bezart** [comment]
Все остальное в #271
