### ISSUE TITLE
Профиль и Аккаунт

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#279]
Названия "Профиль" и "Аккаунт", особенно для непосвящённого юзера, выглядят в одном меню странно. Лично для меня это на первый взгляд синонимы.

http://ilyakantor.ru/screen/2015-02-24_1520.png

Я бы предложил переименовать профиль в "О себе" и сделать Аккаунт первым в списке, как самый востребованный пункт.

Уже говорили об этом, режет глаз, снова поднимаю тему.

**Comment by Bezart** [comment]
На звонке ришили следующее:
1. Первым делаем таб Аккаунт
2. Меняем Профиль на Публичный профиль
3. Добавляем описание в публичный профиль "Эта информация о вас, которая будет видна другим пользователям Javascript.ru"
