### ISSUE TITLE
Учебник: кривые Безье, цветовое кодирование

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#280]
В учебнике про кривые Безье, в примерах я использую цветовое кодирование.

Есть идеи, как его избежать?

http://learn.javascript.ru/bezier#рисование-де-кастельжо

Первая картинка-пример и ниже, там синий-красный-чёрный.

**Comment by iliakan** [comment]
Решили сделать буквенные обозначения, в дополнение к цветовому кодированию на картинках, из текста цвет убрать.

@Bezart при перерисовке иллюстраций это учти, пожалуйста.

**Comment by Bezart** [comment]
Прорисовал иллюстрации в векторе. Пока решили оставить так, без дополнительных обозначений
