### ISSUE TITLE
Профиль: на широких мониторах глюки из-за шрифта

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#281]
У нас стоит CSS media query, которая делает на широких мониторах размер шрифта не 14, а 16px.

При этом профиль слегка корёжит, вот глянь пожалуйста:
Вот видео: http://ilyakantor.ru/screen/2015-02-24_2123.swf

Можно ли поправить вёрстку, чтобы всё было в порядке и с 14 и с 16 размером?

Альтернативный вариант - можем сделать в профиле всегда 14, но хотелось бы один размер везде.

**Comment by iliakan** [comment]
Там ещё скроллы заметил @Bezart

**Comment by iliakan** [comment]
@Bezart посмотри плиз профиль ещё раз, эти баги по идее поправлены.

**Comment by iliakan** [comment]
@tyv, вот у меня на широком мониторе:
http://ilyakantor.ru/screen/2015-02-27_1728.png

На обычном отступы переколбасило.

**Comment by tyv** [comment]
ну надо таки переверстать там все :(

**Comment by iliakan** [comment]
Сложно поддерживать 2 размера шрифта одновременно?

Мы можем отключить там размер 16 вообще, сделать его только в учебнике.

**Comment by tyv** [comment]
нет, все равно рано или поздно будет длинная строка, которая все сломает
без эмуляции таблиц не обойтись

**Comment by tyv** [comment]
вообщем я разберусь, может можно будет малой кровью сделать

**Comment by iliakan** [comment]
Это поправлен, да?

**Comment by tyv** [comment]
да
