### ISSUE TITLE
Учебник: информативность главной

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#282]
В доп курсах показываем список статей. Имхо гораздо информативнее и удобнее.

А то в разделы типа "о всякой всячине" и ходить никто не будет.

Сделал тестовую реализацию локально.

**Comment by Bezart** [comment]
Обновил Learn / Home в исходнике

**Comment by iliakan** [comment]
По виду там только ссылки сделать - и всё? Отступы, межстрочные расстояния в списке, всё стандартно?

Задеплоил, посмотри пожалуйста на nightly, так и должно быть?

**Comment by Bezart** [comment]
Там размеры шрифтов другие, посмотри плиз в макете. Еще у заголовков там стоит шрифт другой. Под "Дополнительно" не хватает строки-подписи

**Comment by iliakan** [comment]
А сейчас?

**Comment by Bezart** [comment]
Обсудили по скайпу. Еще посмотрел, на больших шрифт в этом блоке можно оставлять 14px

**Comment by iliakan** [comment]
На больших - это...? что поменять, не очень понял?

**Comment by Bezart** [comment]
В основном блоке ссылки и так по 14px. Думаю, будет норм. Сейчас они слишком большие

**Comment by iliakan** [comment]
Мне кажется, в осн курсе можно бы побольше подразделы.
На звонке тогда.

**Comment by Bezart** [comment]
Обсудили на звонке
