### ISSUE TITLE
Курсы, вёрстка

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#286]
@tyv как тебе дизайн курсов (страница Courses)?

Пока @Bezart с другими issues работает, хочу попытаться и их сделать, нужна вёрстка, ну и если по самому дизайну какие-то комментарии будут.

**Comment by iliakan** [comment]
@smmurf указал, что по его мнению можно реюзать из его вёрстки: http://learn.javascript.ru/files/smmurf.zip

**Comment by tyv** [comment]
файла нет

**Comment by iliakan** [comment]
Да, сайт заменили на новый. Я пришлю по скайп.

**Comment by tyv** [comment]
все готово кроме оплаты, ждем нового дизайна
оплата сделана сейчас как в ebook
и там например нет юрлиц, я могу прикрутить пока что форму которая есть у @smmurf в верстке, но кажется лучше подождать макета
