### ISSUE TITLE
Карта сайта: юзабилити - не очевиден overlay

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#288]
Сейчас карта сайта показывается в overlay с очень небольшой opacity.

Он почти непрозрачный - это сделано потому, что иначе читать текст было бы сложно.

Однако, так как оверлей занимает всю страницу, то при нажатии на карту сайта, например, здесь https://nightly.javascript.ru/tutorial, возникает впечатление, что это не оверелей, а именно отдельная страница. Она выглядит отдельной.

Соответственно, чтобы уйти с неё, человек будет использовать кнопку браузера Back, и перейдёт непонятно куда.

Вижу два решения:
1. Я могу сделать так, чтобы кнопка Back закрывала оверлей, т.е. вела обратно на страницу.
2. Можно как-то более ясно показать, что это оверлей, чтобы у посетителя не возникало желание нажать Back, а он закрывал именно оверлей кнопкой [x].

Надо выбрать решение и как-то поправить эту проблему юзабилити.

**Comment by Bezart** [comment]
После обсуждения добавил в исходник : http://take.ms/fBgfZ

**Comment by iliakan** [comment]
Сделал. Так ок?

**Comment by Bezart** [comment]
норм сейчас, только отступы сделать, как обсудили на звонке и все гут

**Comment by iliakan** [comment]
Как в Я-поиске - скролл пусть будет без учёта верхней части оверлея.

**Comment by iliakan** [comment]
@tyv, посмотри пожалуйста, как это лучше сделать?

**Comment by iliakan** [comment]
`<progress>` её перекрывает, зайди к примеру на https://nightly.javascript.ru/mouse-clicks и открой карту.

Там z-index 10001, а у модального окна 1001. Есть какая-то причина, почему у progress именно такой z-index или может опустить его до 101?

**Comment by tyv** [comment]
можно понизить, это sticky плагин делает

**Comment by iliakan** [comment]
Странная бага у меня в хроме/опера на Mac - sticky-фильтр сверху дёргается, откладываем её решение до репортов.

**Comment by tyv** [comment]
в фильтре уже нет sticky плагина, а комент про прогресс он как бы вообще не сюда, но да, для стики плагина нужно понизить его z-index

**Comment by iliakan** [comment]
Да, я это сделал, спасибо за уточнение. Пост выше для истории написал, на текущий момент карту считаем закрытой :)
