### ISSUE TITLE
Тесты: фидбек при ответе

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#289]
Что думаете насчёт того, чтобы при ответе на тест сразу давать фидбек, правильный он или нет?

Например, фон мигает красным (неверным) или зелёным (верно), как сделано тут:
http://ilyakantor.ru/screen/2015-02-28_1108.swf

@tyv @Bezart ?

**Comment by Bezart** [comment]
Мне не очень нравится. Если человек сразу видит правильно / неправильно, он меньше сфокусирован на следующих вопросах + многие люди при нескольких неправильных ответах начинают тест заново, не доходя до конца.
