### ISSUE TITLE
Тесты: вопросы многострочные, с кодом и текстом

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#291]
Текущий дизайн тестов для вопроса предусматривает одну жирную строку.

Большинство вопросов состоят из нескольких строк, включают в себя код, см. например:
http://learn.javascript.ru/task/js-voprosnik-3

И вообще, список текущих вопросов: http://learn.javascript.ru/javascript-quiz

В дизайне плиз нарисуй, как это будет? Просто параграфы и код? Каким шрифтом? Плиз текущий диз поправь, чтобы реальный вопрос там был, например http://learn.javascript.ru/task/js-voprosnik-3

**Comment by Bezart** [comment]
http://take.ms/DBZzv 
Просто придерживаться стандартных стилей с learn. min-width для десктопа нужен больше, хотя бы 600-800px
