### ISSUE TITLE
Тесты: индикатор успеха в векторе

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#296]
Сейчас выглядит так:
![image](https://cloud.githubusercontent.com/assets/349336/6459200/82c91bb2-c19d-11e4-8c30-7f65e928aa25.png)

Это PNG, на retina некрасиво. 
Мы говорили раньше о векторном варианте, мб ты даже что-то уже сделал?

**Comment by Bezart** [comment]
Да, делал, вектор в текущем исходнике

**Comment by iliakan** [comment]
При экспорте в SVG и открытии в Sketch:
http://ilyakantor.ru/screen/2015-03-04_1200.png

В браузере та же фигня:
http://ilyakantor.ru/screen/2015-03-04_1200-1.png

**Comment by Bezart** [comment]
Пофиксил, сейчас должно быть норм
