### ISSUE TITLE
Тесты: запись результатов в профиль

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#297]
Предлагаю следующий вариант:
- По умолчанию результаты в профиль не сохраняются.

- После прохождения теста на странице результатов человеку предлагается сохранить результат в профиле. Если жмёт на кнопку, то сохраняем, иначе - нет.

- Если не авторизован, то предлагаем авторизоваться и сохранить результат потом, после авторизации он попадает на ту же страницу, и там может нажать на кнопку.

**Comment by Bezart** [comment]
По-моему, норм

**Comment by iliakan** [comment]
Нарисуй плиз, как это будет.

**Comment by Bezart** [comment]
Добавил в исходник, вот рендер: http://take.ms/O5qxi 
Предлагаю если юзер не залогинен, при клике на кнопку просить логин и после удачной авторизации сразу сохранять результат, чтобы не приходилось кликать дважды на одну и ту же кнопку

**Comment by iliakan** [comment]
Как хорошо, что такая возможность заложена в авторизацию с самого начала. Прикручиваю.

**Comment by iliakan** [comment]
Может добавить туда же возможность "пройти ещё раз?" Или не надо?

**Comment by Bezart** [comment]
Думаю, отличная идея, добавил в исходник: Tests / Results

**Comment by iliakan** [comment]
Implemented.
