### ISSUE TITLE
Тесты: результаты в профиле

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#298]
Добавь, пожалуйста, в дизайн время, которое заняло прохождение теста и убери "слабые места" и "количество попыток" -- их не будет в 1м релизе.

Вот сюда, то есть: http://ilyakantor.ru/screen/2015-03-05_1647.png

**Comment by Bezart** [comment]
Обновил в исходнике: Tests / Profile

**Comment by iliakan** [comment]
Апдейт дизайна.
