### ISSUE TITLE
При переходе на конкретный quiz предлагать пройти его

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#299]
При переходе по ссылке на конкретный quiz, например http://javascript.in/quiz/ajax, хорошо бы предложить пройти тест.
Не начинать новый тест автоматом, только предлагать (и замер времени с согласия).

Как это будет в дизайне выглядеть?

**Comment by Bezart** [comment]
Ссылка не работает

**Comment by iliakan** [comment]
Она и не должна работать.

**Comment by iliakan** [comment]
Важно лишь то, что она ведёт на конкретный quiz, какая разница на какой. В принципе, если тебе важно увидеть, я задеплою.

**Comment by iliakan** [comment]
Задеплоил, вот текущие quiz: https://nightly.javascript.ru/quiz

**Comment by iliakan** [comment]
Если проблема непонятна - напиши.

**Comment by iliakan** [comment]
Если проблема непонятна - напиши плиз.

**Comment by Bezart** [comment]
Давай обсудим на звонке, есть вопросы

**Comment by Bezart** [comment]
Добавил в исходник Tests / Start: http://take.ms/Arrur

**Comment by iliakan** [comment]
А вот это там где?
http://ilyakantor.ru/screen/2015-03-11_0056.png

**Comment by Bezart** [comment]
Добавил: http://take.ms/Hfksg Исходник обновил

**Comment by iliakan** [comment]
Implemented.
