### ISSUE TITLE
Иллюстрации: witch

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#301]
1) Пропущена `witch_lazy5.png` из комплекта
2) При экспорте они портятся: верхний текст сдвигается, вот пример -- кавычка вместо того чтобы быть сверху -- слева: http://ilyakantor.ru/screen/2015-03-06_1712.png

**Comment by iliakan** [comment]
P.S. Пофиксь в figures please, я его не буду трогать без согласований с тобой, а то артборды переносить неудобно жуть.

**Comment by Bezart** [comment]
запушил фиксы, добавил пропавшую картинку из серии

**Comment by iliakan** [comment]
Добавил стрелочки, чтобы было более понятно происходящее, и перенёс в figures.
