### ISSUE TITLE
Таблица приоритетов

### ISSUE THREAD

**Issue by electrovladyslav** [iliakan/javascript-nodejs#304]
В учебнике, в главе "Основные операторы" (https://nightly.javascript.ru/operators), в подразделе "Приоритет" написано:

Она содержит как уже пройденные операторы, так и те, которые мы еще не проходили. В ней каждому оператору задан числовой приоритет. Тот, у кого число меньше — выполнится раньше. Если приоритет одинаковый, то порядок выполнения — слева направо.

А на сайте Мозилы, ссылка на который абзацем выше (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) всё наоборот, чем выше приоритет, тем раньше выполниться операция:

Operator precedence determines the order in which operators are evaluated. Operators with higher precedence are evaluated first.

Ну и, соответственно у вас в таблице приоритеты повышаются (унарный + => 4,  присваивание =>17), а там  - понижаются(унарный + => 15,  присваивание =>3)

p.s. в спецификации не нашёл этой темы.

**Comment by iliakan** [comment]
Спасибо, исправлено.
