### ISSUE TITLE
Содержание раздела Числа.

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#305]
[Содержание раздела Числа.](https://nightly.javascript.ru/number)

Хотелось бы, чтобы содержание носило не только учебный характер, но и справочный (в большей мере, чем сейчас). 

******************

Например, чтобы при описаниях встроенных функций сразу оговаривалось, что они приводят аргумент к числу. 
Конкретный пример для [параграфа "isFinite(n)"](https://nightly.javascript.ru/number#isfinite-n):

> Функция isFinite(n) возвращает true только тогда, когда n — обычное число, а не одно из этих значений:

Однако, [ниже выясняется](https://nightly.javascript.ru/number#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%87%D0%B8%D1%81%D0%BB%D0%BE), что:

> Функция isFinite(n) преобразует аргумент к числу и возвращает true, если это не Infinity/-Infinity/NaN.  

Т.е. хотелось бы сразу при описании каждой функции увидеть полную информацию о базовых особенностях ее работы.

Кстати, похожая ситуация с логическим оператором [|| (или)](https://nightly.javascript.ru/logical-ops#%D0%B8%D0%BB%D0%B8), где сразу же идет выделенное предложение:
> Логическое ИЛИ в классическом программировании работает следующим образом: «если хотя бы один из аргументов true, то возвращает true, иначе — false».

Да, там указано, что это для классического програмирования. Да, двумя параграфами ниже поясняется, что возвращаются значения. Но об этом лучше написать сразу, прямо под фразой про классику, тем же выделенным шрифтом: "Мол, а в js это не совсем так". Ибо люди запоминают первое же выделенное, а потом начинается мужественное преодолевание примеров. Это в лучшем случае, а в худшем - люди не станут читать дальше и потащат это в код. 

******************

Впрочем, информацию о более тонких материях тоже хотелось бы иметь непосредственно при описании функции. Например, в вышеупомянутом параграфе ["Проверка на число"](https://nightly.javascript.ru/number#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%87%D0%B8%D1%81%D0%BB%D0%BE) , выясняется, что:
> Так устроена функция parseFloat: она преобразует аргумент к строке, т.е. true/false/null становятся "true"/"false"/"null", а затем считывает из неё число, при этом пустая строка даёт NaN.
Т.е. она не преобразует пустую строку "" к нулю, как ее товарки.  
Заодно можно указать, что Infinity она почему-то возвращает как Infinity, а не Nan, как parseInt.  

Понятно, что молодой падаван должен стойко переносить тяготы и лишения на пути ниндзя, но иногда это становится утомительным.

******************
Опечатка:   [Math.atan потерял (x)](https://nightly.javascript.ru/number#%D1%82%D1%80%D0%B8%D0%B3%D0%BE%D0%BD%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F).
******************

**Comment by iliakan** [comment]
Эти две вещи исправил, спасибо.
