### ISSUE TITLE
Node.JS скринкаст

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#308]
Информацию просто скопировать с http://learn.javascript.ru/nodejs-screencast? Один-в-один без сайдбара, с такой же структурой?

**Comment by Bezart** [comment]
Ты имеешь ввиду в новом дизе?

**Comment by iliakan** [comment]
Да.

**Comment by Bezart** [comment]
Давай так перенесем пока, потом я посмотрю и отредактирую детали (например иконки и т д) но для этого хотелось бы иметь что-то для старта.

**Comment by iliakan** [comment]
https://nightly.javascript.ru/nodejs-screencast

**Comment by Bezart** [comment]
Добавил макет страницы в исходник (страница Node.js), вот рендер: http://take.ms/FiBNJ. В исходнике еще прорисованы некоторые динамические вариации.

**Comment by iliakan** [comment]
А что там с подпиской на уведомления по курсу? В рендере её не вижу.

**Comment by iliakan** [comment]
P.S. Исходник на Dropbox не обновился.

**Comment by Bezart** [comment]
В исходники это прорисовано. При клике на бейдж (правый верхний угол) появляется попап с формой. При желании, можно продублировать в самом низу, но туда мало кто доходить будет, так как страница очень длинная. В любом случае, для этой формы дизайн не нужен, просто использовать стандартный инпут.

**Comment by iliakan** [comment]
А попап с формой как выглядит?

**Comment by iliakan** [comment]
Внизу тоже нужно. Сверим потом статистику :)

**Comment by iliakan** [comment]
По подписке - сейчас я вообще без дизайна страницы "unsubscribed" и "subscribed" вывожу - тоже он нужен.

**Comment by Bezart** [comment]
не понял последний камент. Касательно формы — добавил в исхоник: http://take.ms/wg0CK

**Comment by iliakan** [comment]
Попробуй подписаться - увидишь страницы без дизайна.

**Comment by Bezart** [comment]
Подписался, на почту ничего не упало... Не вижу смысла в отдельно что-то придумывать. Кидаешь на страницу скринкаста со стандартным сообщением вверху (зеленым), либо на главную стр (более общий вариант)

**Comment by Bezart** [comment]
Получил нотификацию, кликнул, получаю 404

**Comment by iliakan** [comment]
Обычно страницы подписки и отписки везде другие. Сколько ни видел сайтов - там мини-страница "вы подписаны/вы отписаны". Это основная и единственная информация.

Проверю форму.

**Comment by iliakan** [comment]
Давай вместе попробуем.
У меня показывает так: http://ilyakantor.ru/screen/2015-03-20_1824.png

P.S. Кстати, я поменял способ вставки картинки в письмо - теперь просто ссылкой, без base64.

**Comment by iliakan** [comment]
закрываю эту issue, т.к. она по дизайну, остаётся по вёрстке.
