### ISSUE TITLE
Публичный профиль: тесты

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#309]
Где и как в публичном профиле (при заходе другим юзером) будут показываться результаты тестов?

Сейчас там только инфа о юзере в дизайне.

**Comment by Bezart** [comment]
Результаты тестов не будут видны никому другому, мы об этом договаривались когда обсуждали публичный профиль

**Comment by iliakan** [comment]
Наоборот, это публичный профиль, человек проходит тесты и потом может показать их результаты всем "вот какой я крутой (с)"

**Comment by Bezart** [comment]
Я бы очень не хотел так делать. Публичные результаты очень сильно подталкивают к читу и вообще негативно влияет на привлечение пользователей (даже учитывая что у нас есть кнопка Сохранить) Я предлагаю сделать тесты в первую очередь для личного использования, и может быть добавить кнопку "Скачать сертификат" или share для соц сетей.

**Comment by iliakan** [comment]
Если человек не хочет делать результат теста публичным - он может так не делать.

Что касается чита - любые интернет-тесты подвержены читам. Тем не менее, они есть даже в серьёзных конторах типа ODesk, и они "работают" (все всё понимают про читы).

Как публичные результаты тестов могут негативно влиять на привлечение пользователей? Их сохранение сугубо опционально.

**Comment by Bezart** [comment]
Функция сохранения однозначно не должна публично работать. Многие пользователи предпочитают сохранять собственный прогресс и никому его не показывать. Это психологический барьер такой.

С другой стороны, какую проблему ты хочешь решить тем что при сохранении любой сможет увидеть результат? В этом случае нужно показывать сообщение под кнопкой, которое будет говорить что под собой подразумевает сохранение, что, я уверен, негативно скажется на количестве сохраненных тестов.

Если это так важно, я предлагаю сделать opt-in, то есть добавить чекбокс "сделать публично доступным в профиле". Так ты сможешь затрекать сколько людей предпочитает эту опцию.

**Comment by iliakan** [comment]
Кнопка сохранения сейчас на сайте называется "Сохранить в публичном профиле" .
Это делает происходящее самоочевидным.

**Comment by Bezart** [comment]
Но не дает сохранить без публичного шаринга... я считаю что нужна такая возможность

**Comment by iliakan** [comment]
Давай отложим решение по такой возможности.

Сейчас пока все сохранения будут публичными. Это гораздо более востребованная функциональность, чем непубличное сохранение.

**Comment by Bezart** [comment]
В данный момент страница выглядит так: http://monosnap.com/image/oHmTUwQhdXTzowDZOlukr7ejCR9wEp

Какую из этой информации ты бы хотел оставить/убрать?

**Comment by iliakan** [comment]
Тест, Результат, Время прохождения обязательны.
Уровень - опционально.

(И это будет на одностраничном публичном профиле, ты дал скриншот при заходе от имени посетителя).

**Comment by Bezart** [comment]
Решили сделать табы и полностью открыть тесты в этом виде http://monosnap.com/image/oHmTUwQhdXTzowDZOlukr7ejCR9wEp
