### ISSUE TITLE
Task 'truncate string': Incorrect example of the expected result of the function

### ISSUE THREAD

**Issue by baranovRP** [iliakan/javascript-nodejs#310]
# Incorrect example of the expected result of the function
*link:* https://nightly.javascript.ru/string#усечение-строки

*description:*
Создайте функцию truncate(str, maxlength), которая проверяет длину строки str, и если она превосходит maxlength — заменяет конец str на "...", так чтобы ее длина стала равна maxlength.
Результатом функции должна быть (при необходимости) усечённая строка.
*example:*
truncate("Вот, что мне хотелось бы сказать на эту тему:", 20) = "Вот, что мне хотело..."

Actual result:
"Вот, что мне хотело..." length is 22

Expected result
should be "Вот, что мне хоте..." lenght is 20

**Comment by iliakan** [comment]
Не понял.

Тесты ведь проходят?

**Comment by iliakan** [comment]
Что именно не так и в каком месте?

**Comment by baranovRP** [comment]
Да тесты проходят. Не верно описание
truncate("Вот, что мне хотелось бы сказать на эту тему:", 20) = "Вот, что мне хотело..."
строка которая приведена в качестве примера содержит 22 символа, а согласно описания задачи длина строки вместе с добавленными символами должна содержать 20 символов, т.е. "Вот, что мне хоте..."
Просто надо подправить описание 
truncate("Вот, что мне хотелось бы сказать на эту тему:", 20) = "Вот, что мне хотело..." ->
truncate("Вот, что мне хотелось бы сказать на эту тему:", 20) = "Вот, что мне хоте..."

**Comment by iliakan** [comment]
thanks, fixed, to be deployed.
