### ISSUE TITLE
Задача 'Что не так в тесте?': в описании неверно указан ожидаемый рез-т

### ISSUE THREAD

**Issue by baranovRP** [iliakan/javascript-nodejs#311]
# Задача 'Что не так в тесте?': в описании неверно указан ожидаемый рез-т
*link:* https://nightly.javascript.ru/testing#что-не-так-в-тесте
в тесте проверки значения 5 в степени 3 не верно указан ожидаемый рез-т вместо 125 указано 25.

![image](https://cloud.githubusercontent.com/assets/2158131/6546272/15a96284-c5ae-11e4-8252-2bb39dc6b6dc.png)

**Comment by iliakan** [comment]
typo fixed.
