### ISSUE TITLE
Битая ссылка

### ISSUE THREAD

**Issue by gualex** [iliakan/javascript-nodejs#319]
https://nightly.javascript.ru/debugging-chrome
Официальная документация (на англ.)
https://developers.google.com/chrome-developer-tools/docs/overview

**Comment by iliakan** [comment]
Fixed.

**Comment by gualex** [comment]
Сайт имеет смысл прогнать через автоматический детектор битых ссылок.
Например, внутренние битые ссылки на:
https://nightly.javascript.ru/article/js-animation/move/animate.css
https://nightly.javascript.ru/article/js-animation/move/move.js
https://nightly.javascript.ru/article/js-animation/width/animate.css
https://nightly.javascript.ru/article/js-animation/width/width.js
https://nightly.javascript.ru/article/multi-insert/insertAdjacentHTML.js
https://nightly.javascript.ru/article/settimeout-setinterval/setInterval-anim/
https://nightly.javascript.ru/article/settimeout-setinterval/setinterval-interval.svg
https://nightly.javascript.ru/article/settimeout-setinterval/settimeout-interval.svg
https://nightly.javascript.ru/event-onscroll
https://nightly.javascript.ru/files/tutorial/ajax/script/scriptRequest.js
https://nightly.javascript.ru/files/tutorial/browser/cookie/cookie.js
https://nightly.javascript.ru/files/tutorial/intro/array/sieve.gif
https://nightly.javascript.ru/files/tutorial/window/facebook.html
https://nightly.javascript.ru/nodejs-screencast
https://nightly.javascript.ru/task/setter-onReady
https://nightly.javascript.ru/zip/tutorial/ajax/websocket.zip

Есть еще полторы сотни редиректов, которые могут вести в никуда.
