### ISSUE TITLE
Опечатки и прочие мелочи в разделах Числа и Строки.

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#320]
***********
Опечатки

1. Опечатка в [разделе "Числа", параграф "Тригонометрия"](https://nightly.javascript.ru/number#%D1%82%D1%80%D0%B8%D0%B3%D0%BE%D0%BD%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F):  
Math.atan написан без аргумента (x) в отличие от остальных функций.

2. Опечатка в [разделе "Строки" параграф "Отрицательные аргументы"(последний абзац)](https://nightly.javascript.ru/string#%D0%BE%D1%82%D1%80%D0%B8%D1%86%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B):
> Если выбирать из этих трёх метод один, ...

По идее, должно быть "методов", хотя для магистра Йоды - вполне. :smirk:

***********
Мелочи, на которые можно забить

1. Пожелание для раздела "Строки" параграф "Поиск подстроки":
Указать, что поиск при помощи функции indexOf() регистрозависимый.

2. Наползание на текст примера значка "выполнить" (:arrow_forward:) в [разделе "Строки"   "Посимвольное сравнение"](https://nightly.javascript.ru/string#%D0%BF%D0%BE%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5):
> alert("2" > "14"); // true, так как это строки, и для первых символов верно "2" > "1"

Последние пару символов перекрываются даже при максимальной ширине. Ничего страшного, можно забить, но и не очень симпатично. Легко исправить, сократив "так как" до "т.к.". Сработает только для макс. ширины, конечно (правда, в Хроме почему-то при дальнейшем увеличении окна все только ухудшается - появляется горизонтальная прокрутка).

**Comment by iliakan** [comment]
Fixed кроме налезания, там opacity есть на кнопке, вроде видно что под ней. 

Перевод строки можно `float`ом на кнопке, наверно, исправить? Как считаешь, @tyv?

**Comment by discodanser** [comment]
Да реально, на это можно забить, все равно при уменьшении ширины текст будет под кнопками или вообще с горизонтальной прокруткой. Это из разряда обостренного перфекционизма, просто можно без особых затей сделать чуть симпатичней вид хотя бы при максимальной ширине.  Хотя, в принципе, и opacity до 0.6 можно уменьшить смело.
