### ISSUE TITLE
Расстановка пробелов в стиле кода

### ISSUE THREAD

**Issue by gualex** [iliakan/javascript-nodejs#321]
https://nightly.javascript.ru/coding-style
Тема расстановки пробелов совершенно не раскрыта.
На эталонной картинке https://nightly.javascript.ru/article/coding-style/code-style.svg
После for нет пробела: `for(var i = 0; i < n; i++) {`
После *= нет пробела: `result *=x;`
Во множестве примеров кода (в т.ч. на этой же странице) пробелы расставляются хаотично.

**Comment by iliakan** [comment]
Картинку поправил.

Что не раскрыто в плане расстановки пробелов?

Да, хорошо бы поправить стиль примеров, хотя я не всегда ставлю пробелы именно так, иногда группирую без пробелов подвыражения, т.е. возможно "хаос" на самом деле упорядочен.

**Comment by gualex** [comment]
Про расстановку пробелов просто нет раздела.
Хотелось бы видеть раздел, как здесь: http://javascript.crockford.com/code.html Whitespace
На той же странице встречаются примеры:
`for (var i = 0; i < n; i++) {`
`for (var i=0; i<10; i++) {`
Я не вижу в этом "хаосе" упорядоченности :)

**Comment by iliakan** [comment]
М-м, да, я то так то эдак пишу, автоформаттер меня обычно поправляет. 
Может натравить его на все примеры сайта.

**Comment by gualex** [comment]
Некоторые примеры являются некорректными (фрагменты).
Например, с многоточием: 
```
if (0) { // 0 преобразуется к false
  ...
}
```
Средство форматирования должно это учитывать или хотя бы не напортачить в таких местах.

**Comment by iliakan** [comment]
Сделал gulp-task, который прогоняет весь код из учебника через js-beautify, спрашивая подтверждение на каждом примере.

Прогнал через него 1ю часть. Теперь лучше? :)

**Comment by iliakan** [comment]
P.S. Из beautify временно исключены примеры с инлайн-подсветкой, их нужно руками. И некоторые другие, где "однострочные" функции и объекты оставлены намеренно.

**Comment by iliakan** [comment]
И ещё beautify на остатке учебника. Бу-бумс :/
