### ISSUE TITLE
Не выводится пояснение об ошибке в тестах

### ISSUE THREAD

**Issue by electrovladyslav** [iliakan/javascript-nodejs#323]
В разделе https://nightly.javascript.ru/testing#другие-assert третьим аргументом выводиться пояснение об ошибке. Но в iframe  сообщение об ошибке без пояснения, т.е. такое же, как и в предыдущем iframe.

**Comment by iliakan** [comment]
Посмотрите сейчас?

Если проблема всё ещё есть, то можно скриншот?

**Comment by electrovladyslav** [comment]
При заходе на страницу всех iframes были пустыми. Проверил в Хроме, Фаерфоксе и ИЕ. Увидел пиктограмму щита рядом с адресом, нажал на неё, разрешил загрузку скриптов из непроверенных источников. 

Теперь всё работает, пояснение выводится. Только рядом с адресом зачёркнуто https.
