### ISSUE TITLE
Предложение. Отладка в браузере - Ошибки - Другой способ перехода на ошибку

### ISSUE THREAD

**Issue by Kiwka** [iliakan/javascript-nodejs#325]
> Красная строка — это сообщение об ошибке.
> В чём дело? Если мы хотим понять, что случилось — перейдём в отладчик.

Можно добавить также другой способ перехода на ошибку, информация о которой появилась в консоли. Нужно кликнуть по ссылке на файл в окне консоль (в этом случае это pow.js:3), и пользователь перенесется на вкладку Sources на код, который вызвал ошибку. 

"+" такого способа - меньше необходимых действий, нет нужды в перезагрузки страницы

**Comment by iliakan** [comment]
Добавлены разъяснения, почему так.
