### ISSUE TITLE
Переход на страницу "Единицы измерения: «px», «em», «rem» и другие"

### ISSUE THREAD

**Issue by Kiwka** [iliakan/javascript-nodejs#327]
При переходе на страницу https://nightly.javascript.ru/css-units  начальная позиция для просмотром пользователем страницы находится не на верху страницы, а на следующей части страницы http://i.imgur.com/dgPFEWG.png

**Comment by iliakan** [comment]
Да, странно, интересно почему?

**Comment by iliakan** [comment]
Проблема была в autoscroll при autorun + в вёрстку изначальную добавил iframe с правильным размером.
