### ISSUE TITLE
Непонятные смайлы

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#331]
Объясни плиз что нужно объяснить в серии подобных иллюстраций: http://take.ms/N7GhP

**Comment by iliakan** [comment]
Не получается "заматчить" регулярное выражение на этой позиции.

**Comment by iliakan** [comment]
Там алгоритм поиска проиллюстрирован.

**Comment by iliakan** [comment]
Картинка по сути отображает тот же процесс, что witch*
