### ISSUE TITLE
Навигация для телефонов (узкий экран)

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#332]
На почту писал, пишу здесь чтоб не забыть.

**Comment by Bezart** [comment]
Добавил в исходник на страницу responsive (iPhone / Main Menu): http://take.ms/IVmtD

**Comment by tyv** [comment]
а тут что? убрать label и черно-белые иконки сделать?

**Comment by iliakan** [comment]
Сейчас там так: http://ilyakantor.ru/screen/2015-03-12_1656.png

Иконки при наведении подсвечиваются обычно, для того чтобы на мобильных не было глюков (`:hover` глючит), у нас предусмотрен класс `.hover`, который добавляется из JS, если есть атрибут `data-add-class-on-hover`.

Пример в действии: http://ilyakantor.ru/screen/2015-03-12_1659.png

```
<button data-sidebar-toggle="" data-add-class-on-hover="" class="sidebar__toggle"></button>
```

**Comment by iliakan** [comment]
Да, наведение пока не работает, вместо "Полное содержание" может выводить иконку карты учебника, @Bezart ? 

Или вообще без этого пункта справа? Человек может открыть эту верхнюю навигацию, находясь не только в учебнике, будет непонятно что за содержание.

**Comment by iliakan** [comment]
Баг с пустым местом справа, мб связан, на всякий случай тут пишу
http://ilyakantor.ru/screen/2015-03-13_1852.swf

**Comment by skparallax** [comment]
Есть предложение, чтобы на главной странице меню открывалось как у @Bezart на картинке:

![Alt text](https://monosnap.com/file/0hds07RJgHn0Zara9bhqOEZ1cMIMlg.png)

... а на внутренних страницах подгружалась навигация по странице:

![Alt text](https://monosnap.com/file/5W6lfJgpdeULOwHdlyDjXzZ36TY6uL.png)

... чтобы, если надо быстро посмотреть, что там в ИТОГО, не нужно было мотать каждый раз. 

И иконка карты рядом, кому нужно.

**Comment by Bezart** [comment]
Линка "Карта учебника" используется для того чтобы подчеркнуть что это не карта всего сайта, а конкретно этого раздела, поэтому хотелось бы по возможности ее показывать. Я обновил в спеке макет после обсуждения с Ильей, пришли к следующему варианту: http://take.ms/czznC

**Comment by tyv** [comment]
@iliakan тут все?

**Comment by iliakan** [comment]
Кнопки "поделиться" не подсвечиваются при наведении на узком экране. А у тебя подсвечиваются?

**Comment by tyv** [comment]
нет, но кажется и не должны, у телефонов/планшетов нет hover

**Comment by iliakan** [comment]
@Bezart 

Как считаешь, правильно ли что кнопки "поделиться" в этом варианте вообще бесцветные?
https://camo.githubusercontent.com/8e5ca5a711a01cf45a8cdfb99c1b9a52de54ea9d/68747470733a2f2f6d6f6e6f736e61702e636f6d2f66696c652f3557366c664a67706465554c4f7748646c79446a587a5a3336545936754c2e706e67

Будет ли кто-то по ним вообще кликать в таком варианте?

**Comment by Bezart** [comment]
Да, ты прав, должны быть http://take.ms/wRFRA

**Comment by iliakan** [comment]
@tyv внеси изменения, плиз.
