### ISSUE TITLE
Свойство white-space. Неудачный пример

### ISSUE THREAD

**Issue by Kiwka** [iliakan/javascript-nodejs#333]
Не совсем удачный пример для илюстрации значений "pre-wrap" и "pre-line":
> if (hours > 18) {
// Пойти поиграть в теннис
}

Поскольку визуально не заметна и непонятна разница между этими значениями: 
![image](https://cloud.githubusercontent.com/assets/6034955/6596528/d73cbb52-c7fd-11e4-8d1d-a0aa7cbd863d.png)

**Comment by iliakan** [comment]
В каком браузере смотрите?

**Comment by Kiwka** [comment]
Chrome Версия 40.0.2214.115

**Comment by iliakan** [comment]
Thanks fixed.
