### ISSUE TITLE
Опечатка на странице "Клавиатура: keyup, keydown, keypress"

### ISSUE THREAD

**Issue by skparallax** [iliakan/javascript-nodejs#342]
https://nightly.javascript.ru/keyboard-events#скан-коды

>Для других *другими* символов, например, *знаками пунктуации*, есть таблица кодов, которую можно взять, например, из статьи Джона Уолтера:

Правильный вариант:

Для других символов, например, знаков пунктуации, есть таблица кодов, которую можно взять, например, из статьи Джона Уолтера:

**Comment by iliakan** [comment]
fixed thanks.
