### ISSUE TITLE
Поле тестового стенда вылазит за границы при зуме

### ISSUE THREAD

**Issue by skparallax** [iliakan/javascript-nodejs#343]
https://nightly.javascript.ru/keyboard-events#keyboard-test-stand

![screen shot 2015-03-13 at 19 10 28](https://cloud.githubusercontent.com/assets/10166916/6643483/3207a1a6-c9b5-11e4-8001-f3bcfc53b2a2.png)

Может, имеет смысл переносить чекбоксы вместе с их названиями при увеличении или при изменении ширины экрана, чтобы вместо

☑ 
keypress

было

☑keypress

Перфекционизм, конечно :smile:

**Comment by skparallax** [comment]
И расстояние просится между кнопкой и текстовым полем

**Comment by iliakan** [comment]
layout fixed a little bit.
