### ISSUE TITLE
Форма поиска (узкий экран)

### ISSUE THREAD

**Issue by skparallax** [iliakan/javascript-nodejs#345]
Android 4.0.3, Chrome, экран 320px

Не влазит текст "Искать в учебнике", кнопка "Найти" не адаптивная:

![Alt text](https://monosnap.com/file/I6k5by3UiHPcQ7NAHcwORyokFPp1sk.png) 

Как вариант можно адаптировать кнопку так:

![Alt text](https://monosnap.com/file/BJL6wBoEmyXNeAgFVbj7umYR653RdM.png)

Или даже так:

![Alt text](https://monosnap.com/file/UlI1hHWlTeD8RHo3a3Un2kXYGmQXyg.png)

Или так:

![Alt text](https://monosnap.com/file/LnHUmcTYa55Bc8QasUmdjsrzv0SNZm.png)

На большом экране форма поиска посередине на главной странице смотрится шикарно. На маленьком экране не понятно зачем две формы, которые делают одно и тоже (пока во всяком случае) - в углу и в середине? Лишнее место. 

Может оставить только в углу, это будет более привычно для мобильных юзеров? 
Или на гавной только одна посередине, на остальных как сейчас и есть в углу?

Кстати, лупа почему-то закрашена полностью.

**Comment by skparallax** [comment]
Основная форма поиска вылазит за границы

![Alt text](https://monosnap.com/file/UOfXqIfQ0q96ONthkibwjc2A95rlUL.png)

Может убрать кнопку совсем, как вариант и запускать поиск кнопкой на клавиатуре?

![Alt text](https://monosnap.com/file/r5FZ9ifqTCoGT9xeWQbjajvPyYsInr.png)

**Comment by Bezart** [comment]
В обновленной версии макетов, поиск адаптивный Responsive Logic / iPhone / Search, его просто еще не заимплементили.

**Comment by iliakan** [comment]
@Bezart поясни плиз, мы что-то делаем конкретно по этой issue?

Фикс кнопки на главной нужен? 
Поиск адаптивный из другой issue все остальное учитывает?

**Comment by Bezart** [comment]
Зависит от того, сможем ли мы новый поиск на десктопе реализовать. Хотелось что бы поиск был таким:

Десктоп:
http://take.ms/zzMMH

Таблетки:
http://take.ms/wITK8

Смартфоны:
http://take.ms/nUYOU

**Comment by iliakan** [comment]
Сможем, @tyv?

**Comment by tyv** [comment]
мы сейчас не делим на смартфоны и таблетки
я пока сделаю в 2 вариантах

**Comment by tyv** [comment]
а вижу что для шаки есть отдельный media
ок, будет три

**Comment by tyv** [comment]
исходя из дизайна непонятно куда кликать чтобы вернуть все взад

**Comment by tyv** [comment]
@Bezart ^^

**Comment by Bezart** [comment]
http://take.ms/JmL1w добавил в исходник

**Comment by Bezart** [comment]
Альтернативный вариант после обсуждения в гиттере: http://take.ms/Ab2qT 
1. Тап по затемненной области схлопывает поиск
2. Крестик появляется если поле не пустое. Клик по нему стирает значение поля

**Comment by tyv** [comment]
а в десктопе?

**Comment by Bezart** [comment]
На десктопе схлопываем по онфокусаут, как на apple.com или trello
