### ISSUE TITLE
Safari: issue with image

### ISSUE THREAD

**Issue by pomidorchi** [iliakan/javascript-nodejs#347]
В Safari 8.0.3 неполностью отображаются svg картинки в уроке https://nightly.javascript.ru/coding-style 
Screenshot: https://dl.dropboxusercontent.com/u/818189/scr/2014/2015-03-14_22_safari-bug.png
В последнем Chrome при этом всё хорошо.

**Comment by iliakan** [comment]
Дурацкий Safari. Там, видимо, старый баг с SVG, в котором PNG.
