### ISSUE TITLE
Поля и отступы (экран 320px)

### ISSUE THREAD

**Issue by skparallax** [iliakan/javascript-nodejs#348]
Android 4.0.3; Chrome browser; Screen 320px;

Есть предложение уменьшить поля и отступы для мобильных экранов. Это то, что сразу бросается в глаза, как только заходишь на страницу.

* paddings по бокам в `.page__inner` меньше (например, 15px вместо 20px)?

![Alt text](https://monosnap.com/file/7XspWM3rb4IHpJd1NFNMl2A0W6Kff5.png)

* левый отступ от номеров строк меньше?

![Alt text](https://monosnap.com/file/M6O3Vn9XXvr2dJFIhFvgPoochUEvNn.png)

* margins по бокам в `.important__content` меньше?

![Alt text](https://monosnap.com/file/VqtUjOcwKKfMv5NP7GpBGPoVQ8Bvyw.png)

* отступы от края `lessons-list` до содержимого меньше?

![Alt text](https://monosnap.com/file/LaP3kN2jxyvRibb9p6Ea0IWDqzHyQX.png)

* margins по бокам в `.course-info__content` меньше?

![Alt text](https://monosnap.com/file/t94dlCJusOXtTHn0JlBUgKb5zuWrKW.png)

**Comment by iliakan** [comment]
@Bezart, попрошу Юру на глазок сделать или какие-то пожелания?

**Comment by Bezart** [comment]
Предложение стоящее, меня самого отступы смущают. Можно для начала в 2 раза их уменьшить а потом посмотреть.

**Comment by tyv** [comment]
все кроме листинга кода сделаю (там запас для трехзначных чисел)

**Comment by tyv** [comment]
я делал для @media tablet (это от <=840px) думаю так же актуально

**Comment by iliakan** [comment]
@skparallax сейчас - лучше?

**Comment by skparallax** [comment]
@iliakan значительно лучше чем было!
Потестил на 320px, есть 3 момента:

* отступы в оглавлении (просится одинаковое расстояние от края до номера и от номера до текста)
* разваливается навигация

![Alt text](https://monosnap.com/file/Lno08zqX3VYdIqA5Ey3uPtLy6bDieU.png)

* и отступы от номеров строк до края в примерах кода
даже когда код просто в тексте, это бросается в глаза, а когда он в списке, где итак отступ, то вообще смотрится косо

![Alt text](https://monosnap.com/file/SM3TIuBRtymLFhpjiha5g7MDfmzYgZ.png)

**Comment by tyv** [comment]
>> и отступы от номеров строк до края в примерах кода 
я тут ничего не сделаю вероятно

**Comment by tyv** [comment]
> отступы в оглавлении (просится одинаковое расстояние от края до номера и от номера до текста)

тут тоже, потому что там также запас сделан для двузначных чисел

**Comment by iliakan** [comment]
Технически даже и можно сделать доп. классом, чтобы у кода отступ был разный, в зависимости от количества строк: 0-9, 10-99, 100+. 

Но тогда когда на странице несколько фрагментов кода, то горизонтальная позиция кода "прыгает" влево-вправо, ведь ширина поля со строками то одна, то другая. Это не очень красиво.
