### ISSUE TITLE
Быстрый доступ

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#349]
От @skparallax

Столкнулся с такой же проблемой, как и @LeusMaximus - быстро найти какую-то информацию.

Грубо говоря, я захожу на сайт с мобильного, когда надо `быстро найти какую-то информацию` или `освежить что-то в голове`, а компа под рукой нет - в метро, например. То есть все сводится к `зашел-посмотрел-ушел`.

@smmurf, про кнопку быстрой прокрутки, я уверен, большинство юзеров не знают или, по крайней мере, не знают как ее вызвать. Я, например, всегда, как @iliakan, кручу-кручу. 

Получается, чтобы посмотреть что-то в разделе "Итого" (отдельное спасибо @iliakan за резюме всей информации в конце страницы - то, что надо) на странице "Массивы: методы" мне нужно прокрутить страницу `18 (!) раз` и потратить `22-24 секунды`. А если потом нужно промотать куда-то в середину, то совсем беда.

Еще нужно учитывать, что у многих 3G с невысокой скоростью и приходится ждать, когда все подгрузится. Я как юзер, прежде чем зайти на страницу снова, еще подумаю, а в 3й раз точно не приду.

Кнопка "Back-to-top", @LeusMaximus, всей проблемы не решит - наверх, как сказал @Bezart, мало кому надо, а надо что-то быстро найти.

Предлагаю для мобильной версии сделать меню, про которое я писал в #332 и прилепить его наверху:

![Alt text](https://monosnap.com/file/wtwIJYuHHePuYmI3rY0LrArnbkzo0b.png) 

![Alt text](https://monosnap.com/file/5W6lfJgpdeULOwHdlyDjXzZ36TY6uL.png)

40px сверху погоды не сделают, зато:
* навигация по учебнику будет под рукой
* плюс навигация по странице  (а это важно, учитывая объем информации на страницах)
* поиск с любого места
* плюс ссылка в личный кабинет (думаю, там будет выпадашка по разделам)

Что думаете?

**Comment by iliakan** [comment]
@skparallax: имхо проскроллить вверх или вниз каждый может быстро. Статьи не настолько больше.

Можем вниз добавить поиск, what you think, @Bezart  (к #113).

**Comment by skparallax** [comment]
@iliakan, проблема не столько в предыдущей-следующей странице, сколько в навигации внутри данной страницы. И, потом, до конца страницы тоже скроллить надо... 

Материала много, хочется прыгать туда-сюда по странице, а приходится `крутииииииииииить` :smile:

Снова пересмотрел все страницы на мобильном - для лаптопа статьи средние, а для мобильника все-таки большеватые.

**Comment by skparallax** [comment]
И потом, хорошо, когда есть место, где можно посмотреть все подразделы на странице - типа оглавление. Вот чего не хватает.

Может что-то такое вначале?

![Alt text](https://monosnap.com/file/SBt2inqsb9btfiBJqhhcBteZGaieR2.png)

**Comment by Bezart** [comment]
Касательно якорей-ссылок спрятанных за гамбургер-меню, пользователи вряд ли там будут искать навигацию по уроку. Эта кнопка используется для глобальной навигации.

Последний вариант норм, но на первом экране одни ссылки и заголовок остаются, что мне не оч нравится. Предлагаю собрать больше информации о том, как пользователи юзают ресурс на мобильных устройствах, а потом уже принимать решения об улучшениях.

**Comment by iliakan** [comment]
Рассмотрим это после релиза.
