### ISSUE TITLE
Опечатки и прочие мелочи в разделах Замыкания, Функции, Массивы и т.д.

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#353]
1)   Опечатка в разделе "Замыкания, функции изнутри", параграф [Вложенные функции](https://nightly.javascript.ru/closures#%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8):

>  ...если переменная не найдена во внешнем объекте переменных, то она ищется ещё более внешнем... 

Пропал предлог "в".
********************************
2)   Непонятность. Тот же раздел, параграф [Всегда текущее значение](https://nightly.javascript.ru/closures#%D0%B2%D1%81%D0%B5%D0%B3%D0%B4%D0%B0-%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B5-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5):

>  Это естественно, ведь для доступа к внешним переменным функция хранит ссылку [[Scope]] на весь внешний объект с ними, а не на каждое его свойство (переменную) по отдельности. 

В контексте примера не понял, могла быть разница, на весь объект или на каждое свойство? 

*********************
3)   Пожелание. Тот же раздел, [Пример](https://nightly.javascript.ru/closures#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80):

> В конце выполнения функции объект с переменными обычно выбрасывается и память очищается.

Было бы неплохо добавить, что исключение составляют замыкания с возвратом функции, которые будут рассмотрены чуть ниже. Тема и так непростая, мягко говоря, любая мелочь может помочь людям.

***************** 
 4)   Пожелание. Раздел "Объекты: перебор свойств", [Итого](https://nightly.javascript.ru/object-for-in#%D0%B8%D1%82%D0%BE%D0%B3%D0%BE) :

> Для того, чтобы гарантировать перебор ключей в нужном порядке, их делают «нечисловыми», например добавляя в начало +, а потом, в процессе обработки, преобразуют ключи в числа.

Звучит крайне неоднозначно. В примере выше можно найти разъяснение, но некоторые могут ограничиться "Итого". А для новичка сделать что-то нечисловым, добавив +, однозначно ассоциируется с приведением типа. Возможно лучше будет уточнить ситуацию как-то так:
"...их делают «нечисловыми», например добавляя в начало "+" (например, "+7..."), а потом..." .

************************

5)   Уточнение. Раздел "Массивы c числовыми индексам",  [Конец массива](https://nightly.javascript.ru/array#%D0%BA%D0%BE%D0%BD%D0%B5%D1%86-%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%B0):

> Является полным аналогом fruits[fruits.length] = ....

Это написано про push. Для данного примера так. Но в общем смысле, push более широкий функционал имеет, он может добавлять по несколько значений за раз через запятую x.push(a,b,c), в отличие от x[x.length]=.
Т.е. желательно либо конкретизировать, что это для данного примера, либо переписать предложение с нуля.

***************************
6)   Пожелание. Раздел "Массивы: методы", [Метод splice](https://nightly.javascript.ru/array-methods#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-splice):

> Метод splice возвращает массив из удаленных элементов

Выделить жирным или выделить и перенести повыше к объявлению метода.

*******************

7)   Пожелание. Раздел "Условные операторы: if, '?'", [Оператор вопросительный знак '?'](https://nightly.javascript.ru/ifelse#%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B7%D0%BD%D0%B0%D0%BA):

Желательно указать обязательность возвращаемых значений, что надо ставить какие-нибудь заглушки, типа "". А то люди могут быть избалованы тем, что в циклах можно не указывать ничего for (;;).

Кстати (необязательно для учебника), заодно в копилку страшилок для любителей не ставить точки с запятой (помимо вызова фунциии на месте, по-моему, про что где-то в учебнике упоминалось)  можно добавить аналогичную(в плане скобок) фичу убивания скрипта отсутствием точки с запятой перед скобками условного выражения оператора "?". Если скобок нет - то все нормально. 

********************
8)   Пожелание. Раздел "Числа", [NaN](https://nightly.javascript.ru/number#nan):

> Если аргумент isNaN — не число, то он автоматически преобразуется к числу.

Желательно перенести поближе к 

> Значение NaN можно проверить специальной функцией isNaN(n), которая возвращает true если аргумент — NaN и false для любого другого значения. 

(чтобы особенности функции в одном месте были.)

**********************

Сорри за такую простыню.

**Comment by iliakan** [comment]
Сделано кроме 7, 8. Не понял их.

**Comment by discodanser** [comment]
7)   Нельзя написать 

> a > b ?  : a+b;   или   a > b ? a+b : ;  // будет ошибка

Нужно обязательно писать 

> a > b ? "" : a+b;   или   a > b ? a+b : "" ;  // с заглушкой в виде "" или чего-то еще.

Вот о обязательности заполнения всех полей оператора я и предлагал написать.

А тот же if вполне может обойтись без else, или for можно писать вообще ничего не заполняя for (;;).

8)   Желательно, чтобы описание работы фунции не размазывалось по параграфу, а находилось в одном месте. Да еще и выделялось как-нибудь.
В данном случае, упоминание о приведении аргумента к числу не так далеко находится от основного описания функции isNaN, однако все равно я в каком-то упражнении умудрился написать что-то вроде isNaN(+arg). В моем случае это не ошибка, конечно, но случаи бывают разные.
А все потому, что глянул параграф только в том месте, где идет первое описание функции(о возвращаемых параметрах), а ниже читать не стал - вроде как функция простая и т.д. и т.п.

**Comment by iliakan** [comment]
7) проблем вроде таких не было ни у кого, видимо очевидно выяснить самому.
8) Поправил.
