### ISSUE TITLE
Баннер для старого сайта для перехода на новую версию

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#354]

**Comment by iliakan** [comment]
Два дизайна:
1) Для старого learn
2) для javascript.ru

Замена старого learn, я надеюсь, будет весьма скорой. Старый javascript.ru будет ещё долго жить, там форум.

**Comment by Bezart** [comment]
А что есть такого на старом learn  что мы должны его рекламировать на новом сайте? 

Я так, кстати, и не понял причину по которой ты http/https делаешь. Почему бы просто не заменить текущий learn новым?

**Comment by iliakan** [comment]
Ну гм, перестраховываюсь. Можно и заменить, в принципе.

**Comment by iliakan** [comment]
Тогда получается, баннер не нужен совсем.
