### ISSUE TITLE
Powered by IO.JS

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#356]
Мб добавить бы куда-нить в футер, м? :)
Модная штука, и у нас сайтик на неё.

Лого FTW: https://iojs.org/images/1.0.0.png

**Comment by Bezart** [comment]
Можно, только в текстовом формате, чужих лого в футере не нужно.

**Comment by Bezart** [comment]
что-то типа http://monosnap.com/image/YYHrCqtiw0FTebewNIkO1SthVKVrw4

**Comment by iliakan** [comment]
@tyv, футер плиз добавь в текущую вёрстку.

**Comment by tyv** [comment]
сделано на io.js не очень правильная формулировка кажется

**Comment by tyv** [comment]
но я добавлю

**Comment by tyv** [comment]
я включил какой-то старый футер в верстке, он выглядит так:
https://yadi.sk/i/m0nAzQW-fNSt7

его можно убить?

**Comment by iliakan** [comment]
Да, это предварительный вариант был старый, убить.
Слова будут "powered by io.js", но это я руками поправлю.

**Comment by iliakan** [comment]
Футер - это blocks/page-footer.jade в боевые шаблоны скопировать и подключить... Куда?

В `body.jade` под `.page` - ок?

**Comment by tyv** [comment]
да

**Comment by iliakan** [comment]
done.

**Comment by iliakan** [comment]
Проблемка: футер не прилипает к концу страницы на невысоких документах: http://ilyakantor.ru/screen/2015-03-24_1208.png
