### ISSUE TITLE
Тесты: просмотр ответов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#357]
Прошёл тест на quizful, вот результат:
http://ilyakantor.ru/screen/2015-03-17_1531.png

Может, и нам так же сделать? 
Чтобы правильные ответы не смотрели вот так прям сразу.

**Comment by Bezart** [comment]
Мне это не очень нравится, давай оставим как есть. Тесты на то и тесты чтобы видеть где ты ошибся после их прохождения. Те кому нужно считить и так это сделают. Это одна из причин по которой я не при сохранении делать результаты публичными
