### ISSUE TITLE
Дизайн: Баннер Webstorm

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#358]
Тут всё ок с вертикальным выравниванием?
http://ilyakantor.ru/screen/2015-03-17_1708.png

**Comment by Bezart** [comment]
давай на странице посмотрим. Добавь только ему 1px border серый

**Comment by iliakan** [comment]
Там ещё кнопочка закрытия должна быть, помнишь как мы говорили? Как в старом дизайне.

Нарисуй плиз, как это будет выглядеть. В рамке она или вне рамки, или вообще как?

**Comment by Bezart** [comment]
http://take.ms/IBLmL вот, соответственно тому требованию которое мы им кидали

**Comment by iliakan** [comment]
А на главной учебника как расположена покупка учебника и этот баннер?
Вот тут http://ilyakantor.ru/screen/2015-03-20_1748.png

**Comment by Bezart** [comment]
Я бы предпочел показывать только один бвннер на главной. Пока можно webstorm

**Comment by iliakan** [comment]
Добавил баннер на главной.
