### ISSUE TITLE
Тесты: многострочный вопрос

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#359]
Текущая вёрстка тестов не учитывает многострочные вопросы.

Вот так, к примеру, выглядит код:
http://ilyakantor.ru/screen/2015-03-17_1728.png

А хорошо бы код был выше-правее, как-то так: http://ilyakantor.ru/screen/2015-03-17_1730.png

Как соберёшься заняться - запустим тесты у тебя.

**Comment by tyv** [comment]
@Bezart как быть когда строка выделается жирным которую выбрали? у нас вполне понятный селектор для этого, который зацепит любой контент внутри
может выделять другим способом?
```styl
    &__input:checked + &__input-text
        font-weight bold
```

**Comment by Bezart** [comment]
@tyv @iliakan предлагаю пойти более простым путем: http://take.ms/e2cn8

**Comment by iliakan** [comment]
То есть, первый элемент из блока подсвечиваем, так выходит?

**Comment by Bezart** [comment]
Я бы сделал более надежно, а то как-то хрупко звучит. Почему бы не сделать  dd/dt или что-то в таком духе, где dt будет вариантом ответа, а dd – описанием к нему. Тогда появится больше свободы и логика подсветки будет простой и понятной.

**Comment by iliakan** [comment]
@tyv 

Каждый вариант ответа будет содержать два поля: `title` и `description`. Строка ответа, которую нужно в `label`, будет `title`, а опциональный блок под ней `description`.

Sounds good?

**Comment by tyv** [comment]
да, ок

**Comment by tyv** [comment]
я поправлю верстку

**Comment by iliakan** [comment]
Вот так нормально, да?  
http://ilyakantor.ru/screen/2015-03-21_0103.png

**Comment by Bezart** [comment]
Хотелось бы выравнивание чекбоксов по строке сделать и немного подтянуть выше блок кода

**Comment by tyv** [comment]
> Хотелось бы выравнивание чекбоксов по строке сделать

браузеры сильно по разному рендерят чекбокс и когда его выносишь из контекста, хрен подровняешь, я улучшил немного, но в зависимости от браузера хотелось бы +/- px подогнать конечно, но мы этого делать не будем. (PR пришлю скоро)

**Comment by iliakan** [comment]
Сейчас вот тут как бы "слипаются" варианты (нет нижнего отступа) http://ilyakantor.ru/screen/2015-03-23_1145.png

Может сделать для кода нижний отступ или как-то более универсальное решить? (чтобы 1-строчные варианты не поломать)?

**Comment by Bezart** [comment]
почему бы у description просто не сделать margin-bottom: 8px? Тогда однострочные варианты не пострадают

**Comment by iliakan** [comment]
Да, отличное решение, сделал http://ilyakantor.ru/screen/2015-03-23_2310.png
