### ISSUE TITLE
Несколько правок

### ISSUE THREAD

**Issue by effect99gh** [iliakan/javascript-nodejs#363]
https://nightly.javascript.ru/datetime#бенчмаркинг
function walkIn(arr) {
  for (var key in arr) arr[i]++ // вероятно, здесь должно быть arr[key]++
}

Гораздо более надёжные результаты можно получить, весь пакет тестов прогнать много раз. // ".., ЕСЛИ весь пакет..", либо ".., весь пакет тестов прогнаВ.."
«проводить миробенчмаркинг» // ..миКро..

https://nightly.javascript.ru/typeof-duck-typing#полиморфизм
Пример полимофрной функции.. // ..моРФной..

https://nightly.javascript.ru/typeof-duck-typing#полиморфная-функция-formatdate
alert( formatDate(1234567890) ); // вероятно здесь 15.01.1970, а не 14.02.09

**Comment by iliakan** [comment]
Первое поправил, второе уже, третье - недостаточно внимательно прочитали условие.
