### ISSUE TITLE
Ошибка при проверке на undefined

### ISSUE THREAD

**Issue by sandovsky** [iliakan/javascript-nodejs#365]
В главе Псевдомассив аргументов «arguments» (https://nightly.javascript.ru/arguments-pseudoarray#аргументы-по-умолчанию-через) ошибка при проверке на undefined в следующем примере:

function showWarning(width, height, title, contents) {
  if (width !== undefined) width = 200;
  if (height !== undefined) height = 100;
  if (title !== undefined) title = "Предупреждение";

  //...
}
Нужно заменить !== на ===

**Comment by iliakan** [comment]
Fixed.
