### ISSUE TITLE
Шрифт ссылок первого уровня

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#366]
Глянь, пожалуйста, на шрифт ссылок внутри основных разделов https://nightly.javascript.ru/tutorial ?

Он точно ок такой?

**Comment by Bezart** [comment]
Да, точно такой. А в чем проблема?

**Comment by iliakan** [comment]
М, кажется не очень красиво. Возможно, из-за того, что этот шрифт резко выпадает из схемы.
У нас больше нигде нет такого.
С болдом есть, а вот такого просто в повышенном размере нет.

**Comment by Bezart** [comment]
ну ты сам его захотел сделать больше. Мне и 14 px нравился, он тогда не "выпадал"

**Comment by iliakan** [comment]
Да, 14px там как бы мелковат, это ж большие разделы.
