### ISSUE TITLE
Старая песочница - архив

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#367]
Старый раздел "песочница" http://learn.javascript.ru/play в новом движке отсутствует, но содержимое нужно оставить.

Для этого я даю возможность его скачать в виде zip-архивов.

Две страницы есть:
 1. https://nightly.javascript.ru/play/
 2. Если на конкретную ссылку зашёл старую, то http://ilyakantor.ru/screen/2015-03-20_1447.png

Как-то чуть покрасивше их оформить мб, но не сильно заморачиваясь?

**Comment by Bezart** [comment]
Просто выводи этот текст при помощи стандартных нотификаций (желтые)

**Comment by iliakan** [comment]
Вот так? 
http://ilyakantor.ru/screen/2015-03-20_1817.png

**Comment by Bezart** [comment]
Да, норм
