### ISSUE TITLE
Правки в Замыканиях

### ISSUE THREAD

**Issue by effect99gh** [iliakan/javascript-nodejs#368]
[Вот втором примере нужно запустить say();](https://nightly.javascript.ru/closures#вложенные-функции)

##### Тонкий момент
> // каждый вызов увеличивает счётчик и возвращает результат

[Тут](https://nightly.javascript.ru/closures#возврат-функции) код не совсем соответствует данному описанию. Можно было бы поменять местами "увеличивает счетчик" и "возвращает результат", но, возможно, лучше бы установить начальное значение ```currentCount = 0``` и возвращать ```++currentCount```.
Мне кажется, это правильней. Может, что-то упустил, могу ошибаться :)

А [здесь](https://nightly.javascript.ru/closures-usage#объект-счётчика-функция) Вы использовали тот же код, и получится, что после ```counter.reset()``` при запуске мы получим 0, а не 1. Можно в методе ```reset``` присваивать```currentCount = 1```, а можно сделать, как было описано выше. И в этом случае при запуске  ```counter()``` после использования метода ```counter.set(5)``` будет возвращаться 6, а не 5. И, мне кажется, так и должно быть, ведь ```counter()``` должна *увеличить* и вернуть.

**Comment by iliakan** [comment]
чуть поправил там и сям.
