### ISSUE TITLE
Заголовки у доп курсов - кликабельные?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#370]
Вот эти заголовки http://ilyakantor.ru/screen/2015-03-20_1713.png - по замыслу кликабельны аналогично статьям?

В дизайне про это ничего не было. Я бы предложил сделать кликабельными, с иконкой-анкором.

**Comment by Bezart** [comment]
Нет, по замыслу они не кликабельны и я бы не хотел их делать ссылками. Все внутренние пункты и так показаны на странице, поэтому не имеет смысла кидать туда пользователя.

**Comment by iliakan** [comment]
Может, сделать кликабельными их, почему нет-то?

**Comment by Bezart** [comment]
Тут вопрос стоит не в том, почему не сделать, а в том зачем их добавлять?
1. Мы не получаем никакой выгоды когда посылаем туда, так как это чисто навигационная страница, а пользователь может попасть на любую внутреннюю страницу с главной. То есть, мы просто усложняем навигацию без каких-либо причин
2. Это может породить ложные ожидания у пользователя, так как он будет подумать что список на главной не полный и он может получить больше информации, зайдя на страницу раздела, хотя это не так.
