### ISSUE TITLE
Карта сайта на отдельной странице

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#372]
Вот так - правильно? http://ilyakantor.ru/screen/2015-03-21_1316.png

Или нужно, чтобы верхний фильтр был той же ширины, что и карта, т.е больше отступы слева-спрева для него?

**Comment by iliakan** [comment]
http://ilyakantor.ru/screen/2015-03-21_1317.png

**Comment by Bezart** [comment]
Да, нужно по ширине выровнять.
