### ISSUE TITLE
Некорректно отображается верстка

### ISSUE THREAD

**Issue by Yorkina** [iliakan/javascript-nodejs#376]
https://nightly.javascript.ru/coordinates-document

Chrome версия 41.0.2272.89 (64-bit), Safari версия  8.0.4 (10600.4.10.7), Opera версия 27.0.1689.76, 
Firefox версия 35.0.1 - выглядит так, как на картинке ниже.
Firefox 24.6.0 - выглядит нормально.
Мак ось Yosemite 10.10.2
![2015-03-22 20 05 10](https://cloud.githubusercontent.com/assets/9257720/6770445/1465d5d2-d0d1-11e4-9768-14b520e81e7d.png)

**Comment by iliakan** [comment]
Странно, MacOS, последний Chrome/Firefox всё ок.

**Comment by skparallax** [comment]
Протестил страницу на MacOS в

* Chrome (Version 41.0.2272.101 (64-bit))
* Firefox (35.0.1)
* Safari (Version 7.1.3 (9537.85.12.18))
* Opera (28.0.1750.48)
* IE 9-11 :smile:
* и на Android 4.0.3 в Chrome

С картинками везде все нормально, кроме мобильника:

![Alt text](https://monosnap.com/file/jDsZuAz279Dl2VzhXQIIHASPgLXFRI.png)

плюс нашел баг #380

**Comment by Yorkina** [comment]
Монитор 13, Air. Может что-то нужно ?

**Comment by iliakan** [comment]
Yorkina: пока не удаётся воспроизвести. Попробуйте открыть без всех плагинов и расширений браузера?

**Comment by Yorkina** [comment]
Попробовала на Firefox и на Opera. Вид такой же.

**Comment by teodorovych** [comment]
Android 4.2.1
Первая картинка Firefox остальные встроеный браузер =-O
![screenshot_2015-03-30-03-34-09](https://cloud.githubusercontent.com/assets/11709520/6888712/0b6a22ee-d68f-11e4-9fc3-6577057f2c12.png)
![screenshot_2015-03-30-03-35-04](https://cloud.githubusercontent.com/assets/11709520/6888715/1e1eaedc-d68f-11e4-8875-ee9bfa25e60b.png)
![screenshot_2015-03-30-03-35-36](https://cloud.githubusercontent.com/assets/11709520/6888717/27e22d2c-d68f-11e4-9cb9-3eeb589551c0.png)
![screenshot_2015-03-30-03-35-47](https://cloud.githubusercontent.com/assets/11709520/6888720/366f255c-d68f-11e4-8704-8e4379fd0c6d.png)
![screenshot_2015-03-30-03-36-19](https://cloud.githubusercontent.com/assets/11709520/6888724/47b33088-d68f-11e4-8e30-08f5ab3aa416.png)

**Comment by teodorovych** [comment]
Во встроеном браузере, почему-то, все алерты срабатывают при загрузке страници. Это нормально?

**Comment by iliakan** [comment]
А попробуйте в хроме? Вообще Android Browser это старое г.

**Comment by teodorovych** [comment]
![screenshot_2015-03-30-12-41-16](https://cloud.githubusercontent.com/assets/11709520/6894012/76c83c9c-d6da-11e4-9f89-d7dd05681c02.png)
![screenshot_2015-03-30-12-41-31](https://cloud.githubusercontent.com/assets/11709520/6894019/7e08d2dc-d6da-11e4-8342-8e55dac2e655.png)
![screenshot_2015-03-30-12-41-38](https://cloud.githubusercontent.com/assets/11709520/6894023/8a44ed06-d6da-11e4-996f-be8fd2892f9b.png)
Все 3 в последнем Хроме

**Comment by iliakan** [comment]
По внешнему виду все нормально на скриншотах.

По алертам - они автоматом не должны срабатывать.

**Comment by teodorovych** [comment]
Win 7 64bit
Firefox 36.0.4 32bit - все в порядке
Google Chrome.1.0.2272.101 m (64-bit)
![prtsc](https://cloud.githubusercontent.com/assets/11709520/6917090/25579aa8-d7aa-11e4-8643-c2cfa7069fea.jpg)
Что посмотреть?

**Comment by teodorovych** [comment]
Может поможет
Firefox
![firefox](https://cloud.githubusercontent.com/assets/11709520/6917207/42537310-d7ab-11e4-8214-fdfc8b2607fb.jpg)
Chrome
![chrome](https://cloud.githubusercontent.com/assets/11709520/6917214/543193d2-d7ab-11e4-8fb5-71453c52761b.jpg)

**Comment by teodorovych** [comment]
При изменении шрифта на 15 текст в диве помещается в 2 строки, и все исправляется
![chrome_1](https://cloud.githubusercontent.com/assets/11709520/6917410/ee373594-d7ac-11e4-8bfa-b19869d1b456.jpg)

**Comment by iliakan** [comment]
Спасибо, исправил!

**Comment by teodorovych** [comment]
Пока не изменилось. Мож еще не перезалили?

**Comment by iliakan** [comment]
Да, только что перезалил.

**Comment by teodorovych** [comment]
Теперь Ок.
