### ISSUE TITLE
Возможно ошибка в уроке "Управление памятью в JavaScript"

### ISSUE THREAD

**Issue by r5m** [iliakan/javascript-nodejs#379]
На странице https://nightly.javascript.ru/memory-management

В строке "delete family.wife.husband;", мне кажется, должно быть "delete family.mother.husband", так как у объекта family нет свойства "wife".

![nightly_js_ru](https://cloud.githubusercontent.com/assets/3611851/6776081/5b23754a-d164-11e4-9c96-19f8b5d7083a.png)

**Comment by iliakan** [comment]
yep.
