### ISSUE TITLE
Страницы с уроками: горизонтальная прокрутка в Firefox

### ISSUE THREAD

**Issue by skparallax** [iliakan/javascript-nodejs#380]
Firefox (35.0.1) на MacOS

Страницы с уроками прокручиваются горизонтально

http://www.screencast.com/t/hRbm2Q7bi

Проверил во всех браузерах, только в Firefox такое

**Comment by tyv** [comment]
круто как :) https://twitter.com/yuritkachenko/status/580826210143473664 и https://twitter.com/yuritkachenko/status/580828101531320320
