### ISSUE TITLE
О сайте /Вёрстка/

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#381]
@tyv, второй вариант #247, который http://take.ms/OhQ2Z, сверстай, плиз.

Карта, видимо, будет Google Map.

**Comment by iliakan** [comment]
@tyv, фон у аватарок куда-то делся http://ilyakantor.ru/screen/2015-03-30_1530.png

**Comment by iliakan** [comment]
up, фон http://ilyakantor.ru/screen/2015-04-02_1603.png не соответствует дизайну, это специально?

**Comment by tyv** [comment]
я там фильтр заюзал, надо поменьше яркости сделать, сделаю

**Comment by iliakan** [comment]
Just FYI последние PR это не исправили.

**Comment by tyv** [comment]
я поправил яркость, не идеально, но похоже, по другому просто картинки прийдется экспортировать, так как в css фильтров не так много как в sketch

**Comment by iliakan** [comment]
Я думал, что ты экспортируешь их в обычные jpg-шки и добавишь кружок вокруг при помощи CSS.

Ты как-то иначе сделал?
