### ISSUE TITLE
Дизайн: купить учебник, страница

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#382]
Изначально планировалось продавать учебник в виде двух книг: JS и DOM: по 450 руб в отдельности, вместе 650.

Каждая часть учебника имеет >500 страниц, состоит из одного файла, так что это разделение "на тома" вполне естественно.

Сейчас, когда чел жмёт на "купить учебник" -- куда он переходит? 

Видимо, на страницу покупки сразу, но тогда у нас остаётся только 1 вариант продажи, весь учебник целиком?

**Comment by Bezart** [comment]
Думаю, нужен landing страница для учебника, я даже ее рисовать когда-то начинал. Давай для первого релиза сделаем просто один вариант и будем кидать на страницу покупки.

**Comment by iliakan** [comment]
Я для первого релиза уже сделал систему заказов, предусматривающую несколько учебников. 

Консервировать её не хотелось бы.

**Comment by iliakan** [comment]
Если просто по стоимости - то тоже было бы интересно посмотреть, сколько посетителей купят первую часть, вторую или вместе.

Если их вместе продавать сразу, без опций по отдельности - надо и дешевле делать (зачем?), т.к. люди не понимают ценности если не видят раздельных вариантов.

**Comment by Bezart** [comment]
Добавил http://take.ms/FKBuR

**Comment by iliakan** [comment]
@tyv, как бы нам этот выбор сверстать удобнее, чтоб целую страницу не перевёрстывать?

**Comment by iliakan** [comment]
Прямо в боевых шаблонах сделать, наверно, проще будет, я загружу фикстуры для просмотра.

**Comment by iliakan** [comment]
Покажу по скайп где что, когда соберёшься, там небольшая правка совсем.
