### ISSUE TITLE
Опечатки и прочие мелочи в разделах Числа и Строки.

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#383]
1 ) Опечатка в разделе "Преобразование объектов: toString и valueOf", [Две стадии преобразования](https://nightly.javascript.ru/object-conversion#%D0%B4%D0%B2%D0%B5-%D1%81%D1%82%D0%B0%D0%B4%D0%B8%D0%B8-%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F):

>  Далее, вполне возможно, Если необходимо, что полученный из объекта примитив будет преобразован дальше, уже по правилам для примитивов.

* Еще один момент того же параграфа показался странным, может я чего-то не допонял:

> Исключение: Date
Объект Date, по историческим причинам, является исключением.
Бинарный оператор плюс + обычно использует числовое преобразование, но в случае с Date — строковое:

На мой взгляд, бинарный плюс чаще производит строковое преобразование (для объектов, для чисел при сложении со строками, если, конечно, не переопределять valueOf для строк и объектов), а числовые преобразования встречаются реже(булевых значений). А так как new Date - объект, то у меня не вызывает удивления, что преобразование строковое.
Вероятно, лучше написать, что исключение состоит в том, как проходят строковое и числовое преобразования для new Datу. При том, что это объект, мы получаем не object Object и NaN, а строку даты и число в мс. Или что-то еще, я могу только гадать. Но предложение "Бинарный оператор плюс + обычно использует числовое преобразование, но в случае с Date — строковое" - однозначно мне ничего не объясняет.

************

2 )  Опечатка? Раздел "Создание объектов через «new»", задачка [Создать Calculator при помощи конструктора](https://nightly.javascript.ru/task/calculator-constructor):

>  Напишите функцию-конструктор Calculator, которая создает объект с двумя методами:

    Метод read() запрашивает два значения при помощи prompt и запоминает их в свойствах объекта.
    Метод sum() возвращает сумму запомненных свойств.
    Метод mul() возвращает произведение запомненных свойств.

Очень похоже, что метода все-таки три.

******************

3 )  Неоднозначное место в разделе "Дескрипторы, геттеры и сеттеры свойств", [Да здравствуют get/set!](https://nightly.javascript.ru/descriptors-getters-setters#%D0%B4%D0%B0-%D0%B7%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%82-get-set):

> Добавление get-функции age позволяет обойти проблему легко и непринуждённо:
...
  // age будет высчитывать возраст по birthday
  Object.defineProperty(this, "age", {
    get: function() {
      var todayYear = new Date().getFullYear();
      return todayYear - this.birthday.getFullYear();
    }
  });
...
 
Пример не особо показателен. Если нужна функция, то сработает и запись на строчку короче:

>

      this.age = function() {
          var todayYear = new Date().getFullYear();
          return todayYear - birthday.getFullYear();
       }();

Это работает, но если нужно еще более легко и непринужденно, то можно и без функции:

> this.age = new Date().getFullYear() - birthday.getFullYear();

Другое дело, что работает это только для инициализации и не учитывает возможности изменения параметров объекта, влияющих на age. Т.е. лавочка накроется, если потом переопределить у объекта свойство birthday. 

Мне кажется, лучше отметить, что легко и непринужденно с помощью Object.defineProperty можно установить фунцию-геттер с сохранением контекста this и учитывающую изменения остальных свойств объекта. 

**********************

4 ) Не имеет отношения к учебнику. Ошибка в видеоматериале  33_global_object.exe.
На 11:50 пример про определение наличия переменной.

> if (jQuery) {
  alert ("no jQuery")
}

Даже если отвлечься от случая ошибки при отсутствии переменной, при ее наличии функция нас будет дезинформировать.

**Comment by iliakan** [comment]
Спасибо, поправил всё кроме 4.

Закрываю с меткой maybe later из-за 4.
