### ISSUE TITLE
Подписка/отписка для рассылки

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#384]
https://github.com/iliakan/javascript-nodejs/issues/308#issuecomment-84048745

**Comment by Bezart** [comment]
Я бы все-таки кидал пользователя на главную с сообщением вверху. Это поможет оставить пользователя на сайте (или вернуть позже). Пустую страницу с сообщением просто закрывают и все.

**Comment by iliakan** [comment]
Максимум что может на этой странице подтверждения или удаления подписки - это sitetoolbar. И ясное и понятное описание произошедшего. Больше ничего. 

Могу sitetoolbar + success notify попробовать.

**Comment by Bezart** [comment]
Не совсем понял камент, что такое sitetoolbar? Я говорил о чем-то таком: http://take.ms/yyUtE

**Comment by iliakan** [comment]
sitetoolbar это верхняя навигация.

Когда чел подписывается на уведомление, он не уходит со страницы. Ему на почту ссыль, и по ней он открывает мини-страницу, которую тут же закрывает (и у него остаётся старая страница, в которой он продолжает ходить по сайту).

**Comment by Bezart** [comment]
А если чел не идет сразу на почту и увидит письмо когда уже закроет окно?

**Comment by iliakan** [comment]
Это нормальная ситуация, стандартный user experience.

**Comment by iliakan** [comment]
Подписка-отписка всегда так работает, насколько я представляю :)

**Comment by iliakan** [comment]
У нас подписка будет правильная, со специальным тегом для быстрой отписки и проверенная на спам, не то что сейчас.

**Comment by Bezart** [comment]
Я не понимаю как мое предложение противоречит нормальной подписке

**Comment by Bezart** [comment]
В общем, тогда делай стандартным меседжем. Не вижу смысла что-то придумывать здесь с точки зрения дизайна.
