### ISSUE TITLE
Тесты: сохранение результатов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#389]
При нажатии на Сохранить результаты в профиле - как думаешь, что делать?
1) AJAX-кнопка, после сохранения выводит модальное окно, предлагая пройти ещё тест.
2) AJAX-кнопка, после сохранения notification
3) Редирект в профиль.
4) Промежуточная страница, затем редирект к тестам

Мне нравится идея сделать кнопку AJAX, поскольку позволяет человеку почитать страницу результатов. 

Вот здесь кнопка имеется в виду: http://awesomescreenshot.com/0bb4pv0c33

**Comment by Bezart** [comment]
Можно показывать стандартный notification (вариант 2) и в нем ссылку на профиль давать, например:

*Этот результат успешно добавлен к вам в [профиль](http://nightly.javascript.ru/profile)*

Если пользователь захочет, он перейдет туда, если нет — проигнерит или закроет нотификейшн

**Comment by iliakan** [comment]
Готово.
