### ISSUE TITLE
Миграция статей с javascript.ru

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#393]
Тема:
На старом javascript.ru много устаревших статей. Всё содержимое мигрировало в учебник. Как бы сделать, чтобы люди читали новые статьи? 

Сделать во всех старых статьях ссылки на новые?

Голосом обсудить подробнее можно.

**Comment by Bezart** [comment]
Договорились о чем-то таком: http://take.ms/nPVsV

**Comment by iliakan** [comment]
Сделано. В таблицу content_book добавилось поле book_newer.
