### ISSUE TITLE
Небольшие поправки в разделы "Функции-обёртки, декораторы", "Типы данных: [[Class]], instanceof и утки" и  "Массивы: методы".

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#394]
Вне конкурса:
Тех. проблемы в разделе [setTimeout и setInterval](https://nightly.javascript.ru/settimeout-setinterval):

* В параграфе [Рекурсивный setTimeout](https://nightly.javascript.ru/settimeout-setinterval#%D1%80%D0%B5%D0%BA%D1%83%D1%80%D1%81%D0%B8%D0%B2%D0%BD%D1%8B%D0%B9-settimeout) "картинки не грузяцца".

> Нет такого файла: setinterval-interval.svg [/js/javascript-nodejs/source/public/article/settimeout-setinterval/setinterval-interval.svg]
Нет такого файла: settimeout-interval.svg [/js/javascript-nodejs/source/public/article/settimeout-setinterval/settimeout-interval.svg]

* Фрейм в параграфе [Минимальная задержка таймера](https://nightly.javascript.ru/settimeout-setinterval#%D0%BC%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D1%82%D0%B0%D0%B9%D0%BC%D0%B5%D1%80%D0%B0) выдает 404.

**********
Далее последствия очередного приступа перфекционизма - в принципе, на все пункты можно забить.
**********
1 )  Раздел "Функции-обёртки, декораторы", [Декоратор для проверки типа](https://nightly.javascript.ru/decorators#%D0%B4%D0%B5%D0%BA%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8-%D1%82%D0%B8%D0%BF%D0%B0):

> Функция «как-то» отработала, но в реальной жизни такой вызов, скорее всего, будет следствием программной ошибки. 

Звучит интригующе, т.к. что за ошибка - не уточняется. Вероятно, подразумевается, что следствием ошибки отсутствия наличия проверки на тип. Но возможно и другое трактование - все-таки вызов функции будет не следствием, а причиной программной ошибки.

*************

2 )  Раздел "Типы данных: [[Class]], instanceof и утки", [Секретное свойство [[Class]]](https://nightly.javascript.ru/class-instanceof#%D1%81%D0%B5%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D0%BE%D0%B5-%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE-class):

>  Вызов {}.toString в консоли может выдать ошибку 

В консоли-то ладно, ошибка ведь еще будет, если написать это и в так сказать "корне" кода (в смысле, без вложенности в другие конструкции). На занятиях об этом упоминалось, а в учебнике только про консоль. 

P.S. Сейчас прочитал Раздел [Запуск кода из строки: eval](https://nightly.javascript.ru/eval), там об этом говорится.

3 ) Раздел "Массивы: методы", [Метод slice](https://nightly.javascript.ru/array-methods#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-slice):

> Если вообще не указать аргументов — скопируется весь массив: 

Желательно упомянуть, что это не глубокое копирование.

* В том же разделе можно упомянуть, что concat тоже может копировать(тоже не глубоко). А можно и не упоминать - ведь он на символ длиннее и лишняя путаница.

***********

4 )  Видео  "43_object_conversion.exe"  3:05-3:20 и 3:45-4:00. Идет упоминание о том, что valueOf у массива нет. Вообще-то он вроде как есть, если судить по консоли. Другое дело, что сам он ничего особенного не делает, а идет перенаправление на toString.

**Comment by iliakan** [comment]
Тех проблема поправлена
1) Уточнения добавлены.
2) Там вроде очевидно, по тексту.
3) Во избежании запутывания - не уточняю.
4) Да, он вообще везде есть, но возвращает сам объект по стандарту, а значит не подходит (не используется).
