### ISSUE TITLE
Jetbrains.* для участников курса

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#396]
Страница со скидками для участников (детали на звонке).

**Comment by iliakan** [comment]
Страница запроса лицензии вот такая - ок?
http://ilyakantor.ru/screen/2015-03-27_1951.png

Это чтобы участники курса могли ввести свои данные - и автоматом запрос на скидку отправляется на продукт (сейчас отключено).

В действии https://nightly.javascript.ru/jb

**Comment by Bezart** [comment]
Страшненькая получилась :) давай лучше так: http://take.ms/WTRGL
