### ISSUE TITLE
Приоритеты операторов

### ISSUE THREAD

**Issue by r5m** [iliakan/javascript-nodejs#397]
На странице https://nightly.javascript.ru/operators
в таблице с приоритетами оператор присвоения имеет самый высокий приоритет (наименьшее число в таблице - 3).

Цитата: "Она [таблица] содержит как уже пройденные операторы, так и те, которые мы еще не проходили. В ней каждому оператору задан числовой приоритет. Тот, у кого число меньше — выполнится раньше. "

В то же самое время, в Javascript у присвоения - один из самых низких приоритетов (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence)

Возможно ошибка в уроке?

**Comment by iliakan** [comment]
Не понял, в чём ошибка, где конкретно противоречия со ссылкой?

**Comment by iliakan** [comment]
А, видимо во фразе опечатка, да? У кого больше - тот раньше, поправлю.

**Comment by iliakan** [comment]
Обновил данные.

**Comment by r5m** [comment]
Если я правильно понял, то у вас таблица построена по принципу "Чем меньше число, которое обозначает приоритет, тем приоритет выше".

Например, цитата:
"Так как «унарный плюс» имеет приоритет 4, выше, чем 6 у обычного «сложения», то в выражении +apples + +oranges сначала сработали плюсы у apples и oranges, а затем уже обычное сложение"

То есть, приоритет 4 выше, чем приоритет 6.

А у присваивания приоритет 3. То есть, получается, что присваивание имеет более высокй приоритет, чем остальные операторы.

Но, это же не так?


То есть в выражении a = 2 * 2 +1, согласно таблице (и правилу "Чем меньше число, которое обозначает приоритет, тем приоритет выше"), сначала выполнится присваивание (приоритет 3), затем умножение (приоритет 5) и затем сложение (приоритет 6).

**Comment by r5m** [comment]
А если просто исправить правило определения приоритетов на "у кого больше - тот раньше", то в выражении a = 2 * 2 +1 сначала выполнится сложение, затем умножение и потом присваивание, что тоже неверно.

**Comment by iliakan** [comment]
Был апдейт таблицы. Проверьте сейчас.

**Comment by r5m** [comment]
Мне кажется, что для присваивания неправильно назначено число, определяющее приоритет?

**Comment by r5m** [comment]
Все верно.
