### ISSUE TITLE
О сайте - карта

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#410]
На карте из дизайна отмечено не всё.
Так и оставлять масштаб? Или сделать уменьшение, чтобы всё влезало? 

Если уменьшение, то другая проблема - не все города видны.

Карту откуда брал - Google maps?

**Comment by Bezart** [comment]
Да, это гугловые. Можно использовать http://leafletjs.com/ для слоя данных. Если не все влезет — не беда.

**Comment by iliakan** [comment]
Не нашёл, как города зафорсить.
Круг резким сделать тоже не знаю как.

Шо делаем? Увеличиваем зум или кто-то из твоих знакомых может подсказать?

**Comment by Bezart** [comment]
я поговорил с ребятами, вроде бы стандартного метода повлиять на гугл таким образом нет. Просто сделай + 1 зум

**Comment by Bezart** [comment]
Можно использовать библиотеки, тогда можно.

**Comment by iliakan** [comment]
leaflet looks good so far.
