### ISSUE TITLE
Сделать соглашение о сайте

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#423]
@Bezart добавил в Login/Register и Footer соглашения.

**Comment by iliakan** [comment]
Форма регистрация новая не вмещается по высоте (1280 x 800): http://ilyakantor.ru/screen/2015-04-04_1244.png

**Comment by iliakan** [comment]
Видишь, сверху вылезает?

**Comment by Bezart** [comment]
можно немного уменьшить вертикальные марджины у новой текстовки, а так все ок

**Comment by iliakan** [comment]
уменьшил до `15px`.
