### ISSUE TITLE
Sticky поиск на мобильном

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#428]
Sticky поиск должен быть аналогично тому как в хедере, сейчас показывается неадаптированный вариант (вверху):

![img_5751](https://cloud.githubusercontent.com/assets/349336/6992618/4a4ab158-dae1-11e4-918e-0c2fcca940fb.PNG)

**Comment by tyv** [comment]
он же там совсем по другому

**Comment by tyv** [comment]
чуток развалено, но я как раз с ним сейчас работаю https://yadi.sk/i/r_lU_MQrfkfYM

**Comment by iliakan** [comment]
на мобиле sticky пусть вообще не будет в поиске.

**Comment by iliakan** [comment]
в отличие от десктопа.
