### ISSUE TITLE
Форма логина на мобильных

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#430]
Дизайн формы для мобильных: http://ilyakantor.ru/screen/2015-04-04_1609.png
В Sketch - на странице Login / Register.

Это по-прежнему попап, но занимает всю страницу и вместо закрытия - кнопочка "Отмена".

**Comment by iliakan** [comment]
P.S. Причина - текущая форма неюзабельна на iphone 5, аналогичных по размеру и меньших экранах.

**Comment by iliakan** [comment]
Отмена появилась на десктопе:
http://ilyakantor.ru/screen/2015-04-05_1705.png

**Comment by iliakan** [comment]
На мобильном почему-то не вижу кнопку (эмулятор) http://ilyakantor.ru/screen/2015-04-05_1706.png

**Comment by tyv** [comment]
старая версия ios, в новой ок
