### ISSUE TITLE
Обозначить бету

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#433]
Хорошо бы как-то обозначить, что новый релиз - это бета, чтобы не очень пугались возможных недоделок, багов и глюков :)

**Comment by Bezart** [comment]
http://take.ms/MGlOy

**Comment by iliakan** [comment]
А мы как-то предлагаем в новом учебнике перейти на старый? Или просто пишем "бета"? Обычно предлагают какое-то время.

На старом (он будет на другом домене) - перейти на новый предлагаем по идее, да? Как?

**Comment by iliakan** [comment]
В принципе, явных причин нет для этого. Закрою пожалуй.
