### ISSUE TITLE
О сайте: люди

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#435]
Какую-нибудь короткую ссылочку на github/.../contributors.md размести плиз в разделе "Люди".
Может быть, "а также" её назвать?

Там будут те, кто участвовал в разработке сайта.

P.S. В изначальном дизайне там слишком длинный полный линк.

**Comment by Bezart** [comment]
Как тебе http://take.ms/3eT7H ?

**Comment by iliakan** [comment]
@Bezart надо посмотреть на странице целиком. Не будет ли ссылка слишком яркой, там же всё чёрно-белое.

**Comment by Bezart** [comment]
Думаю, норм http://take.ms/xegLx
