### ISSUE TITLE
Неверная конвертация TimeStamp комментария в анонсе и в полном комментарии. Месяцы вместо дней.

### ISSUE THREAD

**Issue by baranovRP** [iliakan/javascript-nodejs#436]
TimeStamp анонсов комментариев отображается в месяцах, тогда как в полной версии комметария TimeStamp это тоже самое число но это дни. (для доп. инф. см скриншот)
![incorrecttimestamp_2015-04-04_21h24_09](https://cloud.githubusercontent.com/assets/2158131/6994261/c2d343ca-db12-11e4-9202-b5f3ecf44e79.png)

**Comment by iliakan** [comment]
Зарепортил на disqus.

**Comment by iliakan** [comment]
Отрубил эту панельку пока.

**Comment by baranovRP** [comment]
Давность комментариев отображается как и ожидается(месяцы и дни), правда комментарий от electrovlad'a пропал (в рамочке на левом скриншоте), он отсутсвует в текущих отображаемых комментах.
