### ISSUE TITLE
Не работает редирект с анонсов комментариев на страницу с полным комментарием

### ISSUE THREAD

**Issue by baranovRP** [iliakan/javascript-nodejs#437]
Не работает редирект с анонсов комментариев на страницу с полным комментарием
(для доп. инф. см скриншот)
![redirectdoesntwork](https://cloud.githubusercontent.com/assets/2158131/6994285/ef70e59e-db13-11e4-89e9-7425aabdc540.png)

**Comment by iliakan** [comment]
Не очень понятно, почему это.
javascript.in - это локальный домен для разработки у себя на машине, как он туда пробрался...

На продакшн будут не эти комментарии, а текущие с learn'а.

**Comment by iliakan** [comment]
Есть мнение, что должно стать ок. Стало?

**Comment by baranovRP** [comment]
Похоже на то что перепутаны комменты под этим issue  и (isuue #436)[https://github.com/iliakan/javascript-nodejs/issues/436#issuecomment-89655877]
А панелька с анонсами отключена, да.
![2015-04-10_08h05_32](https://cloud.githubusercontent.com/assets/2158131/7082739/d43ec54a-df58-11e4-92bc-d7d0417da0a0.png)

**Comment by iliakan** [comment]
Hope it's fixed.
