### ISSUE TITLE
Дизайн: responsive iphone 5 ok?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#439]
Вот скрин: http://ilyakantor.ru/screen/2015-04-05_1039.png

Может, лого левее и чуть выровнять по вертикали?

**Comment by Bezart** [comment]
да, лого либо левее, либо по центру, а то сейчас позиционирование загадочное немного. Касательно кнопки "Найти", мы по-моему решили скрывать блок?

**Comment by iliakan** [comment]
Да, найти там не будет, на момент скрина он был ещё.

@tyv, лого подвинь, пожалуйста, левее.

Там еще Купить учебник на него налезает, если узко, кстати. Так и задумано?
