### ISSUE TITLE
Правки по лого

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#440]
Переслал новый лого дизайнеру знакомому, он некоторые правки предложил (незначительные), посмотри плиз: https://www.dropbox.com/s/n6xtwxjgndn9nkl/javascript.ru-logo2-fixed-%28gb%29.zip?dl=0

**Comment by Bezart** [comment]
Да, норм правки. Там заливка осталась на одном слое, я поправлю и обновлю в исходнике.

**Comment by iliakan** [comment]
Ок, тогда жду новый окончательный лого, буду прикручивать заново к нему анимацию.

**Comment by Bezart** [comment]
Обновил в исходнике. Создал отдельную страницу Logo

**Comment by Bezart** [comment]
Фавиконы тоже обновились

**Comment by iliakan** [comment]
Плиз у беты добавь 10 пикселей слева, вот так: 
http://ilyakantor.ru/screen/2015-04-07_1344.png

Это нужно, чтобы при анимации flash было куда лететь.

**Comment by iliakan** [comment]
Favicons в дропбоксе у меня от 4 апреля,  последние проверь плиз.

```
~/Dropbox/JSR/Production/Favicons
iliakan> ls -lat
total 48
drwxr-xr-x@ 6 iliakan  staff   204  4 апр 14:31 .
drwxr-xr-x@ 5 iliakan  staff   170  4 апр 14:29 ..
-rw-r--r--@ 1 iliakan  staff  5662  4 апр 14:29 apple-touch-icon-precomposed.png
-rw-r--r--@ 1 iliakan  staff  1310  4 апр 14:29 favicon.ico
-rw-r--r--@ 1 iliakan  staff  1310  4 апр 14:29 favicon.png
-rw-r--r--@ 1 iliakan  staff  5187  4 апр 14:29 tileicon.png
```

**Comment by iliakan** [comment]
Взял из скетча, из дропбокса наверно удалить это?

**Comment by Bezart** [comment]
Сделал в исходнике
