### ISSUE TITLE
Картинки на /about

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#444]
Картинки сделать чёрно-белыми? Ещё какое-то преобразование над ними нужно?

Глянь плиз /about, как @tyv сейчас сделал.

**Comment by Bezart** [comment]
На большом экране числа слишком большие:
http://take.ms/acMsR

Это фаерфокс, там grayscale фильтры не работают, так что может отключить их вообще? По-моему цветные смотрятся тоже нормально.

А можно ссылки повесить на имя? http://bezart.me/  это моя если что

**Comment by tyv** [comment]
картинки я экспортну

**Comment by iliakan** [comment]
Ссылки - на именах, при наведении подчёркивание появляется, @Bezart? уточни плиз.

**Comment by Bezart** [comment]
Не, у нас ссылки и так не подчеркнуты. Стандартное поведение можно прикрутить (цвет+hover)

**Comment by iliakan** [comment]
То есть, как эти ссылки показать?

**Comment by Bezart** [comment]
http://take.ms/N2r47

**Comment by tyv** [comment]
насчет картинок, их по уму надо минимум в 2 раза больше чем они есть, чтобы на ретине были не размыты
а в макетах они 64*64

**Comment by iliakan** [comment]
Да, правда. Я это учёл, в `/js/javascript-nodejs/assets/about/` они как раз в большом разрешении. Я б взял запас и в 3-4 раза.

Вон эпл скоро выпустит мак с 8к экраном, не перевёрстывать же :)

**Comment by tyv** [comment]
да но они то без обработки там )

**Comment by tyv** [comment]
@Bezart сделаешь картинки 128x128 квадратные?

**Comment by iliakan** [comment]
@tyv обработка - в плане фотошоп? :) Ну там взгляд более пронзительным сделать, волосы более шелковистыми?

**Comment by iliakan** [comment]
@Bezart глянь about - как щас - гут?
