### ISSUE TITLE
Ссылки на комментарии никуда не ведут.

### ISSUE THREAD

**Issue by electrovladyslav** [iliakan/javascript-nodejs#448]
В комментариях к урокам внизу страницы, в блоке "ТАКЖЕ НА NIGHTLY.JAVASCRIPT.RU", по клику на любом комментарии, Дискус делает редирект на http://javascript.in/, а такого сайта нет.

**Comment by iliakan** [comment]
Комментарии пока не должны нормально работать. После релиза будут.
