### ISSUE TITLE
Глюки в разделах "Дерево DOM" и "Поиск: getElement* и querySelector* и не только", плюс еще по мелочи..

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#450]
1 )  Глюк в разделе "Дерево DOM", параграф [Пример DOM](https://learn.javascript.ru/dom-nodes#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-dom) .

При нажатиях на кликабельные картинки почему-то реагирует и левый сайдбар.
************
2 )  Глючок в разделе "Поиск: getElement* и querySelector* и не только", задача [Поиск элементов](https://learn.javascript.ru/searching-elements-dom#%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2) :

> Используйте для этого консоль браузера, открыв страницу table.html в отдельном окне.

Контекстное меню при нажатии на ссылку правой кнопкой мыши работает, как клик левой, ссылка открывается в текущей вкладке.

Да и вообще, пора избавиться от неразберихи с открытием ссылок на песочницы, сделать их как в примерах из основного текста - открывающимися в новой вкладке. А то в задачах - как придется - это напрягает. 

*************
3 ) Раздел "Навигация по DOM-элементам", [Навигация только по элементам](https://learn.javascript.ru/traversing-dom#%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8F-%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE-%D0%BF%D0%BE-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BC):

> elem.firstElementChild === elem.children[0]
elem.lastElementChild === body.children[body.children.length - 1]

Вторая строчка выглядит крайне подозрительно в плане body.
*********
4 ) 
  а ) Мелочь в разделе "Навигация по DOM-элементам", [Особые ссылки для таблиц](https://learn.javascript.ru/traversing-dom#dom-navigation-tables):

>      table.rows — список строк TR таблицы.
        table.caption/tHead/tFoot — ссылки на элементы таблицы CAPTION, THEAD, TFOOT.
        table.tBodies — список элементов таблицы TBODY, по спецификации их может быть несколько.

Слово список в примере выше(и далее там по тексту) наталкивает на мысли о строках, заголовках и т.д. Но не о псевдомассивах. Лучше сразу приучать к слову коллекция, тем более определение было дано выше. Причем в разделе "Поиск: getElement* и querySelector* и не только" список тоже упоминается, но только для [getElementsByTagName](https://learn.javascript.ru/searching-elements-dom#getelementsbytagname), для остальных методов упоминается коллекция. 

Ну разве что, кроме задачки про дерево, где просят вывести список.  

 б ) Кстати, о птичках. Постановка задачи [Дерево](https://learn.javascript.ru/searching-elements-dom#%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE)  как-то хромает (хотя можно интерпретировать, как "оставить простор для творчества"). Желательно уточнить, делать как демо (т.е. вывод в html, но тогда нужно подсказать про запись в тестовые узлы - nodeValue[или data]), либо указать, чтоб выводили через алерт или консоль. Но тогда тоже нужны подсказки про data и trim(которой, кстати, нет в справочнике).

**Comment by iliakan** [comment]
1. Как реагирует сайдбар? Браузер? Не вижу что-то.
2. Ссылки из текста открываются в том же окне. А что напрягает?
3. Спасибо, поправил.
4. Да, терминология должна быть единая, поправил. К дереву добавил пояснений.

**Comment by discodanser** [comment]
1) Почему-то только в FF глючит(открывает/закрывает).
2) Ну там даже специально написано - откройте в отдельном окне. В принципе, можно открывать где угодно, но задачки однозначно лучше открывать в новой вкладке, особенно если учесть, что планкер часто тормозит. Т.е. на старой вкладке остается теория, на другой - задача. В примерах основного текста так и сделано - и это правильно.
P. S. Обнаружил, что этот глюк с правой кнопкой опять в FF. Дискриминация по браузерному признаку!

**Comment by iliakan** [comment]
sidebar в FF поправил. Песочница сейчас тоже должна в новом окне везде открываться, проверьте, пожалуйста.

А что там с правой кнопкой, я так и не понял?

**Comment by discodanser** [comment]
Анимация чуть похуже, чем в хроме, но сайдбар уже не вылезает. 

Насчет правой кнопки мыши  - не получается с ее помощью вызвать контекстное меню браузера (в FF). Она срабатывает, как левая.

**Comment by iliakan** [comment]
Клик на любом месте страницы?

**Comment by discodanser** [comment]
Сорри, забыл написать - на ссылке table.html.
