### ISSUE TITLE
Логотип на мобильной версии

### ISSUE THREAD

**Issue by skparallax** [iliakan/javascript-nodejs#451]
Уменьшенная версия логотипа на мобильной версии выглядит слишком прижатой к левому краю:

![Alt text](https://monosnap.com/file/P70ruv1fulFVxklu5K6x4FJPXW7Zsr.png)

А при открытом меню и вовсе:

![Alt text](https://monosnap.com/file/24AXwi1cKwb6cTd2OMfXVWjoKwcx6b.png)

Может по центру и чуть ниже?

![Alt text](https://monosnap.com/file/oI6Dh3q0PvnNKA5RGmVctEUEYKgnSd.png)

![Alt text](https://monosnap.com/file/omQfpwYGn604QtyI96HqB9pHinRsZ8.png)

**Comment by tyv** [comment]
у меня на ios симуляторе норм
и еще в хроме тоже норм, может есть способ это увидеть на макбуке как-то?
