### ISSUE TITLE
SVG-иллюстрации и Linux

### ISSUE THREAD

**Issue by r5m** [iliakan/javascript-nodejs#463]
На странице https://learn.javascript.ru/traversing-dom иллюстрации в Ubuntu 15.04 выглядят вот так. Похожая ситуация в Elementary OS.

**Firefox 37:**
![screenshot from 2015-04-12 13 05 57](https://cloud.githubusercontent.com/assets/3611851/7104708/ed768d44-e10c-11e4-9964-1be2edf6a744.png)

**Chromium 41:**
![screenshot from 2015-04-12 13 06 37](https://cloud.githubusercontent.com/assets/3611851/7104707/ed751b1c-e10c-11e4-852a-3493b5c54b86.png)

**Comment by iliakan** [comment]
Возможно, что-то с SVG-рендерером под Lin?

**Comment by r5m** [comment]
Возможно, из-за используемых шрифтов.
В SVG документе прописан *Consolas*, если его переопределить:

```html
<style>
       text {
         font-family: monospace!important;         
       }
</style>
```
то получается уже читабельно
![svg-dom-links](https://cloud.githubusercontent.com/assets/3611851/7180748/082d8d32-e45e-11e4-9b9b-d965d88dfd60.png)

**Comment by iliakan** [comment]
Правильно понимаю, что у вас нет Consolas?

**Comment by r5m** [comment]
Да.

**Comment by iliakan** [comment]
@tyv, добавь пожалуйста Consolas в стили. Там лицензия позволяет нам его у себя захостить или ссылку дать куда-нибудь?

**Comment by tyv** [comment]
так может есть смысл для svg дописать
font-family: Consolas, monospace ?

**Comment by iliakan** [comment]
@tyv, видишь скриншоты - там monospace не очень? 

Кроме того, SVG генерируются из Sketch, это проблематично.

**Comment by tyv** [comment]
насколько я понял лицензия этого не позволяет, кажется его отдельно надо/можно купить или только в поставке с ms софтом

**Comment by tyv** [comment]
http://www.linotype.com/423208/ConsolasRegular-product.html

16.04.2015, 17:14, "Ilya Kantor" <notifications@github.com>:

**Comment by tyv** [comment]
http://www.linotype.com/423208/ConsolasRegular-product.html

**Comment by FFxSquall** [comment]
Вроде как позволяет https://www.microsoft.com/typography/fonts/family.aspx?FID=300
Пункт License Microsoft fonts for use with CSS @font-face rule in websites.

**Comment by FFxSquall** [comment]
Прошу прощения, не заметил, что там ограничения по количеству посещений сайта в бесплатном плане =)

**Comment by iliakan** [comment]
Вижу опцию за 8eur/месяц http://www.fonts.com/web-fonts/plans-and-pricing, но может как-то иначе можно решить проблему?

**Comment by iliakan** [comment]
Может, какой-то близкий шрифт поставить в woff, чтобы размеры не ломались.

**Comment by iliakan** [comment]
Или дешевле/бесплатно поиметь этот шрифт ;)

**Comment by iliakan** [comment]
Спрошу своего MVP Lead, может что-нибудь организует.

**Comment by tyv** [comment]
есть похожие шрифты — много

**Comment by tyv** [comment]
@r5m а ты style прямо в svg писал?

**Comment by r5m** [comment]
Да, внутри тега svg

**Comment by tyv** [comment]
можешь посмотреть
  1. не исправилось ли тут http://yuri.javascript.ru/traversing-dom (но вероятно нет)
  2. загружается ли вообще ```consolas-webfont.woff``` можно пофильтровать запросы в firebug

**Comment by tyv** [comment]
согласно этому http://stackoverflow.com/questions/20577316/svg-font-face-works-in-svg-but-not-when-included-in-a-page
самый правильный пусть во всех картинка заменить шрифт на кривые в редакторе

**Comment by r5m** [comment]
Картинка осталась без изменений, а ```consolas-webfont.woff``` подгружается.

**Comment by tyv** [comment]
вообщем картинки это standalone объекты и ничо тут не попишешь, если есть шрифт в системе, то ок, если нет — то все плохо 
надо менять картинки.

**Comment by r5m** [comment]
Если подключить шрифт внутри SVG через *data uri*, а потом SVG-документ встроить в HTML-страницу, то шрифт отображается корректно.

**Comment by iliakan** [comment]
Как бы автоматом шрифт в кривые перевести?

**Comment by tyv** [comment]
не знаю :( может sketch скрипты понимает?

**Comment by iliakan** [comment]
<defs>
  <style type="text/css">
   <![CDATA[
    @font-face {
        font-family: Delicious;
        src: url('http://nimbupani.com/demo/svgfonts/delicious-roman.otf');
    }
   ]]>
 </style>
</defs>
<text x="100" y="100" style="font-family: 'Delicious'; font-weight:normal; font-style: normal">
 Text using CSS @font-face
</text>   

А если так подключать?

**Comment by iliakan** [comment]
Ping @r5m

**Comment by tyv** [comment]
не будет работать, нужно конвертить в base64
> embed the fonts using a data uri: src: url("data:application/font-woff;base64,<base64 encoded font here")

**Comment by tyv** [comment]
но тогда каждая картинка будет по размеру + шрифт

**Comment by iliakan** [comment]
Tyv уверен что не будет?

**Comment by iliakan** [comment]
Рекомендуют...

**Comment by tyv** [comment]
так там как раз проблема в том что не работает пример с @font-face + url

**Comment by iliakan** [comment]
Работает. Только что протестил на старой MacOS, где Consolas нет.

**Comment by iliakan** [comment]
В каждый SVG добавлю значит шрифт, если получится с лицензией решить.

**Comment by tyv** [comment]
ну я так понимаю это не гарантируется

**Comment by iliakan** [comment]
@tyv я тебя не понимаю ;) это не работает? при каком сценарии? 
Как я понял, тестили добавление шрифта в CSS выше в топике.

**Comment by iliakan** [comment]
Вот, в тестовых целях:
http://js.cx/svg.svg - без шрифта
http://js.cx/svg2.svg - со шрифтом

**Comment by tyv** [comment]
ff не скачивает

**Comment by tyv** [comment]
круче! скачивает но не применяет!

**Comment by tyv** [comment]
обожаю эти браузер

**Comment by iliakan** [comment]
Вот, в тестовых целях:
https://js.cx/svg.svg - без шрифта
https://js.cx/svg2.svg - со шрифтом

**Comment by iliakan** [comment]
Sorry, SSL.

**Comment by r5m** [comment]
```SVG
<defs>
  <style type="text/css">
   <![CDATA[
    @font-face {
        font-family: Delicious;
        src: url('http://nimbupani.com/demo/svgfonts/delicious-roman.otf');
    }
   ]]>
 </style>
</defs>
<text x="100" y="100" style="font-family: 'Delicious'; font-weight:normal; font-style: normal">
 Text using CSS @font-face
</text>   
```

Это работает в SVG как в отдельном документе (если открыть в браузере файл SVG).
И перестает работать, если SVG встроить в HTML документ через тег <img>.

**Comment by iliakan** [comment]
@r5m То есть, если SVG картинка, то всё ок, да?
Вот попробуйте сравнить https://js.cx/svg2.svg и https://js.cx/svg.svg

**Comment by r5m** [comment]
В этих примерах все работает (в *svg2.svg* шрифт подключается).
Но если теперь *svg2.svg* вставить в HTML-страницу, то шрифт перестанет подключаться.

**Comment by iliakan** [comment]
@r5m Да, спасибо, теперь вижу.

**Comment by iliakan** [comment]
Похоже в SVG ссылку на шрифт толком не вставишь кросс-платформенно.
Тогда будем в SVG font-family указывать расширено.

Чтобы картинки не ломались, размеры fallback-шрифтов должны быть схожими. Здесь у Consolas проблемка.

Вот сделал HTML:
```html
<div style="font-family:Consolas">alert( this.name + ' бежит, скорость ' + this.speed );</div>
<div style="font-family:Menlo">alert( this.name + ' бежит, скорость ' + this.speed );</div>
<div style="font-family:Monaco">alert( this.name + ' бежит, скорость ' + this.speed );</div>
<div style="font-family:Lucida Console">alert( this.name + ' бежит, скорость ' + this.speed );</div>
<div style="font-family:Andale Mono">alert( this.name + ' бежит, скорость ' + this.speed );</div>
<div style="font-family:Courier New">alert( this.name + ' бежит, скорость ' + this.speed );</div>
<div style="font-family:PT Mono">alert( this.name + ' бежит, скорость ' + this.speed );</div>
```
URL: https://js.cx/fonts.html
Скрин: http://ilyakantor.ru/screen/2015-04-17_0952.png

Получается, Consolas сильно меньше других. На него, выходит, в SVG нельзя ориентироваться, так как при fallback сильно меняются размеры.

@Bezart ?

**Comment by Isk1n** [comment]
Inkscape версии 0.49 и выше может автоматом преобразовывать текст в кривые http://stackoverflow.com/questions/20577316/svg-font-face-works-in-svg-but-not-when-included-in-a-page . Правда размер при этом увеличивается на порядок

**Comment by Bezart** [comment]
Конвертирование в кривые можно легко сделать при экспорте, это не проблема. Проблема выбрать правильный подход. Существует несколько вариантов настроек экспорта шрифтов внутри SVG:

1. SVG Fonts (without embed). Самый маленький размер файла, то что мы сейчас используем. Фейлится при использовании "небезопасных" шрифтов

2. SVG Fonts (with embed). Разные настройки http://take.ms/MRvVT Увеличивает размер

3. Curves. Самый кроссбраузерный вариант в плане отображения, размер файла большой.

@iliakan сейчас пробую вариант с системными шрифтами (вариант 1), может прокатит

**Comment by iliakan** [comment]
@Bezart, SVG fonts (Именно svg-шрифты) браузеры слабо поддерживают (Firefox не поддерживает).

**Comment by Bezart** [comment]
@iliakan Firefox, да, не поддерживает svg-глифы, то есть вариант 2 отпадает

Касательно оставшихся 2х вариантов:

### Вариант 1

Безопасные шрифты в SVG через ```@font-face``` Размер файла **7.1Kb**

Courier New: http://take.ms/9fPkw :( 
```
font-family: "Courier New", Courier, "Nimbus Mono L", monospace
```

Tahoma: http://take.ms/ZSlli
```
font-family: Tahoma, Geneva, "DejaVu Sans", sans-serif
```

Мне нравится Trebuchet (http://take.ms/3JdeM), но под Linux пока не нашел аналога


### Вариант 2
Кривые, кроссбраузерный вариант, размер файла без оптимизации и сжатия: **152Kb**

**Comment by iliakan** [comment]
@Bezart Мы можем в SVG использовать несколько шрифтов с fallback, чтобы точно что-то подхватывалось, просто по размеру чтоб не очень отличались.

**Comment by Bezart** [comment]
@iliakan ну для этого я и прописал стили ^ там где фолбек

**Comment by iliakan** [comment]
Посмотрели.
1) 
В SVG шрифт внедрить x-браузерно нельзя

2) 
а) Автоперевод в кривые через inkscape ломает картинки, напр. `metric-client-left-top-rtl.svg` была сломана.
б) Перевод в кривые в Sketch убирает цвета из рисунка, пробовали там же.

Размер после перевода в кривые незначительно уступает PNG@2x. А обычный PNG меньше.


3)
Fallback картинку портит так или иначе, всё прыгает, даже если на похожий шрифт. Поэтому не подходит.

=========
Резюме: переходим на PNG.

**Comment by iliakan** [comment]
Должно стать ок, перешли на png #487
