### ISSUE TITLE
Косяк с поисковой строкой 

### ISSUE THREAD

**Issue by MisaGu** [iliakan/javascript-nodejs#464]
1. на главной странице криво стоит placeholder (Chrome 41.0.22)
2. при нажатии на "лупу" в право-верхнем углу при разворачивании блока видно наложение текста на иконку авторизации, если добавить фон все будет гудно )))
3. header в "карта учебника" вылезает на 2 пикселя справа + кнопка "закрыть" - крестик уходит за скролл страницы

З.Ы. - это превое что бросилось в глаза

**Comment by iliakan** [comment]
1. Можно скриншот?

2. Это именно при разворачивании, да?
@tyv, зачем там на `body` класс `paranja_open`, кстати, что он означает? влияет на всю страницу?

3. Можно скриншот?

**Comment by MisaGu** [comment]
1. http://www.awesomescreenshot.com/image/77063/ec28720d47b1a056bad6e823d7be916b
2. http://www.awesomescreenshot.com/image/77139/b5e6446c4b2d35140ad1a5fd6509210d
3. http://www.awesomescreenshot.com/image/77079/123ef74b4e941a3eec0472a72e25d55c

**Comment by iliakan** [comment]
@MisaGu спасибо, не могли бы уточнить также ширину экрана?

**Comment by teodorovych** [comment]
По поводу карты и 2-х пикселей.
Зависит от масштаба.
<div class="tutorial-map__filter> больше на несколько пикселей чем <div class="tutorial-map>

**Comment by iliakan** [comment]
В каком масштабе смотреть?

**Comment by teodorovych** [comment]
Смотрю в Firefox. Разница есть всегда. Визуально более заметна при уменьшении масштаба.
Например:
![firefox](https://cloud.githubusercontent.com/assets/11709520/7140729/abebb2b2-e2d5-11e4-9485-d7cf4ff73960.jpg)
При уменьшении масштаба, разница с 3-х пикселей, увеличивается до 12 (видел сам)

**Comment by iliakan** [comment]
На очень маленьком масштабе видна разница у меня в Firefox. То есть, при многократном уменьшении.

Эта проблема понятна, воспроизвёл, спасибо.

**Comment by iliakan** [comment]
@tyv, если что-то не воспроизводится по этой таске - пиши, я вроде всё увидел.

**Comment by tyv** [comment]
я на маке не могу воспроизвести

**Comment by tyv** [comment]
ff@37.0.1

**Comment by iliakan** [comment]
@tyv тут 3 глюка, какой из них?

**Comment by tyv** [comment]
третий

**Comment by iliakan** [comment]
Chrome широкий экрам масштаб ---

**Comment by tyv** [comment]
у меня ок https://yadi.sk/i/H_5Gmt61g3XM4

**Comment by iliakan** [comment]
Если будут рекомендации по воспроизведению 3) для @tyv - welcome.

**Comment by fdr-** [comment]
Всё зависит от ширины ползунка справа, поскольку он влияет на положение правой границы блока `.tutorial-map` и не влияет на положение правой границы `.tutorial-map__filter`.

И тут начинается самое интересное. :)

Система (версия) | Браузер (версия) | Ширина ползунка, px | Ссылка
--- | --- | --- | ---
Ubuntu (14.04) | Chrome (41) | 15 | https://yadi.sk/i/EJy6JI4Pg6phS
Ubuntu (14.04) | Firefox (37) | 13 | https://yadi.sk/i/mcTl16wMg6pht
Windows (7) | Chrome (42) | 17 | https://yadi.sk/i/j1UukdKLg6pi9
Windows (7) | Firefox (37) | 17 | https://yadi.sk/i/jk-VL0o9g6piK
Windows (7) | IE (11) | 17 | https://yadi.sk/i/ZVpRECVxg6piZ
> 40 - margin слева и справа у `.tutorial-map`.

Т.е. в Windows `.tutorial-map__filter` вылезает ровно на `2px`.

Можно рекомендовать использовать virtualbox+vagrant. :)

**Comment by FFxSquall** [comment]
Как вариант сделать безопасный отступ справа скажем 20px. Либо избавиться от position fixed и таскать этот блок js'ом =)

**Comment by tyv** [comment]
круто, я подумаю

**Comment by MisaGu** [comment]
... эмм размер крана 1920

**Comment by iliakan** [comment]
@tyv, метка need more info актуальна?

**Comment by tyv** [comment]
нет, надо делать; случай просто редкий а подумать надо

**Comment by tyv** [comment]
можно закрывать, карта сделана по другому немного, должно решать проблему
