### ISSUE TITLE
Список методов оплаты

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#466]
Пересмотреть логику и дизайн кнопок выбора метода оплаты.

**Comment by Bezart** [comment]
Учебник:
http://monosnap.com/image/o5qcqr7tzrNPRbVeux2JQjK0UC4yli

Курсы
http://take.ms/Tkpo5

В исходнике еще пару юзкейсов

**Comment by iliakan** [comment]
Выбор валюты, как и любое другое уточнение метода оплаты, имхо должен быть на строке под методом оплаты, а не справа.

То есть, "раскрытие" пункта оплаты и выбор дополнительных параметров. Как на амазоне.

**Comment by Bezart** [comment]
По-моему лишнее, к тому же место занимать будет неоправданно много. В идеале пользователи не будут менять валюту, так что это не обязательное поле. В общем, предлагаю оставить так как есть.

**Comment by iliakan** [comment]
Лишняя строка появится, зато всё красиво и в едином стиле.

**Comment by Bezart** [comment]
http://take.ms/FhO3Q

Если что, сообщение показывать по той же логике:
http://take.ms/sLWjN

**Comment by tyv** [comment]
@Bezart смотри у нас уже есть  подписи такого стиля
https://yadi.sk/i/9FmN0Bp9fzB2H
может сделаем одинаково?

**Comment by Bezart** [comment]
@tyv согласен

**Comment by iliakan** [comment]
@tyv, посмотри пожалуйста текущий дизайн, там форма оплаты поменялась немного, стала проще. И респонсивность прорисована.

Может, имеет смысл брать брать название способа оплаты как HTML-строку из переменной?
