### ISSUE TITLE
Дизайн: респонсивность к тестам

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#468]
Нарисовать, как тесты и результат выглядят на телефонах и планшетах.

Возможно, небольшие фиксы к текущему выводу, но в общем - что-то, на что можно ориентироваться при вёрстке.

**Comment by iliakan** [comment]
@Bezart сейчас тесты на мобильных выглядят совершенно сломаными, это не improvement, а bugfix.

**Comment by Bezart** [comment]
Добавил дизайн на страницу Responsive Logic:

Главная:
http://monosnap.com/image/qX5hbIJ55I1g49ikSNHv1vlNMLTDK4

Вопрос:
http://monosnap.com/image/ZdHf3sstSrozBcG2OD0naa7iYTa4vw

Результаты:
http://monosnap.com/image/pcxx61WK4lsZT2ypdjfjPSfOfLuXNM

**Comment by tyv** [comment]
может правильные/неправильные прямо легким фоном выделить? эти бордеры будет не оч видно, а с фоном очень наглядно

**Comment by Bezart** [comment]
@tyv это первое что я попробовал, но легкий зеленый/красный фон сливается в случае если есть код. Может просто цвета такие выбрал... в общем, я не против если есть предложение которое смотрится нормально

**Comment by iliakan** [comment]
@tyv, какой сейчас state здесь?

**Comment by tyv** [comment]
ну я их сверстал, теперь бы с живыми данными посмотреть и поотлавливать баги

**Comment by iliakan** [comment]
Вот тесты http://ilyakantor.ru/screen/2015-04-25_2020.png
здесь должно быть что-то типа "Вопрос 1 из 20"

**Comment by iliakan** [comment]
Посмотри плиз наживую, баги увидишь быстро.

**Comment by tyv** [comment]
это надо закрыть
