### ISSUE TITLE
Клики по ссылкам

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#470]
Сейчас при клике колесом на ссылки ничего не происходит. При зажатом ctrl ссылки открываются в том же окне. Хотелось бы нормального поведения в этих случаях (открытие в новом табе)

**Comment by iliakan** [comment]
Обновил код аналитики, сейчас ок? Если нет - напиши, куда и чем жать, посмотрю ещё раз.

**Comment by iliakan** [comment]
Не могу воспроизвести клик колесом.
У меня он открывает в новой вкладке.
