### ISSUE TITLE
Задача в песочнице не соответствует решению на странице.

### ISSUE THREAD

**Issue by electrovladyslav** [iliakan/javascript-nodejs#471]
В задаче [Получите пользовательский атрибут](https://learn.javascript.ru/task/get-user-attribute) в диве есть id:
`<div id="widget" data-widget-name="menu">Выберите жанр</div>`
 и в решении этот элемент находится по getElementById. 
В песончнице, на [планкере](http://plnkr.co/edit/hiuRomq3zff9cpRZcHFF?p=preview) id у дива нет, , так что по getElementById найти его проблематично.

**Comment by iliakan** [comment]
Thanks, fixed!
