### ISSUE TITLE
Стили инлайнового кода

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#477]
Провел некоторое время читая учебник и заметил что если в тексте встречается инлайновый код, то чтение немного усложняется, так как отличия шрифтов слабые. Предлагаю попробовать жирное начертание для кода: http://take.ms/RivWy

**Comment by iliakan** [comment]
Могу показать у себя, как получилось. Можно `Consolas` -> `PT Mono` ;)

**Comment by iliakan** [comment]
Решили оставить Consolas.
