### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by fdr-** [iliakan/javascript-nodejs#478]
Письмо о подтверждении регистрации приходит даже в том случае, когда форма не проходит проверку.
По ссылке в письме - 404.

Некорректная ошибка при повторной регистрации e-mail: https://yadi.sk/i/cjEw0ootfzHwe

**Comment by iliakan** [comment]
Какой браузер? Что набрать, чтобы воспроизвести?

**Comment by fdr-** [comment]
#### Браузеры
* Linux
 * Chrome v. 41.0.2272.118 (64-bit)
 * Firefox v. 37.0.1
* Windows
 * Chrome v. 42.0.2311.90 m
 * Firefox v. 37.0.1

> Не знаю зачем всё это скопировал, простого "последние" наверное бы хватило. :)
> Насколько понимаю, проверки на клиенте и нет (за исключением html5 атрибутов), поэтому дело не в браузере.

#### Как повторить
**Email**: любой e-mail
**Имя пользователя**: 1
**Пароль**: 1

Форма отправляет данные, от сервера приходят ошибки
```json
{"errors":{"password":"Пароль должен быть минимум 4 символа.","displayName":"Имя пользователя должно иметь не менее 2 символов."}}
```
но письмо всё равно отправляется на указанную почту с просьбой подтвердить регистрацию.

**Comment by iliakan** [comment]
Очень интересная проблема. Отсылку почты я поправил, но вот валидация...

У меня вот так: http://ilyakantor.ru/screen/2015-04-15_1047.png.

**Comment by iliakan** [comment]
Не могу воспроизвести проблему.

**Comment by fdr-** [comment]
Нужно было создать 2 разные записи, мой косяк.

Для того, чтобы увидеть ошибку зарегистрированного ящика, нужно пройти проверки в 2х других полях, т.е.:

**Email**: зарегистрированный e-mail
**Имя пользователя**: qw
**Пароль**: qwer
