### ISSUE TITLE
Кнопа наезжает на лого

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#480]
http://ilyakantor.ru/screen/2015-04-15_1414.png - что делаем?

**Comment by soltx** [comment]
как насчёт иконок? сэкономит место или bottom center fixed

**Comment by iliakan** [comment]
А вот ещё от гугл бота :)
http://ilyakantor.ru/screen/2015-04-15_2329.png

**Comment by FFxSquall** [comment]
Мне кажется на мобильных устройствах этой кнопке там не место. Можно вынести в выпадающее меню, там где карта сайта.

**Comment by tyv** [comment]
я уюрал кнопку в последнем PR на ширине < 400px

**Comment by iliakan** [comment]
@tyv, может имеет смысл спросить @Bezart что делать? Я ему напомню.

**Comment by tyv** [comment]
ну откатим потом, мне было быстро, людей это затрагивает мало

**Comment by Bezart** [comment]
@FFxSquall да, я так и прорисовывал, кнопку скрываем на мобильном разрешении. Идея поместить в дропдаун мне тоже нравится, можно как-то так: http://monosnap.com/image/VfHTEyuuO9dqts9PHlOGxOvQMhxTdM

**Comment by iliakan** [comment]
@Bezart  там ещё проскакивала мысль вместо выпадающего селекта сделать там просто меню. Что думаешь?

**Comment by FFxSquall** [comment]
@iliakan, @Bezart Да как я уже говорил, можно меню сделать не в селекте, вот так например http://lmimg.ru/4xSbwDCCT

**Comment by Bezart** [comment]
@FFxSquall @iliakan первоначально так и было, но я изменил на текущий дропдаун, так как переходы между главными разделами на мобильных устройствах очень не многочисленны. Хотелось бы иметь только востребованную функциональность в мобильном меню и желательно не перегружать эту область

**Comment by FFxSquall** [comment]
Тогда просто нужно поправить код, что бы при нахождение в конкретном  разделе именно он был выбран в селекте, сейчас всегда первый пункт

**Comment by iliakan** [comment]
@tyv, по покупке учебника нарисуй, пожалуйста, можно просто в вёрстку добавить, логику по показу я в jade добавлю.

**Comment by iliakan** [comment]
@tyv, ты наверно сделал, да? Куда смотреть?

**Comment by tyv** [comment]
нет, ща сделаю
