### ISSUE TITLE
Нет отображается код в окнах, ведущих на plnkr.co

### ISSUE THREAD

**Issue by Saviloff** [iliakan/javascript-nodejs#481]
Не отображается на странице код в специальных окнах, ведущих на plnkr.co
На скриншоте красным выделил.
Пробовал в Хроме и Фаерфоксе. Одинаково.
http://javascript.ru/forum/attachments/site/2664d1428939953-oshibki-i-bagi-na-sajjte-bezymyannyjj-jpg
Страница: https://learn.javascript.ru/testing

**Comment by iliakan** [comment]
Очень интересный баг, я не могу воспроизвести.
Можно подробнее?

Раньше была такая проблема, я думал что исправил её. Может, кеш?

**Comment by fdr-** [comment]
Кэш почистил на всякий.

Именно для указанной страницы не совпадают протоколы, браузер блокирует ресурсы.

https://yadi.sk/i/bj208MPng2FWr

**Comment by iliakan** [comment]
Обновите. Работает?

**Comment by fdr-** [comment]
Не работает. :(

**Comment by iliakan** [comment]
А сейчас?

**Comment by fdr-** [comment]
Без изменений.

**Comment by iliakan** [comment]
Да, надо же, там старые файлы. Ресинкнул учебник на прод.
Вот ссылка, работает? https://js.cx/article/testing/pow-1/ (кеш браузера очистить)

**Comment by fdr-** [comment]
Да, теперь работает.
