### ISSUE TITLE
Usability баг навигации

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#482]
Сейчас верхний селект на мобилах, если открыть - там выпадает выбор пунктов верхнего уровня.

Проблема в том, что по умолчанию учебник - первый. И если нужно перейти именно на учебник, то упс.

Либо надо добавить справа от селекта кнопу "перейти", либо пустую опцию к селекту  (которая будет выбрана по умолчанию).

**Comment by FFxSquall** [comment]
А какой там смысл в селекте? Как по мне, это очень не удобно, лучше сделать классическое меню по пунктам, только вертикальное.

**Comment by iliakan** [comment]
@Bezart То есть, опишу проблему точнее.

Есть страницы, которые сейчас вне разделов верхних. Например "о сайте".

Нужно либо внести такую страницу в один из разделов, либо предусмотреть пустой пункт в селекте.

**Comment by iliakan** [comment]
@FFxSquall селект, вроде, норм выглядит и достаточно удобен.

**Comment by Bezart** [comment]
В общем, предлагаю оставить так как есть, только прикрутить логику к селекту (что бы он показывал текущий раздел) "О сайте" сейчас показывается в футере, там ему и место. Не вижу пока ничего что было бы действительно полезно добавить.

**Comment by iliakan** [comment]
Пункт "Выберите раздел", если мы не знаем, где юзер сейчас (вне раздела).
