### ISSUE TITLE
Не открываются архивы туториалов

### ISSUE THREAD

**Issue by Isk1n** [iliakan/javascript-nodejs#485]
Пробую распаковать zip-архивы из этого раздела https://learn.javascript.ru/ajax-xmlhttprequest (phones.zip и phones-async.zip) и из этого https://learn.javascript.ru/xhr-onprogress (progress.zip). 
Unzip пишет:

    error [phones-async.zip]:  missing 179395127 bytes in zipfile
    error [phones.zip]:  missing 717211 bytes in zipfile
    error [progress.zip]:  missing 307382 bytes in zipfile

Размеры файлов:

    4259 phones-async.zip
    4158 phones.zip
    1938 progress.zip

md5:

    6eb93d7db912d9494991312dab35c39d  phones-async.zip
    f8fce707f1570554da958e2c10d31006  phones.zip
    6dfe1e8d583c94ac49441701ed59b018  progress.zip

Это только у меня такое?

**Comment by iliakan** [comment]
Вижу, скоро будет исправлено.

**Comment by iliakan** [comment]
Fixed.
