### ISSUE TITLE
Шрифт в SVG. Переход с Consolas?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#487]
У нас используется Consolas как основной шрифт. С ним проблема - он под Linux не распространяется, под Mac его тоже нет по умолчанию. 

В CSS можно указать несколько шрифтов, это решит проблему с HTML.

Но в SVG тоже шрифт используется. Если его нет, то SVG корёжит. На шрифт завязаны разные размеры внутри SVG.

Выходов несколько:
1) Перевести шрифты в SVG в кривые. Это можно автоматически сделать, SVGшки вырастут, скажем был 1kb, станет 16kb.
2) Использовать в SVG шрифт через `@font-face`. Consolas платный при этом, за pageview причём, это неудобная система, надо будет его сменить. 

Вот несколько вариантов:
PT Mono http://ilyakantor.ru/screen/2015-04-16_2337.png
Droid Sans Mono http://ilyakantor.ru/screen/2015-04-16_2337-1.png
DejaVu Sans Mono http://ilyakantor.ru/screen/2015-04-16_2338.png

Мне нравится DejaVu Sans Mono из них, но у него размер 137k в woff2 и 183k в woff. Не жирновато ли качать?

Ideas welcome.

**Comment by iliakan** [comment]
Update: через http://www.fontsquirrel.com/tools/webfont-generator сделал subsetting на символы: `!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¢£¥¨©«®´¸»ˆ˚˜ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё`

Получилось 22/18kb в DejaVu Sans Mono.

**Comment by Bezart** [comment]
можно заменить на что-то стандартное и не изобретать велосипед, но тогда нужно будет править иллюстрации... я посмотрю что можно сделать и что будет быстрее

**Comment by iliakan** [comment]
На что стандартное?

**Comment by iliakan** [comment]
Шрифт, который есть на Mac, Win, Lin и, желательно, на Android/iOS? Это какой?

**Comment by FFxSquall** [comment]
@iliakan, Arial =)

**Comment by fdr-** [comment]
@iliakan 
> В CSS можно указать несколько шрифтов, это решит проблему с HTML.

Правильно ли я понимаю, что для html будет что-то подобное:
```css
font-family: Consolas, 'Lucida Console', 'DejaVu Sans Mono', monospace;
```
И если так, то почему подобное нельзя сделать для svg? Даже, если вдруг, какие-то проблемы с тегом `style`, то должны корректно работать атрибуты.

```xml
<text font-family="Consolas, 'Lucida Console', 'DejaVu Sans Mono', monospace">...</text>
```

@FFxSquall, увы, но Arial на Linux нужно ставить отдельно. По крайней мере в Debian/Ubuntu.

**Comment by iliakan** [comment]
@fdr- разные шрифты имеют разные размеры. SVG - это иллюстрации. В них важна длина, которую занимает текст, поскольку вокруг текста всякие прямоугольники, отступы и т.п.

**Comment by Bezart** [comment]
перенесли обсуждение в #463 решили переходить на PNG

**Comment by iliakan** [comment]
Перешли на PNG, так как:
1) в SVG внедрить шрифт кросс-браузерно нельзя, 
2) в кривых SVG сравним с PNG + перевод в кривые глючит.
3) fallback в SVG толком не возможен, т.к. разные шрифты отличаются в деталях и сбивают картинки.
