### ISSUE TITLE
Поправки к содержимому некоторых разделов по DOM.

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#494]
1 )  Раздел "Добавление и удаление узлов", [Итого](https://learn.javascript.ru/modifying-document#%D0%B8%D1%82%D0%BE%D0%B3%D0%BE):

>  Вставка и удаление узлов:

    parent.appendChild(elem)
    parent.insertBefore(elem, nextSibling)
    parent.removeChild(elem)
    parent.replaceChild(elem, currentElem)

> Все эти методы возвращают elem.

Вопрос вызывает сочетание последних двух строк. В предпоследней надо бы переименовать elem на  newElem, а currentElem на elem.

********************
2 )  Раздел "Мультивставка: insertAdjacentHTML и DocumentFragment", [Добавление множества узлов](https://learn.javascript.ru/multi-insert#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B0-%D1%83%D0%B7%D0%BB%D0%BE%D0%B2):

>  Но операция += с innerHTML не работает с DOM. Она не прибавляет, а заменяет всё содержимое списка на дополненную строку. 

Прочев учебник, честно говоря, подумал, что оператор "+=" для innerHTML делает исключение (а чудес в js хватает), и не учитывает старое значение innerHTML(удаляет его). Только посмотрев видео, прилагающееся к уроку, понял, в чем дело. Лучше переписать как-то так:

>"Она не прибавляет дополненную строку к DOM-содержимому списка, а заново вставляет содержимое списка, дополненное строкой, в DOM." 

Ну или вроде того, я не особо старался. В общем, заменить нынешнее предложение.

P.S. Нашел еще в разделе "Свойства узлов..." параграф [Тонкости innerHTML](https://learn.javascript.ru/basic-dom-node-properties#%D1%82%D0%BE%D0%BD%D0%BA%D0%BE%D1%81%D1%82%D0%B8-innerhtml). Там поподробнее написано, и менее неоднозначно, но все равно пограничный случай:

> На практике этим следует пользоваться с большой осторожностью, так как фактически происходит не добавление, а перезапись:

Если очень кратко нужно исправить, то хотя так:

> происходит не добавление, а добавление с перезаписью:

Хотя, конечно, можно и забить. "Правильные верблюды" найдут дорогу. Но в разделе "Мультивставка..." лучше поправить.

*************
3 ) На всякий случай, вдруг актуально: для <IE10 отсутствует прозрачность на управляющих кнопках в правом верхнем углу примеров. Хотя для местного контингента пользователей это вряд ли актуально.

**Comment by iliakan** [comment]
1) Не понял проблему.
2) Раскрыл тему пошире.
3) Для контингента, судя по браузерным статам, совсем не актуально.

**Comment by discodanser** [comment]
По поводу первого пункта:

>  parent.replaceChild(elem, currentElem)
    Все эти методы возвращают elem.


Вроде как здесь должен возвращаться currentElem.
