### ISSUE TITLE
Навигация по DOM-элементам, интерактивное путешествие

### ISSUE THREAD

**Issue by fdr-** [iliakan/javascript-nodejs#497]
[Для примера](https://learn.javascript.ru/traversing-dom#интерактивное-путешествие) подгружается скрипт https://js.cx/script/travel.js, который содержит сомнительную инициацию (в конце):

```js
  if (iframe.contentDocument.readyState == 'complete') {
    setTimeout(init, 100);
  } else {
    iframe.contentWindow.onload = function() {
      setTimeout(init, 100);
    };
  }
```
Как следствие, пример срабатывает через раз.

Вероятно, должно быть:
```js
iframe.contentWindow.onload = init;
```

**Comment by iliakan** [comment]
То есть, у вас init не вызывается? Может, ошибка какая в консоли?

**Comment by fdr-** [comment]
`init` вызывается, но контент загружен не полностью, из-за чего вылезает ошибка.

https://yadi.sk/i/oW7fPv11g5BGK

Похоже, что Chrome (v. 42.0.2311.90 m) не знает, что `complete` - это полностью загруженный контент, по крайней мере для `iframe` :) В других браузерах всё в порядке.

**Comment by iliakan** [comment]
На всякий случай добавил задержку инициализации, должно работать так или иначе :)
