### ISSUE TITLE
Мультивставка: insertAdjacentHTML и DocumentFragment, append/prepend, before/after, replaceWith

### ISSUE THREAD

**Issue by fdr-** [iliakan/javascript-nodejs#498]
[В примере](https://learn.javascript.ru/multi-insert#append-prepend-before-after-replacewith) используется `Element.prototype.mutation`, не нашёл такого [в репозитории](https://github.com/Financial-Times/polyfill-service/tree/master/polyfills).
[По ссылке](https://cdn.polyfill.io/v1/polyfill.js?features=Element.prototype.mutation) отдаётся пустая обёртка, пример не работает.

Нужно использовать `Element.prototype.append`, Т.е.:
```html
<script src="https://cdn.polyfill.io/v1/polyfill.js?features=Element.prototype.append">
```

**Comment by iliakan** [comment]
Fixed, thanks!

**Comment by fdr-** [comment]
Руководствовался только ошибкой консоли, но не посмотрел код, в коде используется ещё и `Element.prototype.after`:
```html
<script src="https://cdn.polyfill.io/v1/polyfill.js?features=Element.prototype.append,Element.prototype.after"></script>
```
Теперь код полностью рабочий. :)

**Comment by iliakan** [comment]
Thanks fixed.
