### ISSUE TITLE
Мышь: Drag'n'Drop более глубоко, dragmanager

### ISSUE THREAD

**Issue by fdr-** [iliakan/javascript-nodejs#499]
[В примере](https://learn.javascript.ru/drag-and-drop-objects#dragmanager) ([пример отдельно](https://learn.javascript.ru/article/drag-and-drop-objects/dragDemo/)) подгружается [скрипт](https://learn.javascript.ru/article/drag-and-drop-objects/dragDemo/DragManager.js), который начинается строкой:

```js
var dragManager = new function() {
```
Ниже выполняется другой скрипт, который начинается строкой:
```js
DragManager.onDragCancel = function(dragObject) {
```
Не знаю, говорит, кто такой `DragManager`, пример не работает.

**Comment by iliakan** [comment]
Похоже, проблема с Cloudflare. Они почему-то отдали очень старый файл. Я очистил кеш и заработало. Если ещё повторится - буду с ними разбираться, странно.
