### ISSUE TITLE
Примеры: неверно указан протокол

### ISSUE THREAD

**Issue by fdr-** [iliakan/javascript-nodejs#501]
Эти примеры из разных статей объединяет одна и та же ошибка - используется `http` протокол, ни один из примеров не работает.

https://js.cx/task/clock/solution/
https://js.cx/task/slider-widget/solution/
https://js.cx/task/selectable-list-component/solution/
https://js.cx/task/voter/solution/
https://js.cx/task/table-template/solution/
https://js.cx/task/menu-template/solution/
https://learn.javascript.ru/article/custom-events/menu-callback/
https://learn.javascript.ru/article/custom-events/menu-event/
https://js.cx/task/voter-events/solution/
https://js.cx/task/selectable-list-evented/solution/
https://js.cx/task/custom-select/solution/
https://js.cx/task/slider-events/solution/
https://learn.javascript.ru/article/webcomponent-build/ui-slider/
https://learn.javascript.ru/templates#шаблонизация-компонент - смотреть на пример с капитаном очевидность (ko)

**Comment by iliakan** [comment]
Все почистил, были старые файлы. Сейчас всё ок, да?

**Comment by fdr-** [comment]
Не заработали:
https://learn.javascript.ru/article/webcomponent-build/ui-slider/
https://learn.javascript.ru/templates#шаблонизация-компонент - пример с knockout.js

---
Кроме того, в примере https://js.cx/task/selectable-list-evented/solution/ ошибка.
[Здесь](https://js.cx/task/selectable-list-evented/solution/listSelect.js) создаётся объект event
```js
var widgetEvent = new CustomEvent("select", {
  bubbles: true,
  detail: getSelected()
});
```
А в другом скрипте попытка вызвать свойство, которого нет
```js
document.querySelector('#heroes').addEventListener('select', function(event) {
    alert(event.value); /** undefined */
});
```
Скорее всего должно быть:
```js
document.querySelector('#heroes').addEventListener('select', function(event) {
    alert(event.detail);
});
```

**Comment by iliakan** [comment]
Спасибо, исправлено.
