### ISSUE TITLE
Примеры: 404 для подключаемых ресурсов

### ISSUE THREAD

**Issue by fdr-** [iliakan/javascript-nodejs#502]
В примерах неверно указаны пути на скрипты и стили, либо они не существуют. Примеры не работают.

https://learn.javascript.ru/article/js-animation/move/
https://learn.javascript.ru/article/js-animation/width/
https://js.cx/task/animate-ball/solution/
https://js.cx/task/animate-ball-hops/solution/

**Comment by iliakan** [comment]
Hope fixed.
