### ISSUE TITLE
Не великоват ли баннер?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#510]
Jetbrains не слишком большой по виду? Может уменьшить?

**Comment by Bezart** [comment]
На нормальном разрешении – норм (разве что 10–20 px по высоте убрать). В любом случае, всегда есть опция убрать баннер. А вот на таблетах, нужно что-то сделать: http://take.ms/M4QjT может убрать нижнюю часть? ограничение по высоте, в общем, должно оставаться прежним (можно просто пропорционально уменьшать)
