### ISSUE TITLE
run на форуме перестал работать

### ISSUE THREAD

**Issue by roni-ridz** [iliakan/javascript-nodejs#514]
Refused to display 'http://lookatcode.com/showhtml' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by iliakan** [comment]
Поправлю. Можно ссылку на тему на форуме?

**Comment by roni-ridz** [comment]
http://javascript.ru/forum/misc/55281-razdelit-stroku-i-vpisat-ee-v-tablicu-%5Bdopisat-70%25-uzhe-est%5D.html

в любой теме run не работет

**Comment by iliakan** [comment]
Fixed. Thanks!

**Comment by roni-ridz** [comment]
тоже самое пропал run
Refused to display 'http://lookatcode.com/showhtml' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
http://javascript.ru/forum/jquery/41020-udalit-ehlement-input-s-sokhraneniem-ego-znacheniya-v-td.html#post269823

**Comment by iliakan** [comment]
Только что попробовал, работает. Security понизил на всякий случай.
