### ISSUE TITLE
4 опечатки + неисправленное

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#519]
1 ) Опечатка в разделе "Введение в браузерные события", [addEventListener и removeEventListener](https://learn.javascript.ru/introduction-browser-events#addeventlistener-%D0%B8-removeeventlistener):

> Нет метода, который позволяет считать обработчики событий, назанченные через addEventListener. 

"назанченные"
*****************
2 ) Опечатка в разделе "Генерация событий на элементах", [Отмена действия по умолчанию](https://learn.javascript.ru/dispatch-events#%D0%BE%D1%82%D0%BC%D0%B5%D0%BD%D0%B0-%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E):

> Вызов event.preventDefault() является возможностью для обработчика событие сообщить в сгенерировавший событие код, что эти действия продолжать не надо. 

" для обработчика событиЯ сообщить"
*****************
3 ) Опечатка в разделе ["Шаблонизатор LoDash"](https://learn.javascript.ru/template-lodash), Итого:

> можно вызвать передать данные сразу в _.template вторым аргументом.

Кстати, 27.04.2015 ссылка на эту страницу редиректится на ["Эволюция шаблонных систем для JavaScript"](https://learn.javascript.ru/templates). На которой тоже есть опечатка (см.следующий пункт).
*****************
4 ) Опечатка в разделе "Эволюция шаблонных систем для JavaScript", [Кросс-платформенность](https://learn.javascript.ru/templates#%D0%BA%D1%80%D0%BE%D1%81%D1%81-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C):

>Эту проблему решили обошли быстро. 

*****************
5 ) Подниму вопрос про раздел "Добавление и удаление узлов", [Итого](https://learn.javascript.ru/modifying-document#%D0%B8%D1%82%D0%BE%D0%B3%D0%BE):

>  Вставка и удаление узлов:

    parent.appendChild(elem)
    parent.insertBefore(elem, nextSibling)
    parent.removeChild(elem)
    parent.replaceChild(elem, currentElem)

> Все эти методы возвращают elem.

Вопрос вызывает сочетание последних двух строк. В предпоследней надо бы переименовать elem на  newElem, а currentElem на elem.

Пояснения:

>  parent.replaceChild(elem, currentElem)
    Все эти методы возвращают elem.

конфликтует с теорией, что первый элемент - всегда новый, а этот метод возвращает всегда старый (чуть выше в том же разделе):

>  parentElem.replaceChild(elem, currentElem)
    Среди детей parentElem заменяет currentElem на elem.

> Оба этих метода возвращают удаленный узел. 

Т.е. возвратится должен currentElem, а не elem, как написано в Итого. Потому и предложил переименование аргументов.

Вроде как здесь должен возвращаться currentElem.

**Comment by iliakan** [comment]
Fixed.
