### ISSUE TITLE
Сбит спиннер на восстановлении пароля

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#522]
Вот скрин: http://ilyakantor.ru/screen/2015-04-22_2254.png

История проблемы - был спиннер вместо текста.

Потом ты что-то сделал и теперь спиннер вместе с текстом. Имхо вместо было лучше.
И ещё он сейчас не на месте, не знаю, связано ли с твоими изменениями.

**Comment by tyv** [comment]
там старые кнопки, вставил правильные новые -- все ок

**Comment by iliakan** [comment]
Не мог бы грепнуть по коду, остались ли где-то ещё старые?
