### ISSUE TITLE
Куда лучше слать фидбек?

### ISSUE THREAD

**Issue by Isk1n** [iliakan/javascript-nodejs#528]
1) Какие замечания по содержимому учебника лучше оставлять в disqus-комментариях, а какие - здесь?
*Пример:* На этой странице https://learn.javascript.ru/focus-blur есть код с ошибкой
```html
<style>
.my::-webkit-input-placeholder, .my::-moz-placeholder {
  color: red;
  font-style: italic;
}
</style>
```
здесь нужно разделить правила, иначе работать не будет http://stackoverflow.com/a/2610741/2955384

2) Есть ли смысл дублировать в issues замечания из комментариев?
*Пример:* https://learn.javascript.ru/ajax-xmlhttprequest#comment-1082393218

**Comment by iliakan** [comment]
1) Fixed.
2) Ошибки в учебнике лучше писать сюда.
