### ISSUE TITLE
Не отображается результат исполнения примеров кода в главе testing

### ISSUE THREAD

**Issue by Alendorff** [iliakan/javascript-nodejs#531]
https://learn.javascript.ru/testing
Извините, другие главы не проверял, но в этой не работает предпросмотр результатов кода с plnkr. Если смотреть на самом plnkr, то там код работает.   
Использую Chrome Версия 42.0.2311.90 m

**Comment by iliakan** [comment]
Должно стать ок. Пишите, если ещё повториться.

**Comment by Alendorff** [comment]
Подтверждаю, стало Ок.
