### ISSUE TITLE
Ошибка: requestId

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#532]
Вот это чуть покрасивше мб сделать? http://ilyakantor.ru/screen/2015-04-25_1418.png

**Comment by Bezart** [comment]
сделай id красным цветом, таким же как и надпись "Ошибка на сервере"

**Comment by iliakan** [comment]
http://ilyakantor.ru/screen/2015-04-25_1452.png ?

**Comment by Bezart** [comment]
я имел ввиду значение красным, саму подпись можно вернуть

**Comment by iliakan** [comment]
может тебе быстрее будет чиркануть на макете чем писать много букв? :)

**Comment by Bezart** [comment]
это же просто поменять цвет у надписи, не думаю что будет быстрее...

**Comment by iliakan** [comment]
http://ilyakantor.ru/screen/2015-04-27_0842.png ?

**Comment by Bezart** [comment]
404 Not Found

**Comment by iliakan** [comment]
Два дня назад было 200 OK.
