### ISSUE TITLE
Карта учебника - нет ссылки назад

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#537]
Вот здесь: http://javascript.in/tutorial/map
Нет никакой ссылки "обратно на сайт". Как-то продумать бы.

**Comment by Bezart** [comment]
:) там море ссылок на сайт, это же карта... Если ты имеешь ввиду ссылка на главную учебника, то это другой вопрос. Напомни плиз, когда пользователь сюда попадает. На сколько я помню, карта обычно в попапе показывается, а эту страницу мы придумали для чего-то...

**Comment by iliakan** [comment]
Эту страницу мы придумали для открытия в новом окне. В ссылки на главную не будет.

**Comment by Bezart** [comment]
если в новом окне, то зачем тогда ссылка "назад"? предыдущее окно же открыто...

**Comment by iliakan** [comment]
Гм, ну вроде пока жалоб нет..
