### ISSUE TITLE
Респонсивность на странице курсов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#540]
На "внешних" страницах курсов (/courses в первую очередь) нужна респонсивность, чтобы страница целиком помещалась на экране мобильного, иначе гугл будет их пессимизировать при поиске с мобилок.

**Comment by Bezart** [comment]
Добавил в исходник на страницу ```Responsive logic / iPhone / Cources / Home``` http://take.ms/vtmy4 

При раскрытии аккордеона: http://take.ms/4Istg
При скроле: http://take.ms/uasm0

**Comment by Bezart** [comment]
http://take.ms/WHGc2 страница программы

**Comment by tyv** [comment]
@Bezart у тебя магически табы мз десктопа превращаются в аккордеон на мобильных дизайне;

я не очень понимаю как это вменяемо сверсатать без пляски в DOM в js, чего конечно не хочется делать

**Comment by Bezart** [comment]
Первоначально я хотел скрывать эти секции на смартфонах вообще, так как очень много текста, очень сомневаюсь что кто-то эти детали будет читать

@iliakan может все-таки скрывать?

**Comment by iliakan** [comment]
@Bezart люди вообще часто читают перед тем как платить деньги за что-либо. Надо дать им такую возможность. Наоборот текста мало сейчас, мало деталей, люди должны хорошо понимать, что именно их ждёт.

**Comment by Bezart** [comment]
Продукт который мы продаем не несет в себе никакого "срочного" характера. Если люди и будут покупать на мобилах, то уже определившись со своим решением и зная что конкретно они покупают. Это не спонтанная идея, которая, вдруг, возникла в кафешке.

Мобильную версию записи на курсы можно расценивать как решение для крайних случаев, например кто-то получил уведомление на почту о наборе в группу, находясь в отпуске, без доступа к ноутбуку.

В любом случае я уверен что:

1. Не нужно тратить много времени на реализацию мобильной записи без уверенности что это принесет конкретную выгоду

2. При реализации нужно учитывать конкретные случаи использования а не просто следовать модному тренду.

Как вариант решения, можно скрыть весь текст за дропдаунами и показывать первоначально только главный тунель:

Главная: http://monosnap.com/image/mzMxo0tBYdEVug767C7dJ4leJYkU4P
Страница курса: http://monosnap.com/image/r5SfxLQYzNL01OOI8uwohPK4aVkhKS

При клике показывать всю инфу "навалом" без дополнительных дропдаунов и табов.

**Comment by iliakan** [comment]
@Bezart здесь речь не о мобильной записи, а о мобильном чтении информации о курсе.

Зачем дропдаун, если вместо него можно сам текст пустить?

**Comment by tyv** [comment]
ну в этой идее что-то есть, мне нравится что страница получается очень лаконичной
но не нравится что прийдется все равно грузить килограмм всего, а отсечь мы не можем, так как только на клиенте определяем тип устройства.

давайте сделаем как нарисовано, в целом это кажется не плохим компромисом

**Comment by Bezart** [comment]
@iliakan дропдаун отличается тем, что он подчеркивает тот факт что это дополнительная "описательная" информация, тем кому интересно – нажмут и прочитают. Тем кому не интересно это может доставить неудобство, потому что мы вываливаем весь этот текст и заставляем сканировать страницу на факт чего-то важного.

В общем, предлагаю реализовать последний вариант и смотреть на данные.

**Comment by iliakan** [comment]
Под дропдауном в дизайне есть, да?

**Comment by Bezart** [comment]
да, все выводим как есть. акардион вместо табов убираем просто.

**Comment by iliakan** [comment]
Уточню - ты имеешь в виду - выводим аккордион вместо табов?

**Comment by Bezart** [comment]
у @tyv  были сомнения по поводу реализации первоначального аккордеона, который есть в макете. Новая логика не требует этого аккордеона, можно выводить содержимое табов потоком.

**Comment by iliakan** [comment]
У @tyv был вопрос в связи с тем, что табы - это сначала список заголовков, а потом список текста в вёрстке.
А аккордеон - это заголовок-текст-заголовок-текст. 

То есть, HTML-разметку нужно менять, чтобы аккордеон из табов сделать.
В новой логике то же самое, @Bezart?

То есть, на телефоне заголовок-текст-заголовок-текст... ?

**Comment by Bezart** [comment]
Если есть решение без переделки разметки, я только за. Если нет, то да, заголовок-текст

**Comment by iliakan** [comment]
@tyv ну, раз такое дело, буду js'ом переколбашивать разметку при ресайзе.

**Comment by tyv** [comment]
@iliakan не стоит, я давай продублируем заголовки и спрячем их на десктопах

**Comment by iliakan** [comment]
ok

**Comment by tyv** [comment]
@Bezart "мнения профессионалов" нет в responsive

**Comment by Bezart** [comment]
@tyv Ок, сделаю

**Comment by tyv** [comment]
@Bezart хотя по-кмолчанию выглядит ок https://yadi.sk/i/vvBYa1EHgnCZP

**Comment by Bezart** [comment]
Да, думаю ничего выдумывать не нужно. Единственное, можно правый марджин у юзерпика уменьшить на 50% для мобил
