### ISSUE TITLE
null + undefined; //NaN

### ISSUE THREAD

**Issue by yurko** [iliakan/javascript-nodejs#541]
Что выведет этот скрипт?

"use strict";
a = null + undefined;
alert(a);

Варианты: null; undefined; NaN; В коде ошибка.
Правильным ответом отмечено "В коде ошибка.".  В консоли Chrome - NaN.

**Comment by FFxSquall** [comment]
@yurko в консоле хрома, не включен use strict. Что бы проверить данный пример нужно обернуть это в функцию вот так
```javascript
(function()
{
    "use strict";
a = null + undefined;
alert(a);
}());

**Comment by yurko** [comment]
спасибо, понял, в strict переменная a должна быть объявлена
