### ISSUE TITLE
не всегда верно

### ISSUE THREAD

**Issue by gualex** [iliakan/javascript-nodejs#548]
http://learn.javascript.ru/traversing-dom
`var elem = document.createElement("div");`

Всегда верно:
`elem.childNodes[elem.childNodes.length - 1] === elem.lastChild;`

не всегда верно

**Comment by iliakan** [comment]
Вы имеете в виду случай с пустым узлом? Просьба более подробно описывать предлагаемые изменения. Спасибо.

**Comment by gualex** [comment]
Случай с элементов без дочерних узлов.
можно заменить

Всегда верно:
=>
При наличии у элемента дочерних узлов всегда верно:
