### ISSUE TITLE
polyfill-closest css <=> selector

### ISSUE THREAD

**Issue by gualex** [iliakan/javascript-nodejs#549]
http://learn.javascript.ru/task/polyfill-closest
В решении нужно использовать либо css, либо selector.

**Comment by iliakan** [comment]
Репорт непонятен.

**Comment by gualex** [comment]
(function() {
  // проверяем поддержку
  if (!Element.prototype.closest) {
    // реализуем
    Element.prototype.closest = function(**css**) {
      var node = this;
      while (node) {
        if (node.matches(**selector**)) return node;
        else node = node.parentElement;
      }
      return null;
    };
  }
})();

**Comment by iliakan** [comment]
Спасибо, исправлено!
