### ISSUE TITLE
Страница группы

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#553]
1) Убрать ссылку на стр группы если не подтвержден
2) Если подтвержден то состояние в посл колонке
3) Добавить расписание.

**Comment by iliakan** [comment]
Если курс завершён, то ссылка на возможность оставить отзыв.

**Comment by Bezart** [comment]
http://monosnap.com/image/djJKlTSVVBBnCYmMmrCPv61hr73pqZ

**Comment by Bezart** [comment]
последний вариант http://take.ms/up83O

**Comment by iliakan** [comment]
@tyv обнови плиз в статике.

**Comment by iliakan** [comment]
@tyv это готово, да?

**Comment by tyv** [comment]
да, готово
