### ISSUE TITLE
Кнопки поделиться

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#561]
http://javascript.in/nodejs-screencast - кнопок типа "поделиться" тут по дизайну нет, а по смыслу они очень даже востребованы.

**Comment by Bezart** [comment]
http://monosnap.com/image/7ZRSNqacKw8O1gfc174AXSS9LQK848

**Comment by iliakan** [comment]
@tyv сделай плиз подсветку при наведении - у нас их две стандартных: осветляющая и затемняющая, какую-нибудь из этих.
