### ISSUE TITLE
Форма для отзывов

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#570]
[09/05/2015 12:03:52] Ilya Kantor: [Avatar]  ФИО  Страна, город  Дата
Профили в соц сетях, ссылки...

Общая оценка от 1 до 10
Порекомендовал бы?

Отзыв
[09/05/2015 12:08:18] Ilya Kantor: [Расшарить отзыв]

**Comment by Bezart** [comment]
Форма: http://monosnap.com/image/29L8X63v3Jb0r01xPy5xmELQrsmRPb
Варианты оценки (меняется при ховере, фиксируется при клике): http://take.ms/T87UF
Успешная отправка / шаринг: http://take.ms/XuMwf

**Comment by Bezart** [comment]
Обновил: http://take.ms/Mjlv7 
Если чекбокс "Публичный профиль" отключен, ссылку на профиль не показываем

**Comment by iliakan** [comment]
Может, так `Ссылка на ваш github или профиль в соц сети`. 
И обосновать, что люди склонны учитывать только те отзывы, об авторах которых они могут узнать подробнее.

**Comment by Bezart** [comment]
То что ты пытаешься обосновать, это наша проблема, пользователя это не интересует. Ему нет дела, поверит кто-то что это реальный человек или нет, он забудет об отзыве как только закроет форму.

Во время заполнения отзыва, ему нужно дать понять где эта ссылка будет использоваться, поэтому предлагаю добавить подпись "Будет использоваться только как ссылка в вашем отзыве"

Все остальное предлагаю оставить как есть.

**Comment by iliakan** [comment]
Хорошо бы его как-то сагитировать что-то написать там. Для отзыва это важно.

**Comment by Bezart** [comment]
Ну наши проблемы его не сагитируют. Можно перефразировать "Было бы здорово если бы мы могли сослаться на вас в соц. сетях. Эта ссылка будет использоваться только внутри вашего отзыва у нас на сайте"

**Comment by iliakan** [comment]
Ок, давай как-то так.

**Comment by iliakan** [comment]
Чел должен видеть, что нам нужна эта ссылка иначе ему ваще влом ;) А так если доволен и благодарен, то  заполнит.

**Comment by Bezart** [comment]
Добавил в макет http://take.ms/72cuR

**Comment by tyv** [comment]
@Bezart  Там очередной шрифт используется для звездочек, я не вижу его на fontello

**Comment by iliakan** [comment]
@tyv, если тебе что-то нужно от @Bezart , обязательно переводи таск на него. Он очень редко, к сожалению, смотрит "просто вопросы".

**Comment by iliakan** [comment]
@Bezart чтобы просто вопросы смотреть - нужно настроить уведомления о них.

**Comment by tyv** [comment]
ну я взял обычный utf симфол звездочек, он выглядит так же

**Comment by Bezart** [comment]
да, норм с utf символом, тот шрифт что сейчас стоит подхватился автоматом при вставке

**Comment by iliakan** [comment]
@Bezart с учётом того, что почти все поля юзера "о себе" уже предзаполнены, может быть сверху показывать отзыв, а их как-то отделить снизу.

Чтобы юзер сначала написал по делу, а потом уже думал остальное, ему и править обычно ничего не надо в "о себе", по идее.

**Comment by Bezart** [comment]
По первому пункту — я бы не хотел менять ничего. Если все предзаполнено, человек просто проскролит вниз, никакого неудобства это не создаст. Я бы хотел иметь поле самого отзыва близко к самой кнопке "Отправить"

По второму пункту, думаю что сейчас все хорошо. Если человек готов оставить это фото под отзывом, мало вероятно чтобы он по какой-то причине возражал оставить фото для профиля. Нам выгоднее, чтобы у людей были юзерпики, так как это позитивно влияет на популярность ресурса. Если же пользователь будет возражать, он может легко поменять юзерпик в профиле...
