### ISSUE TITLE
2 ошибки в учебнике

### ISSUE THREAD

**Issue by drDocument** [iliakan/javascript-nodejs#574]
Илья, поправьте 2 ошибки в учебнике
http://learn.javascript.ru/with

Первая -- чисто техническая, по семантике языка
Цитата:
При использовании with, как и во вложенных функциях — переменная изменяется в той области, где была найдена.
Это утверждение не верно. На самом деле, будет создана новая переменная, в том окружении, из которого производится присваивание.

Вторая -- в большей степени формальная

Там пишется, что, якобы, конструкция with является устаревшей. Это утверждение делается, насколько я понял, на основании того, что она не работает в режиме use strict. Однако, эти 2 понятия абсолютно ортогональны. Код, задаваемый директивой use strict, можно считать семантическим подмножеством JS, не более того. Во избежании превратных и неоднозначных толкований, достаточно упоминания, что данная конструкция не работает в данном режиме.

**Comment by iliakan** [comment]
1) Это не так.
2) Конструкция with устарела, вообще, код, не рабочий вне use strict устарел и не рекомендуется, в связи с implicit use strict в ES6 модулях.
