### ISSUE TITLE
Мелкие косячки и пучок опечаток.

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#579]
1 ) Опечатки:

[POST с multipart/form-data](https://learn.javascript.ru/xhr-forms#post-%D1%81-multipart-form-data)

>  Пример кода для пересылкЕ того же запроса...

[Другие кодировки](https://learn.javascript.ru/xhr-forms#%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8)

>  Поэтому просто для обмена данными JS ↔ сервер, без всяких формА...

[Контроль безопасности](https://learn.javascript.ru/xhr-crossdomain#%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8C-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8)

> «Непростыми» считаются все остальные, например, запрос с методом PUT или с заголовком Authorization БУДЕТ НЕ ПОДХОДИТ под ограничения выше.

там же

> Поэтому при посылкОЙ «непростых» запросов

[Файлы и формы](https://learn.javascript.ru/xhr-onprogress#%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-%D0%B8-%D1%84%D0%BE%D1%80%D0%BC%D1%8B)

> Выше мы использовали xhr.send(file) для посылки файл пересылается в теле запроса. (То ли запятой нет, то ли еще что...)

[Запросы GET и POST](https://learn.javascript.ru/ajax-iframe#%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D1%8B-get-%D0%B8-post)

>  Его изменение доступно между ифреймами с разных доменов и не ПЕРЕводит к перезагрузке страницы.

[Итого](https://learn.javascript.ru/events-change#%D0%B8%D1%82%D0%BE%D0%B3%D0%BE)

> В них можно отменить действие браузера, и тогда вставкЕ/копирования/удаления не произойдёт.

****************
2 )  [Проверка](https://learn.javascript.ru/ajax-nodejs) 

> Server running on port 8080  

У меня без этого запускается(пустая командная строка в винде), то ли инфа устарела, то ли из-за конфигурации ПО.

Там же косяк с [Демо](https://learn.javascript.ru/ajax-nodejs#%D0%B4%D0%B5%D0%BC%D0%BE): сервер js.cx возвращает 404.

3 ) [Основы XMLHttpRequest](https://learn.javascript.ru/ajax-xmlhttprequest). 
В примерах отсутствует подсказка для кнопки "скачать проект", хотя есть подсказка "открыть в отдельном окне".

4 ) [Обработка ответа, JSONP](https://learn.javascript.ru/ajax-jsonp#%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0-jsonp)  

> Cервер кодирует данные в JSON и оборачивает их в функцию…

Как бы это не совсем корректно, вводит в заблуждение. Скорее оборачивает в вызов функции(если можно так выразиться), а не в саму функцию (сама-то функция на клиенте).

5 ) [Методы focus/blur](https://learn.javascript.ru/focus-blur#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-focus-blur)

В примере не возвращает фокус в FF.

6 ) [Плейсхолдер](https://learn.javascript.ru/focus-blur#%D0%BF%D0%BB%D0%B5%D0%B9%D1%81%D1%85%D0%BE%D0%BB%D0%B4%D0%B5%D1%80)

> Стилизуется везде, кроме IE

В IE с 10-ки стилизуется через :-ms-input-placeholder .

7 ) [Событие submit](https://learn.javascript.ru/forms-submit#%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-submit)

Это скорее к опечаткам, в примере остался рудимент в виде &lt;/button> .

*************
Засим прекращаю регулярное занудство в связи с окончаниeм курсов. Также рекомендую отдохнуть.

**Comment by iliakan** [comment]
;) Спасибо, посмотрю поправлю. Покой нам только снится.

**Comment by iliakan** [comment]
Пункт 1 готов.

**Comment by discodanser** [comment]
Странно, что некоторые вещи из закрытых кейсов сразу попадают в продакшн, как нынешние опечатки, а другие, зачастую более важные - нет. Как, например, [два противоречащих друг другу параграфа в одном разделе (пункт 5)](https://github.com/iliakan/javascript-nodejs/issues/519).

**Comment by iliakan** [comment]
Можно уточнить, что же, всё-таки, неправильно там в пункте 5?

**Comment by iliakan** [comment]
Какие конкретно параграфы мне внимательнее перечитать?

**Comment by iliakan** [comment]
Всё, что здесь было, исправлено, спасибо.
