### ISSUE TITLE
SVG с флагами

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#581]
У страны, которая у юзера, ты флажок нарисовал.

Не мог бы сделать SVG для флагов: Белоруссия США Германия Украина Израиль Россия.

@tyv пытался экспортить, но у него тень не экспортнулась, что с ней делаем?

**Comment by Bezart** [comment]
Привет, касательно флагов там тень через CSS можно сделать я думаю. Что касается самих флагов, их можно взять из этого репозитория: http://lipis.github.io/flag-icon-css/

Конкретно страны которые нужны:
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/il.svg
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/de.svg
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/us.svg
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/ru.svg
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/ua.svg
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/by.svg

**Comment by iliakan** [comment]
Положил в flags.
