### ISSUE TITLE
"И в третий раз закинул старик невод..."

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#582]
Раздел "Добавление и удаление узлов", [Итого](https://learn.javascript.ru/modifying-document#%D0%B8%D1%82%D0%BE%D0%B3%D0%BE):

> ....
parent.replaceChild(elem, currentElem)

    Все эти методы возвращают elem.

Это идет в противоречии с параграфом выше [Удаление узлов: removeChild] (https://learn.javascript.ru/modifying-document#%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%83%D0%B7%D0%BB%D0%BE%D0%B2-removechild)

>  parentElem.replaceChild(elem, currentElem)
    Среди детей parentElem заменяет currentElem на elem.

    Оба этих метода возвращают удаленный узел.

Проблема в следующем:

 в первом случае говорится, что возвращается первый аргумент (elem), а во втором - что второй (currentElem).

**Comment by iliakan** [comment]
Thanks, fixed.
