### ISSUE TITLE
Еще  дополнение  по старенькому кейсу раздела "Две стадии преобразования".

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#583]
Был такой пункт про в разделе ["Две стадии преобразования"](https://learn.javascript.ru/object-conversion#%D0%B4%D0%B2%D0%B5-%D1%81%D1%82%D0%B0%D0%B4%D0%B8%D0%B8-%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) - "Исключение: Date". 

Описание было поправлено, а вот пример показался неинтересным:

> // бинарный плюс, строчное преобразование
alert( new Date + "" ); // "строка даты"

Потому что сложение со строкой   (+ "")   и так обычно приводит к строке, для этого никакое исключение не нужно. Правда, придумать что-то другое тоже нелегко, на ум приходит только:

alert( new Date + +"" )   // остается надеется, что унарный плюс не запутает читателя 

или

alert( new Date + 333333 )   // просто много цифр, чтоб было заметно, куда они  приклеились.

**Comment by iliakan** [comment]
Да там как раз нюанс важен, что обычно `+` как раз использует числовое преобразование.
```js
alert( { valueOf: function() { return 5 } } + ""  )  => 5
```
