### ISSUE TITLE
Курсы отзывы: добавить Занятость?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#587]
Мб добавить это поле в отзывы? Или что-то типа такого, чтобы чел мог указать "Студент" или "PHP-разработчик" или "Старший Манагер Рога и Копыта.com"? Будет некрасиво - скроем.

**Comment by Bezart** [comment]
Добавил в отзыв http://take.ms/T307s
И в форму http://take.ms/ILtuM

**Comment by iliakan** [comment]
Если в макетах Sketch оно есть - закрой плиз таск.
