### ISSUE TITLE
Курсы: "мнение опытных разработчиков"

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#588]
As discussed in Skype добавишь в диз?

**Comment by iliakan** [comment]
Может, блок на главной курсов заменить на такой, как обсуждали? 

Отзывы ведь текущие в старом формате. Это, в частности, значит, что люди - не юзеры сайта, сслыку на профиль не дашь. Оценки в большинстве нету.

**Comment by iliakan** [comment]
Skype: решили пока без отзывов, они на старой страницы курсов будут.

**Comment by Bezart** [comment]
На будущее есть блок: http://take.ms/W4p2o
