### ISSUE TITLE
Подзаголовок

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#591]
Вот здесь одинаковым шрифтом обе строки?

Это выходит, по сути, заголовок и подзаголовок, но они одним шрифтом?

**Comment by Bezart** [comment]
Я думал что это будет один заголовок, просто название курса всегда новой строкой что бы легче читать было

**Comment by iliakan** [comment]
@tyv, это по смыслу один заголовок, но разбит на 2 строки. Как оформить? h1 + br внутри?

**Comment by iliakan** [comment]
http://monosnap.com/image/Wc3bJuJfyBbXwK73RPCG7yrkZC2Q5w
http://ilyakantor.ru/screen/2015-05-16_1024.png

**Comment by tyv** [comment]
да, br норм

**Comment by iliakan** [comment]
Пишу тут чтоб не забыть http://javascript.in/courses/groups/js-1/signup - поправить расстояние грамотно.
