### ISSUE TITLE
Курсы - анкета участника

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#592]
Сейчас на курсе при записи я предлагаю заполнить анкету участника, с общей информацией о человеке. Всем. Смотрю, кто записался, пожелания.

Видимо, в сайт интегрировать имеет смысл в регистрацию? И тут уж всех заставлять её проходить, включая 1го-единственного участника.

**Comment by iliakan** [comment]
Данные анкеты не публикуются, кроме как по желанию участника. Он их может использовать для отзыва (автозаполняются поля).

**Comment by Bezart** [comment]
http://take.ms/B2bZM

**Comment by iliakan** [comment]
Боевой шаблон уже есть.
