### ISSUE TITLE
По поводу закрытого кейса #583

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#593]
[Еще дополнение по старенькому кейсу раздела "Две стадии преобразования". #583] (https://github.com/iliakan/javascript-nodejs/issues/583#issuecomment-102579756)

Возможно, какое-то недопонимание возникло. 

> Да там как раз нюанс важен, что обычно + как раз использует числовое преобразование.
alert( { valueOf: function() { return 5 } } + ""  )  => 5

Действительно, получается "5", только это строка:

> typeof ({ valueOf: function() { return 5 } } + "")  // string

Проблема не в бинарном плюсе, а в присутствии пустой строки "", которая превращает в строку любое другое слагаемое, будь-то исключение или хоть что еще.

**Comment by iliakan** [comment]
Поменял код на такой:
```js
// бинарный плюс для даты toString, для остальных объектов valueOf
alert( new Date + "" ); // "строка даты"
```
Должно стать понятнее, в чём именно состоит исключение.

**Comment by discodanser** [comment]
Ну, на самом деле пример понятнее не стал, про исключение там тестом и так вроде нормально объяснено, а глядя на пример каждый увидит, что там будет строка в любом случае (из-за ""). Ну да ладно, это не ошибка, просто непоказательный пример.
