### ISSUE TITLE
Анкета для курсов - Dropbox

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#596]
Для курсов по Node.JS требуется Dropbox.

Аккаунт где-то надо указывать, в анкете сверху?

**Comment by Bezart** [comment]
Так он должен быть по идее привязан к email'у.. если дропбокс на другом имейле, нужно будет решать в индивидуальном порядке. Вводить дополнительное поле для 2-го имейла не вижу смысла

**Comment by iliakan** [comment]
Да, точно. Проблемы не существует ;)
