### ISSUE TITLE
Выбор страны

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#597]
Есть два предложения по выводу страны.

Первое - такого рода диз:
http://ilyakantor.ru/screen/2015-05-16_2235.png
То есть, есть селект со всеми странами, а под ним - ссылки на самые частые.

Второе - один селект со всеми странами, изначально выбрана страна, угаданная по IP. Обычно страна угадывается верно.
Этот вариант сейчас реализован.

**Comment by Bezart** [comment]
Мне нравится второй вариант — определение по ip. Как правило, этого с головой хватает. Дополнительно, вверху списка можно показывать часто используемые страны http://take.ms/AC1K0
