### ISSUE TITLE
Cookies + History

### ISSUE THREAD

**Issue by Alexey-v-Ivanov** [iliakan/javascript-nodejs#599]
На сайте learn.javascript.ru :
Переход с главной страницы в  "карту учебника" (в модальное окно) не записывается в history, и соответственно, нельзя вернуться обратно на главную с помощью кнопки "назад" (или бэкспейса). Кроме того, карту нельзя добавить в "избранное". С точки зрения пользователя, это неудобно.

**Comment by iliakan** [comment]
В закладки добавлять теперь можно. 
Кнопка назад не работает, т.к. это модальное окно, было бы неправильно.
