### ISSUE TITLE
Горизонтальная прокрутка в учебнике

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#600]
При авторизации под длинным именем юзера в учебнике появляется горизонтальная прокрутка.

http://ilyakantor.ru/screen/2015-05-18_2338.swf

**Comment by iliakan** [comment]
@bezart, как лучше поступить в этом случае?
1) На узком экране делаем имя не 200px max, а 100px max.
2) Ужимаем какие-то ещё элементы, чтобы потенциально более длинное имя влезло.

**Comment by iliakan** [comment]
P.S. Текущий респонсив (начало уменьшений) у нас идёт от `1100px`.

**Comment by tyv** [comment]
сделал красиво благодаря флексбоксам
