### ISSUE TITLE
Профиль: Сделать описание курса ссылкой?

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#613]
Вот это мб объединить, сделать название курса ссылкой?
http://ilyakantor.ru/screen/2015-05-25_1823.png

**Comment by Bezart** [comment]
Я думал об этом первоначально, но решил сделать отдельно ссылками, так как у нас их несколько: инструкции, материалы, описание. Если будет ссылка на названии + инструкции и материалы, будет не очень понятно что находится за ссылкой.

**Comment by iliakan** [comment]
Вообще, эта ссылка самая ненужная. Поэтому я предложил объединить, чтобы она не занимала место.

**Comment by Bezart** [comment]
Как раз тогда она станет самой заметной и большой, поэтому предлагаю оставить как есть.

**Comment by iliakan** [comment]
Может сделать типа [->] у заголовка маленькое?

**Comment by Bezart** [comment]
Не вижу смысла ребусы создавать. Можно ссылку вниз передвинуть, то есть сделать последней
