### ISSUE TITLE
Флаг в анкете

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#615]
Pull с меня плиз.

Вот здесь флаг http://ilyakantor.ru/screen/2015-05-25_1929.png
1) Стили поправь плиз, чтобы показывался нормально справа от селекта.
2) Тут вокруг флага рамка криво выглядит - это флаг настолько кривой или можно что-то сделать?

**Comment by tyv** [comment]
а зачем он там вообще?

**Comment by iliakan** [comment]
Не нужен там флаг? :)

**Comment by tyv** [comment]
ну он вообще непонятно зачем

**Comment by Bezart** [comment]
Здесь флаг не нужен, юзер и так его знает. Он нужен только в самом отзыве на странице чтобы подчеркнуть что люди из разных стран.
