### ISSUE TITLE
Курсы: страница материалов без материалов.

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#618]
Как будет выглядеть страница материалов, когда ничего нет?

Нужна надпись типа "Материалов пока нет, будут доступны позже".

Сейчас так - может, ок? http://ilyakantor.ru/screen/2015-05-26_1256.png

**Comment by Bezart** [comment]
Зеленый цвет уведомлений у нас используется для обозначения успешного завершения какого-либо действия. Здесь же нужен синий, информационный блок. Касательно логики — норм. Надпись можно поправить, чтобы объяснить что материалы будут постоянно обновляться а не выкладываться за один раз: "Материалов пока нет, будут наполняться по мере прохождения курсов"

**Comment by iliakan** [comment]
Ok, сделал синим. Это только до начала курса видно.
