### ISSUE TITLE
Отзыв: ошибки

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#620]
Эти поля обязательны.
Как будут выглядеть ошибки, если оценки или текста нет?

http://ilyakantor.ru/screen/2015-05-26_2010.png
Стандартное красненькое внизу? С какими отступами? Не добавишь в макет?

**Comment by Bezart** [comment]
Стандартный стиль со стандартными отступами http://take.ms/8jWtM это есть в макете.

**Comment by iliakan** [comment]
И под звёздочками тоже?

**Comment by Bezart** [comment]
Да, такой же шрифт, такой же отступ. Сами звездочки не трогаем только
