### ISSUE TITLE
Ошибка в тексте учебника https://learn.javascript.ru/datetime#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%B4%D0%B0%D1%82%D1%8B

### ISSUE THREAD

**Issue by konstantin-agafonov** [iliakan/javascript-nodejs#626]
Текст:

"Для примера возьмем две функции, которые бегают по массиву:

function walkIn(arr) {
  for (var key in arr) arr[i]++
}

function walkLength(arr) {
  for (var i = 0; i < arr.length; i++) arr[i]++;
}

Чтобы померять, какая из них быстрее, нельзя запустить один раз walkIn, один раз walkLength и замерить разницу. Одноразовый запуск ненадежен, любая мини-помеха исказит результат.

Для правильного бенчмаркинга функция запускается много раз, чтобы сам тест занял существенное время. Это сведет влияние помех к минимуму. Сложную функцию можно запускать 100 раз, простую — 1000 раз…

Померяем, какая из функций округления быстрее:"

Здесь слово "округления" лишнее.

**Comment by iliakan** [comment]
Thanks fixed.
