### ISSUE TITLE
Непубличный отзыв

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#629]
Если отзыв на курс непубличный, нужно поправить макет, видимо как-то отразить на нём это?

Как минимум, убрать кнопки шаринга, мб сообщение о непубличности?

P.S. Имеется в виду макет, где один отзыв одинокий.

**Comment by iliakan** [comment]
Ещё вопрос - если чел НЕ рекомендует курсы - как это отобразить в дизайне?

**Comment by Bezart** [comment]
Кнопки шаринга убираем, если чел не рекомендуем, то просто не показываем зеленую надпись "Рекомендует курс..."

В сообщении об успешном сохранении отзыва "Ваш отзыв успешно сохранен. При желании, вы можете поделиться им в соц сетях" меняем текст на "Ваш отзыв успешно сохранен. Он будет виден только нам" или что-то в таком духе

**Comment by iliakan** [comment]
@iliakan публичный отзыв и редактирование отзыва todo
