### ISSUE TITLE
Вход в систему на отдельной странице

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#630]
Сейчас выглядит так: http://ilyakantor.ru/screen/2015-05-30_0958.png (просто вставил содержимое модального на странице)

Адаптируй, пожалуйста, в плане дизайна.

Может быть, вообще голое окно "вход в сайт" с этой формой?

Типичный случай использования - это когда чел переходит по ссылке на страницу, доступ к которой требует авторизации. В этом случае страница перенаправляет на такую вот авторизацию.

**Comment by Bezart** [comment]
http://monosnap.com/image/8Kxz5nXywcFjR4a5lqBBDZfvW8utV2

**Comment by Bezart** [comment]
http://monosnap.com/image/BgqaAXtYLAlP5LiEAvefkYhu9oIDNC второй вариант (первый мне нравится больше)

**Comment by iliakan** [comment]
Первый вариант значит.

@tyv: я запушил, url: http://javascript.in/auth/login

В client-side шаблонах авторизации (`auth/templates`) `inModal`, если в модальном окне.
