### ISSUE TITLE
Курсы: сертификат

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#633]
Ссылка на скачивание сертификата после окончания группы - там же где отзыв?

**Comment by Bezart** [comment]
1. Нужно его первоначально письмом прислать
2. Оставить ссылку на сертификат на странице профиля в разделе "Курсы" http://take.ms/C3uQk

**Comment by iliakan** [comment]
Сертификат нужен мало кому. Я упомяну о нём в письме по завершении курса.
Ок, ссылка понятно.
