### ISSUE TITLE
Неточность/ошибка в тексте

### ISSUE THREAD

**Issue by teodorovych** [iliakan/javascript-nodejs#636]
В примере кода на странице https://learn.javascript.ru/event-delegation#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D0%B1%D0%B0-%D0%B3%D1%83%D0%B0
после слов "Код будет таким:" пропущено прсвоение переменной "table"
Из-за этого может возникнуть ложное мнение, что событие, можно назначить на таблицу как клас объектов (на объект обозначеный тегом table).

**Comment by iliakan** [comment]
Почитал текст - мне кажется происходящее очевидным, если кому-то непонятен момент - напишите в этой issue.
