### ISSUE TITLE
Сертификат

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#639]
Как тебе? 
http://ilyakantor.ru/screen/2015-05-31_0959.png

PDF-бланк в дропбоксе ссылка ушла почтой.

**Comment by Bezart** [comment]
Я бы поменял шрифт в двух местах:
- JavaScript.ru — на OpenSans Bold
- Имя – на стандартный шрифт (calibri или что там у тебя сейчас)

Не нужно множить стили и начертания, иначе сертификат выглядит как "игра со шрифтами". Все остальное ок.

**Comment by iliakan** [comment]
Покажи
