### ISSUE TITLE
Совместное использование async + defer

### ISSUE THREAD

**Issue by karavaev-evgeniy** [iliakan/javascript-nodejs#641]
В учебнике сказано (https://learn.javascript.ru/external-script):
![screenshot_2](https://cloud.githubusercontent.com/assets/6982951/7902243/9091459e-07d4-11e5-944b-915953833bb9.png)

А может смысл есть? Если нам нужно асинхронно загрузить скрипт и выполнить его после загрузки, то ставим async, но это не сработает для IE9-. В этом случае ставим оба атрибута, нормальные браузеры отработают по async, а IE9- по defer, сохранив при этом хотя бы асинхронность.

Есть ли в этом смысл? Если да, то может стоит написать об этом в учебнике?

**Comment by iliakan** [comment]
Fixed.
