### ISSUE TITLE
Курсы: набор в текущие группы

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#646]
Сейчас окончание набора в группы выглядит так: http://ilyakantor.ru/screen/2015-06-05_1353.png

Может, показывать там недавние группы и когда закрылся набор?

Чтобы было видно, что активность есть, и чтобы люди примерно представляли, сколько времени проходит от начала набора до конца.

**Comment by Bezart** [comment]
1. На картинке нужен input для email'а
2. Мне кажется лучше показывать предположительное начало набора в след группу, так как это одновременно покажет активность и предоставит полезную информацию, причем не накладывает особых обязательств на тебя. Например:
"Набор в группу от 2 июня закрыт. Следующий набор откроется предположительно в начале июля"

**Comment by iliakan** [comment]
1) на картинке сейчас если юзер залогинен - показывается только кнопка
2) может написать, когда он именно закрыт?

Как-то оформлять это визуально? мб нарисуешь?

**Comment by iliakan** [comment]
Тут важный момент есть: люди должны понимать, что набор заканчивается за несколько дней. Чтобы без неожиданностей, а то мне пишут письма "ой не успел опоздал а кто ж знал а".

Если я об этом просто напишу - могут подумать что "в рекламных целях нагнетаю".
А если я напишу, что группа тогда-то запись завершилась тогда-то - то это наглядно говорит и о частоте групп и о времени на набор.

**Comment by Bezart** [comment]
По этой логике нужно показывать дату начала набора и дату конца набора, дату начала занятий и дату начала следующего набора, что добавляет сложности. 

Хотелось бы знать какую задачу мы решаем. Нужно мотивировать людей записываться быстрее как только они увидят набор? Но ты сам говоришь, что сейчас все быстро проходит. Чтобы избавится от писем неуспевших? По-моему это не аргумент. В общем, если ты опишешь конкретно проблему, будет хорошо.

**Comment by iliakan** [comment]
Задача - чтобы люди видели и активность по группам и могли сориентироваться, в какое время записаться, по объективным данным. 
Именно с этой целью я и предлагаю дополнить информацию.
