### ISSUE TITLE
Скринкаст по Node.JS - когда курс открыт

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#647]
Если открыт курс, то на странице скринкаста, видимо, имеет смысл сразу перебрасывать на него? Заимплементил переброс в угловой ссылке, мб как-то ещё его учесть?

А если группы закрыты - то упомянуть мб о /courses/nodejs где-то?

**Comment by Bezart** [comment]
То как сейчас работает – норм. Когда группы закрыты, показываем стандартную форму в попапе. 

На счет ниэнего блока, предлагаю менять его на что-нибудь такое http://take.ms/zqXHR

**Comment by iliakan** [comment]
@Bezart а если только одна группа открыта, то только один квадратик в 50% ширины с ней или она растягивается на 100% ?

**Comment by Bezart** [comment]
один 50%

**Comment by iliakan** [comment]
up

**Comment by tyv** [comment]
я не понял что нужно сделать

**Comment by iliakan** [comment]
плашка внизу видишь?

**Comment by iliakan** [comment]
Апдейт дизайна (pull с меня осторожно, я пока старый вариант интегрировал - твои переменные потёр)
http://monosnap.com/image/3KKv9ZrFL1ohe4R1dwqdEqiUtmylaK

Изменение - может быть несколько групп, но "Узнать программу" - одна кнопка.

**Comment by iliakan** [comment]
@tyv пока не надо это делать.
