### ISSUE TITLE
Пара опечаток, неработающие в FF примеры

### ISSUE THREAD

**Issue by discodanser** [iliakan/javascript-nodejs#648]
1 ) Опечатка (в каментах нашли) в [Стиль в зависимости от хозяина](https://learn.javascript.ru/css-scoping#%D1%81%D1%82%D0%B8%D0%BB%D1%8C-%D0%B2-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8-%D0%BE%D1%82-%D1%85%D0%BE%D0%B7%D1%8F%D0%B8%D0%BD%D0%B0):

>  Хозяин :host выбирается В именно в контексте Shadow DOM.

***********

2 ) Странное предложение в Импорты [Зачем?](https://learn.javascript.ru/link-import#%D0%B7%D0%B0%D1%87%D0%B5%D0%BC):

>  Иначе говоря, \<link rel="import"\> — это аналог \<script\>, но для подключения не только скриптов, а документов, с шаблонами, библиотеками, веб-компонентами и т.п.

Может имелось ввиду : "но только для подключения не скриптов,"

***************
3 ) [Переход внутрь ифрейма](https://learn.javascript.ru/iframes#%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4-%D0%B2%D0%BD%D1%83%D1%82%D1%80%D1%8C-%D0%B8%D1%84%D1%80%D0%B5%D0%B9%D0%BC%D0%B0):

Пример не работает в FF (и в учебнике, и в планкере). Т.е. на отжатии кнопки видно проскакивающий зеленый фон, но не более. Если сделать задержку на срабатывание скрипта - работает. Чудит мозилла.

До кучи - люди в каментах жалуются на корявость фразы из этого раздела: “Браузер может не считать документ в ифрейме пришедшим с другого же домена.”
****************
4)  [Исключение: запись в location](https://learn.javascript.ru/same-origin-policy#%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%B2-location):

Опять неработающий в FF пример (не происходит перенаправления). Но на этот раз пример не работает только в учебнике. Если вытащить в отдельный HTML (или в том же планкере) - все норм. 
***********
5 ) [Показ с отключённым функционалом](https://learn.javascript.ru/clickjacking#%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7-%D1%81-%D0%BE%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D1%91%D0%BD%D0%BD%D1%8B%D0%BC-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D0%BE%D0%BC):

>  position: absolute;

Может лучше fixed?  При абсолютном позиционировании и наличии полос прокрутки защитный div будет уезжать с прокруткой. Это заметно, если ему фон дать.

Ну и для ссылки лучше добавить (чтоб тянулась на весь размер div): 

>  display: block;
    height: 100%;

**Comment by iliakan** [comment]
Всё, кроме 5) сделал.
Насчёт 5) не уверен, что происходит плохого при `absolute`? Защитный `div` не имеет фона, он прозрачный.

По тексту учебника, пожалуйста, пишите в репозитарии где текст, я как раз туда коммичу, это удобнее, сообщения видны: https://github.com/iliakan/javascript-tutorial
