### ISSUE TITLE
Блок типа "у нас обучались"

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#649]
Что-то аналогичное http://javascript.ru/mk#uchastniki-proshlyh-meropriyatiy

**Comment by Bezart** [comment]
ок, сегодня закину макет

**Comment by iliakan** [comment]
Количество логотипов можно увеличивать и уменьшать.

**Comment by iliakan** [comment]
Добавь плиз на страницу курсов главную, http://monosnap.com/image/ZjRC1seO5OnwQ5gn61dBzs1aU8iAj5, всего 16 логотипов, сетка строго 4x4 (сами картинки я вставлю, любые `img` туда).

**Comment by iliakan** [comment]
Все ячейки одинакового размера, выравнивание по центру.

**Comment by iliakan** [comment]
Слишком большие лого, переделать на слайдер.

**Comment by Bezart** [comment]
Вариант слайдера: http://take.ms/olYMs
Движение по кругу.

Еще сделал черно-белые версии (так логотипы унифицированы) :

Слайдер: http://take.ms/VSnwj
Сетка: http://take.ms/OTUts

При наведении можно показывать цветное лого

**Comment by iliakan** [comment]
Цветной вариант looks good. Всего там логотипов 30 ?
@tyv, у нас была карусель для отзыва можно как-то реюз для этой штуки?
