### ISSUE TITLE
Проблема с форумом? Uncaught Error: adsbygoogle.push(): All ins elements in the DOM w

### ISSUE THREAD

**Issue by khusamov** [iliakan/javascript-nodejs#651]
Здравствуйте!

Проблема с форумом? Uncaught Error: adsbygoogle.push(): All ins elements in the DOM w 
чето выдает ошибку, связанную с гуглом...

Браузер : Хром
Ошибка появляется на всех страницах форума.

Uncaught Error: adsbygoogle.push(): All ins elements in the DOM with class=adsbygoogle already have ads in them.

```javascript
gd	@	pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:54
hd	@	pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:55
(anonymous function)	@	pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:55
(anonymous function)	@	pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:55
```

вдобавок постоянно крутится в хроме загрузка - бесконечно что то пытается загрузить...

**Comment by iliakan** [comment]
1) Попробуйте в другом браузере
2) Дайте URL, где проблема

**Comment by khusamov** [comment]
в яндекс.браузере та же проблема
Uncaught Error: adsbygoogle.push(): All ins elements in the DOM with class=adsbygoogle already have ads in them.

URL к примеру этот http://javascript.ru/forum/site/56303-problema-s-forumom-uncaught-error-adsbygoogle-push-all-ins-elements-dom-w.html

**Comment by iliakan** [comment]
Fixed.

**Comment by khusamov** [comment]
А вы еще не опубликовали на самом сайте?
а то пока проблема наблюдается.
ну по крайней мере тут http://javascript.ru/forum/extjs/56409-%5Bw%5D-ignoring-server-record.html

**Comment by iliakan** [comment]
Может, из кеша?

**Comment by khusamov** [comment]
Странно. В яндекс. браузере проблемы уже нет. А в GoogleХроме все по старому.

**Comment by khusamov** [comment]
Вот этот запрос не дает покоя

https://mc.yandex.ru/watch/1178660?wmode=5&callback=_ymjsp866853086&page-ref=http%3A%2F%2Fjavascript.ru%2Fforum%2Fextjs%2F56407-vyzov-record-save-ne-obnovlyaet-pagingtoolbar-i-ne-menyaet-fantomnyjj-id-na-realnyjj.html&page-url=http%3A%2F%2Fjavascript.ru%2Fforum%2Fextjs%2F&browser-info=j%3A1%3As%3A1920x1080x24%3Ask%3A1%3Af%3A18.0.0%3Afpr%3A26122061601%3Acn%3A1%3Aw%3A1903x596%3Az%3A180%3Ai%3A20150615123910%3Aet%3A1434361151%3Aen%3Autf-8%3Av%3A636%3Ac%3A1%3Ala%3Aru%3Als%3A1402513224221%3Arqn%3A1203%3Arn%3A232834648%3Ahid%3A46600417%3Ads%3A0%2C0%2C211%2C41%2C0%2C0%2C%2C225%2C5%2C%2C%2C%2C450%3Afp%3A396%3Awn%3A28627%3Ahl%3A37%3Arqnl%3A1%3Ast%3A1434361151%3At%3AExtJS%20-%20Javascript-%D1%84%D0%BE%D1%80%D1%83%D0%BC
