### ISSUE TITLE
Ошибка в пояснении к тестам по JS

### ISSUE THREAD

**Issue by true0r** [iliakan/javascript-nodejs#655]
В пояснение указанно  **Везде "use strict"** ([строка в коде](https://github.com/iliakan/javascript-nodejs/blob/90373d79c74e7d80e3ef723acb0998db7fb4f744/handlers/quiz/templates/blocks/quiz-explanations.jade#L7)  [на сайте](http://learn.javascript.ru/quiz/js-basic))
В действительности, там где этот режим используется в вопросах, это явно указанно в коде, в других случаях подразумевается обычный. Из за описания, участник теста допускает ошибки, там где их нет

**Comment by iliakan** [comment]
Можно пример таких вопросов теста, где участник допускает ошибки, как вы пишете?

**Comment by true0r** [comment]
![image](https://cloud.githubusercontent.com/assets/8409258/8266364/3e9d49a8-1734-11e5-92d7-a27d43509c4e.png)
![image](https://cloud.githubusercontent.com/assets/8409258/8266514/99fa943a-173a-11e5-9bce-32c2c0f1a015.png)

Если подразумевается "use strict" то правильный ответ: **В коде ошибка** так как возбуждается ошибка *SyntaxError: Duplicate data property in object literal not allowed in strict mode*

Я прошел тест несколько раз и других вариантов нет, думаю это единственная типичная ошибка

**Comment by iliakan** [comment]
Наверно, вы пробовали в старом firefox? Там была такая проблемка.

В Chrome ошибки не будет.

**Comment by true0r** [comment]
Пробовал на node.js v0.12.2 с флагом -use_strict, в Chrome все действительно в порядке. 

В заблуждение вводит описание режима в книге,  думал это стандартное поведение. Тогда вопрос закрыт.

>В  строгом  режиме  попытка  определить  в  литерале  объекта  два  или  более 
свойств с одинаковыми именами считается синтаксической ошибкой.
 
*Флэнаган Д. JavaScript Подробное руководство 6 изд 2012 ст.134*

**Comment by iliakan** [comment]
Да, процитированное вами утверждение – неверно.
