### ISSUE TITLE
Что-то не так в решении задачи

### ISSUE THREAD

**Issue by Alexey-v-Ivanov** [iliakan/javascript-nodejs#663]
http://learn.javascript.ru/getters-setters#добавить-геттер-для-power

Берем код из решения, добавляем строки:
var cm = new CoffeeMachine(400, 200);
alert( cm.getPower )

И в алерте вместо 400 получаем:
function() {
    return power;
}

п.с. возможно, конечно, что это я что-то делаю не так))

**Comment by iliakan** [comment]
```js
alert( cm.getPower() );
```
