### ISSUE TITLE
Платформа движка IO.JS или Node.JS ?

### ISSUE THREAD

**Issue by CustomButtons** [iliakan/javascript-nodejs#664]
На главной странице репозитория платформа называется 4 раза из которых: 1 раз - IO.JS, 3 раза - Node.JS. Надо привести к одному виду.
![platform1](https://cloud.githubusercontent.com/assets/5240074/8639002/7485f520-28e5-11e5-874a-2fe05f2f984f.png)
![platform2](https://cloud.githubusercontent.com/assets/5240074/8639017/0ad68382-28e6-11e5-95b6-9b8657958d79.png)

**Comment by iliakan** [comment]
Fixed.
