### ISSUE TITLE
Добавить в учебник ссылку "Случайная статья"

### ISSUE THREAD

**Issue by CustomButtons** [iliakan/javascript-nodejs#668]
В данный момент в учебнике 220+ статей и все они очень полезные и интересные.
Часто хочется прочитать **любую** статью и на этот случай не хватает кнопки **"Случайная статья"** как в википедии.
В общем голосую за введение этого функционала.

**Comment by iliakan** [comment]
@tyv @Bezart what you think?

**Comment by tyv** [comment]
Это же учебник а не stack-overflow

**Comment by iliakan** [comment]
@Bezart согласен с @tyv?

**Comment by Bezart** [comment]
Да, согласен, это не решает основной цели учебника. Мне кажется важнее показывать релевантную информацию нежели случайную.
