### ISSUE TITLE
Количество мест на курсе 

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#672]
Мы говорили о показе количества оставшихся мест на курсе, помнишь? Забыли в дизайне, похоже.

**Comment by Bezart** [comment]
http://take.ms/J9bdp

**Comment by iliakan** [comment]
Пишем из расчёта "все места минус оплатившие"? 
Если человек записался, но пока не оплатил - место под него не резервируется?

Можно вычислять из расчета, что 80% всех записей оплачивается. То есть "все места минус оплатившие минус 0.8 * ожидающие оплаты".

**Comment by Bezart** [comment]
Думаю только оплатившие. Альтернативно можно показывать "80% мест уже занято" это не привяжет тебя к конкретным числам.

**Comment by Bezart** [comment]
Что думаешь на счет предложения?

**Comment by iliakan** [comment]
Да, учитываем только оплативших.

Надпись эту показываем начиная с какого количества мест? Всегда? Или с 50% занятых?

**Comment by Bezart** [comment]
С 50% имеет смысл
