### ISSUE TITLE
Disqus генерит неправильные ссылки на комменты

### ISSUE THREAD

**Issue by burashka** [iliakan/javascript-nodejs#675]
В почтовой нотификации от Disqus есть кнопка "Reply to *", которая генерит ссылку без https, в итоге переход заканчивается сообщением "Сервер не найден". Вероятно стоит настроить хотя бы редирект с http на https или поставить какую-нибудь заглушку на http.

**Comment by travis-javascript** [comment]
Можно пример ссылки?

---
Best Regards,
Ilya Kantor

2015-07-25 13:45 GMT+03:00 Evgeny Uspenskiy <notifications@github.com>:

**Comment by iliakan** [comment]
Можно пример кривой ссылки?

**Comment by burashka** [comment]
http://javascript.in/let-const#comment-2156071691

**Comment by iliakan** [comment]
Вносил исправления.
Можно пример страницы, на которой такая ссылка, если она ещё есть?

**Comment by burashka** [comment]
https://learn.javascript.ru/let-const
Могу что-нибудь ответить в обсуждении и тогда вам придет ссылка или вы ответьте и тогда выложу что прислал дискус.

**Comment by iliakan** [comment]
Написал.

**Comment by burashka** [comment]
Прошел нормально. Спасибо!
