### ISSUE TITLE
Цвет фона для иллюстраций

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#677]
В данный момент экспорт иллюстраций настроен таким образом, что фон в итоговом файле прозрачный. Как думаешь, стоит ли сделать его белым? Дело в том что некоторые иллюстрации используют белую обводку / заливку, в итоге накладывать их на другой фон не имеет смысла. Пример: https://js.cx/article/intro/limitations.png

**Comment by iliakan** [comment]
Предложил бы не форсить белый цвет, если нет необходимости.
Она сейчас есть?

**Comment by Bezart** [comment]
Конкретно

**Comment by iliakan** [comment]
Закрываю, пока в этом нет необходимости, если позже она появится то сделаем.
