### ISSUE TITLE
Карта сайта в iphone

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#680]
Не работают ссылки.

**Comment by iliakan** [comment]
@Bezart better now?

**Comment by Bezart** [comment]
Проверли на iphone 5 (chrome, safari) по прежнему нужно 2 раза тапать. Это же поведение наблюдается в главном меню (ссылки "карта учебника", "купить учебник", социальные иконки)

**Comment by Bezart** [comment]
на ipad mini то же самое

**Comment by iliakan** [comment]
@tyv, я попробовал через класс `.working-hover` обойти (`:hover` только при его наличии включаю, а для iphone/ipad/ipod его нет), но может в чём-то ещё дело?

**Comment by tyv** [comment]
посмотрю сегодня вечером
