### ISSUE TITLE
Разные преподаватели для курсов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#684]
- Страница курсов
- Страница отзывов (фильтр по преподу, вывод препода)
- Страница записи
- О преподе (в профиле?)

**Comment by Bezart** [comment]
О преподавателе: http://take.ms/cnmCM
Страница курсов: http://take.ms/Zsxe2
Страница отзывов: http://take.ms/lr6ut
Страница записи: http://take.ms/9TjU4

**Comment by iliakan** [comment]
На странице отзывов слова "Отлично", "Хорошо" и др - больше не ссылки? Раз селект-фильтр есть.

**Comment by Bezart** [comment]
1) Можно оставить ссылку которая будет менять селект. То есть можно будет 2-мя способами применить фильтр

2) Согласен, можно поменять на "Ведет"

**Comment by Bezart** [comment]
В будущем на страницу преподавателя можно будет добавить количество проведенных курсов и общий рейтинг (или дату когда начал вести курсы). Сейчас данных не хватает, так что это может оказаться негативным фактором.

**Comment by iliakan** [comment]
На отзывы хорошо бы добавить в дизайн комментарий преподавателя.

Мало ли чел напишет "Препод хреново знает геометрию." А препод должен иметь возможность сказать что "Вообще-то курс про JavaScript, вы не туда записались товарищ".

**Comment by iliakan** [comment]
Предложение по местам в дизайне:
1) в дизе вывода отзыва (как в списке, так и отдельно) добавить вывод комментария преподавателя.
2) в дизе вывода отзыва в списке сейчас есть ссылка на страницу этого отзыва одного? Если нет, то добавить.
3) на странице отдельного отзыва преподаватель может его откомментировать.

**Comment by iliakan** [comment]
up? :)

**Comment by Bezart** [comment]
Сегодня прорисую

**Comment by Bezart** [comment]
1) Вывод в списке: http://take.ms/AmqaU (аналогично на странице отзыва)
2) Cсылка есть в правом верхнем углу (#)
3) Процесс добавления / редактирования комментариев для препода: https://monosnap.com/file/CSde3vAISXGwONvPhY6J1x25HOLM2h

**Comment by iliakan** [comment]
А преподавателя мы выводим внизу отзыва всегда вообще?

**Comment by Bezart** [comment]
Да, всегда. Ты как-то по-другому думал сделать?

**Comment by iliakan** [comment]
Если фильтр по преподу, то тоже выводим?

**Comment by Bezart** [comment]
да, выводим
