### ISSUE TITLE
Футер для англ версии

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#686]
В английской версии - такой же футер? Соглашение может не нужно? Ещё какие-то изменения?

**Comment by Bezart** [comment]
Кроме соглашения можно оставить все как есть. Можно еще оставить ссылку на русскую версию для тех кто заблудился.

**Comment by iliakan** [comment]
Да, точно. RU/EN где-то должно быть. Где?

**Comment by Bezart** [comment]
Предлагаю в футере https://monosnap.com/file/rgP3CCAMJFuUAeDPZNvukoEGXZ6VA4
