### ISSUE TITLE
О сайте в английском варианте

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#687]
Страницу "О сайте" изменить для английской версии.

**Comment by Bezart** [comment]
Я пока набросал перевод текущей http://take.ms/fysFUl можешь глянуть и сказать, какую информацию ты хотел бы изменить/добавить. Я не вижу смысла отделять javascript.info от javascript.ru, но может у тебя свое видение

**Comment by Bezart** [comment]
По скайпу решили делать больше особняком. Вариант лейаута http://take.ms/tF4rI

**Comment by iliakan** [comment]
А серое сверху - это текущий "баннер" или что-то другое?

**Comment by iliakan** [comment]
Пока больше нравится просто перевод ;)
