### ISSUE TITLE
Список материалов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#690]
Вот текущий вид:
http://ilyakantor.ru/screen/2015-08-20_1601.png

Нужно:
1) Форму добавления материала покрасивше (для преподавателей only)
2) К материалу может быть комментарий, один абзац. Его вывод в список.

**Comment by Bezart** [comment]
Добавил в на страницу cources: http://take.ms/ChbYdS
Предлагаю еще добавить возможность удаления (при клике на иконку)
