### ISSUE TITLE
Цвет кнопки "решение"

### ISSUE THREAD

**Issue by inomn** [iliakan/javascript-nodejs#691]
Если раскрыть решение задачи, то кнопка получает синий фон. Затем красный ховер на синем фоне - режет глаза - https://i.gyazo.com/901096325f3e53d3d3cdc97041dbb6c5.png

**Comment by iliakan** [comment]
Вот скриншот при наведении: http://ilyakantor.ru/screen/2015-08-21_1653.png

@Bezart как там должно быть по дизайну?

**Comment by Bezart** [comment]
Согласен, смотрится не очень. Давай оставлять ссылку белой, просто добавляя подчеркивание при ховере:  
![image](https://cloud.githubusercontent.com/assets/576155/9460480/bc541b32-4b06-11e5-8876-606ec78d114d.png)
