### ISSUE TITLE
Непонятный отступ на главной учебника

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#693]
В средней колонке какой-то отступ вылез http://jmp.sh/YjTPpH1

**Comment by iliakan** [comment]
@tyv глянь плиз.

**Comment by tyv** [comment]
@Bezart @iliakan я такого не наблюдаю — это хром?

**Comment by iliakan** [comment]
@Bezart браузер и разрешение экрана какие?

**Comment by Bezart** [comment]
@iliakan @tyv Version 45.0.2454.78 beta (64-bit) macos 
Может быть по причине беты. В ff все гут. Еще при наведении на заголовок выскакивает не вся иконка: http://jmp.sh/OAkYVzu
