### ISSUE TITLE
Полноэкранная версия карты учебника 

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#698]
Заменить текущий попап как обсуждали в #695

**Comment by Bezart** [comment]
Как на счет такого варианта с небольшой прозрачностью https://monosnap.com/file/QYjJy60B4tLlbwavgKKpKHGw6eoxVC ?

**Comment by iliakan** [comment]
Ок. В макете сейчас он, да?

**Comment by Bezart** [comment]
Да, есть на странице navigation logic

**Comment by iliakan** [comment]
@Bezart норм что вверху столько пустого места?

**Comment by Bezart** [comment]
Пустого места действительно много, 30px—35px хватит с головой

**Comment by iliakan** [comment]
@tyv пустое место поправь плиз.
