### ISSUE TITLE
CSS для англ версии

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#700]
1) В JS есть переменная `LANG` глобальная с языком `"ru"/"en"`. Ветки типа `if (LANG == "en")` вполне ок, так как при сборке остаются только те `if`, в которых язык тот, что в константе.

2) Сделал файл `ru.styl` и `en.styl`, вместо главного `index.styl`.
Пожалуйста, вырежь из `en.styl` то, что не нужно для учебника. Я чуть порезал, может ещё что-то?

**Comment by tyv** [comment]
ох, а ты уже запушил? я просто на середине работы над другим кусокм и у нас очевидно будут тут конфликты :(

**Comment by iliakan** [comment]
Да, но ничего. Перетри мои изменения в стилях своими тогда, их немного. Потом сделай файлы ru.styl en.styl уже какие сам считаешь нужным.

**Comment by iliakan** [comment]
Пока откладываем выделение `common.styl`?

**Comment by iliakan** [comment]
Какое состояние этой issue сейчас, не подскажешь? Английская шапка для глав и статей готова?

**Comment by tyv** [comment]
да, готова; 
common.styl надо выделить вечер.. на неделе постараюсь сделать
