### ISSUE TITLE
Профиль: редактирование и вывод "О себе"

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#706]
Добавлено новое поле "о себе" для пользователя, в профиле.

При редактировании - текстария с подписью, дизайн: https://jumpshare.com/v/ksGKAh9TC0xwcfBO7ZAu

Сейчас реализовал так:
```
div
  textarea.textarea-input(maxlength=300 focus-on="editing" ng-model="editingValue" type="text")
  p Только текст и ссылки, не более 300 символов.
```

Получилось вот: 
http://ilyakantor.ru/screen/2015-09-16_1812.png

Поправь плиз стили, чтобы хорошо выглядело.

-----------------

При выводе сейчас переносов нет, текст вылезает:
http://ilyakantor.ru/screen/2015-09-16_1810.png

Нужно, чтобы выводился 1 параграф текста, сейчас ограничение до 300 знаков.

**Comment by iliakan** [comment]
P.S. В гостевом профиле то же самое при выводе:
http://ilyakantor.ru/screen/2015-09-17_1345.png

**Comment by iliakan** [comment]
Так это выглядит сейчас: http://ilyakantor.ru/screen/2015-09-22_1936.png

Поле выглядит очень маленьким, некрасивым и неудобным. Особенно если хочется вместить несколько параграфов что, в плане рассказа "о себе" более чем уместно.

**Comment by Bezart** [comment]
Ну давай увеличим его + увеличим line-height

**Comment by iliakan** [comment]
Естественно было бы снизу разместить кнопки "отмена"-"сохранить", мне кажется.

**Comment by Bezart** [comment]
Кнопки хотелось бы оставить чтобы сохранить логику редактирования одинаковой для всех полей. Вот увеличил немного размер http://take.ms/3W4AE

**Comment by iliakan** [comment]
а вариант с кнопками внизу можно посмотреть для сравнения?

**Comment by Bezart** [comment]
http://take.ms/m9EBj

**Comment by iliakan** [comment]
@bezart, то есть только на часть ширины текстарея всё равно?

**Comment by Bezart** [comment]
Слишком длинные textarea неудобны. По прежнему считаю что вариант с кнопками справа лучше

**Comment by iliakan** [comment]
@tyv, что думаешь?
Два варианта:
http://take.ms/3W4AE
http://take.ms/m9EBj

**Comment by tyv** [comment]
мне все равно тут, главное чтобы cmd+enter сработал

**Comment by tyv** [comment]
делать что-то?

**Comment by iliakan** [comment]
ок, давай тот вариант, который @Bezart предложил
https://github.com/iliakan/javascript-nodejs/issues/706#issuecomment-142676763

размер больше, шрифт, возможно, поменьше.

**Comment by iliakan** [comment]
Сделаю сам.
