### ISSUE TITLE
Политика отзывов

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#713]
Хорошо бы где-то добавить упоминание о нашей политике в отношении отзывов.

1) Показываются все отзывы, опубликованные авторами. Фильтрацию по оценке вы можете сделать сами.
2) Отзывы не модерируются. Исключение может быть сделано только при нарушении условий пользования сайтом и курсами.
3) Все люди - реальные участники.

Это важно, особенно пункт 1), иначе люди могут подумать, что отзывы специально выбирали.

**Comment by Bezart** [comment]
Несколько вариантов:
V1: http://take.ms/9vuaW
V1 (hover): http://take.ms/bqxAw

V2 (иконка в правом верхнем углу): http://take.ms/XxDBc
V3: http://take.ms/oT6Kv

**Comment by iliakan** [comment]
Выбрали первый вариант.

**Comment by Bezart** [comment]
В исходниках  ```Courses / Reviews / Summary / Policy```, ```Courses / Reviews / Summary / Policy Expanded```
