### ISSUE TITLE
Список отзывов: преподаватель

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#714]
Нам точно нужен родительный падеж?

http://ilyakantor.ru/screen/2015-09-19_2015.png

**Comment by Bezart** [comment]
Ну так читается по-человечески. Иначе нужно вводить подписи "Преподаватель" и "Оценка", либо же коряво будет звучать "Отзывы --- Василий Иванов --- Все оценки"

**Comment by iliakan** [comment]
с оценкой всё очевидно о чём фильтр
с преподавателем - полагаешь, что нет?

**Comment by Bezart** [comment]
Не критично в принципе, если много кода писать, можно без падежа
