### ISSUE TITLE
Отзывы: фильтр по преподавателям и статистика

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#715]
В отзывах есть фильтр по преподавателям и оценке.

При изменении фильтра по преподавателям - мы меняем статистику? (число отзывов по оценкам, % рекомендаций)

Или всегда, вне зависимости от фильтра, только общую статистику показываем?

**Comment by Bezart** [comment]
Я думаю, показываем всегда общую статистику внутри блока. Как следующий шаг можно перенести фильтр вверх (показывать над блоком), тогда можно применять ко всему содержимому.
