### ISSUE TITLE
Ссылка на комментарий

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#717]
Вот эта ссылку на комментарий - есть где-то?
http://ilyakantor.ru/screen/2015-09-20_1800.png

Если нет - добавь плиз.

**Comment by iliakan** [comment]
@bezart: может лучше дату сделать ссылкой?

**Comment by Bezart** [comment]
Да, можно и дату сделать, правда, тогда не совсем очевидно будет что это ссылка.

**Comment by iliakan** [comment]
Ок, при наведении будет ссылка значит.
