### ISSUE TITLE
Открывать ссылку на договор оферту в новом окне

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#723]
Сейчас с последнего шага оплаты меня кидает на новую страницу а при нажатии Back я переходу опять на первый шаг. Думаю, имеет смысл открывать в новом окне чтобы не уводить пользователя из туннеля.

**Comment by iliakan** [comment]
тогда посетитель закроет страницу оплаты и увидит "неоплаченный" интерфейс.

**Comment by Bezart** [comment]
Почему он будет закрывать страницу оплаты? Мы открываем новое окно небольшого размера и оставляем его на той же странице оплаты без надобности заполнять ту же форму 2 раза

**Comment by iliakan** [comment]
Мы не открываем новое окно браузера?

**Comment by Bezart** [comment]
сейчас нет

**Comment by iliakan** [comment]
Ты предложил открывать новое окно браузера?
