### ISSUE TITLE
Nowrap для даты / времени курсов

### ISSUE THREAD

**Issue by Bezart** [iliakan/javascript-nodejs#724]
Сейчас плохо читается: http://take.ms/VhxCj предлагаю поставить nowrap для даты / времени, или на новую строку всегда переносить

**Comment by iliakan** [comment]
Это на маленьком экране? Там дата - это часть названия группы, nowrap её не поставишь.
Может, есть альтернативные варианты?

**Comment by Bezart** [comment]
Альтернативное решение — формализировать дату начала и время проведения курсов и генерировать заголовок автоматически, при этом указывать только название самого курса. Или же просто ввести еще одно кастомное текстовое поле, которое будет отвечать за подзаголовок, то есть "Регистрация" + "Название курса" + "подзаголовок"

**Comment by iliakan** [comment]
может шрифт просто чуть меньше? :)

**Comment by Bezart** [comment]
Это стандартный заголовок, поэтому не хотелось бы лепить костыли. Если сложно, давай тогда так оставим
