### ISSUE TITLE
Курс: Анкеты участников

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#731]
Нужна страничка, где преподаватель может посмотреть анкеты участников группы.

Видимо, в виде списка, а не по отдельности.

**Comment by Bezart** [comment]
А что такое анкета и в каком виде она храниться?

**Comment by iliakan** [comment]
Анкета это  когда юзер получил инвайт - он заполняет о себе. Потом мы используем это для отзыва.
Что-то в дизах не могу найти.

**Comment by Bezart** [comment]
а, понял, хорошо, сделаю

**Comment by Bezart** [comment]
Список учасников: http://take.ms/zn5eh

В каком виде будем анкету показывать, как форму или нужен отдельный дизайн?

**Comment by iliakan** [comment]
Главное, чтобы ведущий курса мог быстро прочитать анкеты участников, это только для ведущего.

**Comment by Bezart** [comment]
Так в анкете только имя и имейл выходит: http://take.ms/bP3ob

**Comment by iliakan** [comment]
Это не анкета.
Анкета - это когда инвайт получил и присоединяешься к группе.

**Comment by Bezart** [comment]
https://monosnap.com/file/sEJ29lGTjEfIgcmH1iKlHTXOxo62dq

**Comment by iliakan** [comment]
1) Название юзера - видимо, ссылка на его профиль?
2) Сортировка по имени юзера?
3) На эту страницу где в интерфейсе лучше ссылку сделать?

**Comment by Bezart** [comment]
1) Можно, да
2) Как удобнее, можно по дате записи на курс
3) Лучше делать ссылку которая будет видна только преподу в разделе "курсы" в его аккаунте http://take.ms/bN3IJ (здесь можно давать и ссылку для рассылок по группе)

**Comment by iliakan** [comment]
Окончательный вариант анкет, как я понял: https://monosnap.com/file/sEJ29lGTjEfIgcmH1iKlHTXOxo62dq
