### ISSUE TITLE
Тема для скринкаста

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#734]
Для нового скринкаста по webpack нужна тема.
http://webpack.github.io/

Как для заставки, так и для "слайдов".

Тема светлая лучше, для node.js она темновата получилась в итоге.

**Comment by Bezart** [comment]
Заставка: http://take.ms/hQdaI
Слайды: http://take.ms/7hGOB

Присылай мне видео (5-7 секунд), которое мы обсуждали, я сам напишу звуковые эффекты для заставки, так будет звучать более профессионально.

**Comment by Bezart** [comment]
Вот набросал звуковой ряд и сделал превью для видео: http://take.ms/0y0BA

**Comment by iliakan** [comment]
More more!

**Comment by Bezart** [comment]
Рендер: https://www.dropbox.com/s/ijb29e7batafnxz/JSR_Screencast_Webpack_v4.mp4?dl=0
Исходник ScreenFlow: https://www.dropbox.com/sh/zlsj3ulbhmcorb1/AACvH1M6CezCI5kJCwl15UX6a?dl=0
