### ISSUE TITLE
Скидка на продукты jetbrains - только для участников курса

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#735]
Надо бы страничку со ссылкой learn.javascript.ru/jb закрыть для всех, кроме курсантов и ссылку на неё куда-то поместить, чтобы они её могли найти.

**Comment by Bezart** [comment]
Привел саму страницу к стандартному виду: http://take.ms/BTOwZ
Ссылку на скидку размещаем в стандартном месте в профиле: http://take.ms/3d2tD

**Comment by iliakan** [comment]
Ок, там уже 4 ссылки, выходит.
