### ISSUE TITLE
Webpack screencast page

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#736]
Дизайн learn.javascript.ru/webpack-screencast

**Comment by Bezart** [comment]
По аналогии с Node.js: https://monosnap.com/file/csRz6VnYUbKyp5Jiybgz0al37DstGe

**Comment by iliakan** [comment]
Подписка на новые выпуски - там же, в том же виде?

**Comment by Bezart** [comment]
Расширенная подписка http://take.ms/XolDF Для нода по той же схеме

**Comment by Bezart** [comment]
После обсуждения в скайпе, решили оставить лендинг как на node.js:
https://monosnap.com/file/csRz6VnYUbKyp5Jiybgz0al37DstGe

При открытии видео, показывать полноэкранный режим с плейлистом и возможностью навигации по курсу: http://jmp.sh/N0K0ylr

**Comment by iliakan** [comment]
Уточнения из скайпа
1) Это оверлей на всю страницу
2) Сайдбар статический, видео - на оставшуюся ширину

Моб - ?

**Comment by Bezart** [comment]
#67A2D2 — цвет фона у блока
https://www.dropbox.com/s/nkeath8bxqgth1j/webpack_bg.png?dl=0 — картинка

Картинку нужно просто центрировать и не тянуть
