### ISSUE TITLE
Управление рассылками из профиля

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#737]
Текущая страница управления подписками выглядит так:
http://learn.javascript.ru/newsletter
http://screencast.com/t/7HrBmNSDn9

Она доступна как вошедшим юзерам, так и анонимам, т.е. не совсем является частью профиля. 

Сейчас она вообще недоступна посетителям сайта. Куда бы ссылку на неё поместить?

**Comment by Bezart** [comment]
Эта страница нужна тем, кто уже подписан на рассылку или тем кто еще только хочет подписаться?

**Comment by iliakan** [comment]
И тем и тем.

**Comment by Bezart** [comment]
Это две разные варианта. Я предлагаю давать ссылку в самом письме чтобы отписаться. А для записи использовать блок на главной, при этом автоматически подписывать на все либо спрашивать в процессе.

**Comment by iliakan** [comment]
сейчас это одна страница,

**Comment by iliakan** [comment]
в письме - ссылка на неё

**Comment by Bezart** [comment]
После обсуждения в скайпе предлагаю сделать следующим образом:

1. На главной блок для записи на уведомления: http://take.ms/Tvt0M 
2. Для зареганых пользователей добавить соответствующий раздел в аккаунте: http://take.ms/Qq716
3. Оставить существующую страницу (http://learn.javascript.ru/newsletter) для тех кто кликает на ссылку "Отписаться" в письме

**Comment by iliakan** [comment]
@tyv, не мог бы сделать блок на главной и подписки в профиле.

**Comment by iliakan** [comment]
@Bezart 
Блок на главной - только для анонимов или для всех?

Если текущий юзер - зареган, то этот блок меняется, если какие-то подписки уже есть и позволяет управлять ими так же, как в профиле?

**Comment by Bezart** [comment]
Блок для всех, так как если чел зареган, это не значит что он подписан. Этот блок не меняется, даже если чел подписан. Просто обновляем его списки
