### ISSUE TITLE
Оплата: банковская квитанция в Украине

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#741]
В список способов оплаты добавить способ через банк Украины.
То есть, по сути то же самое, что Сбербанк сейчас, но в гривнах на Украине.

Сейчас выглядит так:
https://gyazo.com/f8e601992964d775bdc3a24320eafb04

**Comment by Bezart** [comment]
Предлагаю сделать по аналогии с существующим пунктом:
Банковский перевод (для оплаты в гривнах)

Без скобок и логотипов

**Comment by iliakan** [comment]
Нужен лого для этого способа оплаты.

У нас способ оплаты выбранный изображается только в виде лого в краткой форме. Для банковского перевода по россии, к примеру, используется https://gyazo.com/4e59422f0e5f47fd0476977ae84ce9d0

**Comment by Bezart** [comment]
Решили не использовать логотип вообще
