### ISSUE TITLE
Заглавная страница для англ версии

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#750]
Для англ версии нужна заглавная страница, с учётом того, что там сокращённый вариант учебника, который постепенно дописывается.

То есть, хорошо бы не ждать, пока все будет переведено, чтобы начать публиковать.

Пока это только первая часть, потом будет ещё контент.

**Comment by Bezart** [comment]
Дублирует https://github.com/iliakan/javascript-nodejs/issues/897
