### ISSUE TITLE
 se strict;

### ISSUE THREAD

**Issue by AndreiSharov** [iliakan/javascript-nodejs#753]
Очень много примеров поломалось на сайте из-за добавления use strict в основном ошибка что не объявлена переменная

Например:

1:
https://learn.javascript.ru/keyboard-events
В действии:
<input onkeypress="this.nextSibling.innerHTML = getChar(event)+''"><b></b>
не работает

2:
https://learn.javascript.ru/regexp-groups

var str = '<span class="my">';

reg = /<(([a-z]+)\s*([^>]*))>/;

alert( str.match(reg) ); // <span class="my">, span, s

Нет var reg 

3: https://learn.javascript.ru/regexp-groups

тоже самое 
match = 'a'.match(/a(z)?(c)?/)

alert( match.length ); // 3
alert( match[0] ); // a
alert( match[1] ); // undefined
alert( match[2] ); // undefined

match = 'ack'.match(/a(z)?(c)?/)

4: https://learn.javascript.ru/regexp-groups

alert( match.length ); // 3
alert( match[0] ); // ac, всё совпадение
alert( match[1] ); // undefined, для (z)? ничего нет
alert( match[2] ); // c

5: https://learn.javascript.ru/regexp-backreferences

str = "He said: \"She's the one!\".";

reg = /['"](.*?)['"]/g;

6: https://learn.javascript.ru/regexp-backreferences

str = "He said: \"She's the one!\".";

reg = /(['"])(.*?)\1/g;

alert( str.match(reg) ); // "She's the one!"

**Comment by iliakan** [comment]
PR не мог бы составить из этого?

**Comment by iliakan** [comment]
Всё кроме 1 поправил, 1 не понял.
