### ISSUE TITLE
Ошибка в регулярном выражении

### ISSUE THREAD

**Issue by AndreiSharov** [iliakan/javascript-nodejs#755]
https://learn.javascript.ru/regexp-backreferences

Ошибка в решении:

Итого, получится: \[(b|url|quote)\][\s\S]*?\[/\1\].
и
Для закрывающего тега [/1] понадобилось дополнительно экранировать слеш: \[\/1\].

Ошибка в \[/\1\], причём в коде решения правильно: \[\/\1\]

**Comment by iliakan** [comment]
Не понял.

**Comment by AndreiSharov** [comment]
Ошибка в решение задачи первой задачи
https://learn.javascript.ru/regexp-backreferences
в строке
Итого, получится: \[(b|url|quote)\][\s\S]*?\[/\1\].
а должно быть
Итого, получится: \[(b|url|quote)\][\s\S]*?\[\/\1\].

так же ошибка дальше в 
Для закрывающего тега [/1] понадобилось дополнительно экранировать слеш: \[\/1\].
Должно быть:
Для закрывающего тега [/1] понадобилось дополнительно экранировать слеш: \[\/\1\].

Причём в коде решения всё правильно:
var re = /\[(b|url|quote)\][\s\S]*?\[\/\1\]/g;

**Comment by iliakan** [comment]
Всё правильно. В самом регэкспе слеша нет. Слеш нужен при объявлении его через /.../.

**Comment by iliakan** [comment]
Если через new RegExp , то слеш не нужен.
