### ISSUE TITLE
Вопрос по коду аутентификации. Через facebook

### ISSUE THREAD

**Issue by mbob72** [iliakan/javascript-nodejs#757]
Пытаюсь разобраться как работает код аутентификации через соцсети, на примере facebook.

В стратегии (handlers/auth/strategies/facebookStrategy.js) получаем от фейсбука profile, и если все без ошибок, вызываем, в строке 108, authenticateByProfile, ей передаем данные profile и req в том числе. 

И вот вопрос в том, откуда у нас в этой ситуации может появиться req.user. Такая проверка проводится в стороке 72 кода handlers/auth/lib/authenticateByProfile.js

Как я понимаю, req.user ставится паспортом ПОСЛЕ завершения аутентификации, поддерживая авторизованную сессию в частности через serialize-deserialize, а у нас в этот момент авторизация еще на закончена, т.е. user еще не получен через вызов done(null, user) 

Помогите разобраться в логике. Т.е. profile это данные полученные от фейсбука, что такое req.use, с учетом того, что done(null, user) у нас еще не случилось.

**Comment by iliakan** [comment]
Свойство `req.user` установлено при привязке нового профиля соц. сети к существующему аккаунту.

То есть, это текущий юзер в том случае, если он осуществляет авторизацию через соц. сеть, будучи уже авторизованным на сайте - делает "привязку" (можно сделать в аккаунте).
