### ISSUE TITLE
ReferenceError: getChar is not defined

### ISSUE THREAD

**Issue by AndreiSharov** [iliakan/javascript-nodejs#758]
Страница:
https://learn.javascript.ru/keyboard-events

Там где пример в действии

Код:
input onkeypress="this.nextSibling.innerHTML = getChar(event)+''"

Ошибка
ReferenceError: getChar is not defined

**Comment by AndreiSharov** [comment]
Вот точнее:

<input onkeypress="this.nextSibling.innerHTML = getChar(event)+''"><b></b>

**Comment by AndreiSharov** [comment]
Вы добавили USE STRICT во все примеры и многие поломались, особенно в 3 части учебника.

**Comment by AndreiSharov** [comment]
Всё равно не работает :(

вот скриншот
http://etrubka.com/1.png

**Comment by iliakan** [comment]
Не апдейтил ещё учебник.
