### ISSUE TITLE
бесконечный цикл в примере

### ISSUE THREAD

**Issue by AndreiSharov** [iliakan/javascript-nodejs#759]
Страница:
https://learn.javascript.ru/while-for

Можно убрать и шаг:

//+ run
var i = 0;

for (; i < 3;) {
  alert( i );
  // цикл превратился в аналог while (i<3)
}
----------------------------------------------------------------------------------------------
Вместо:
for (; i < 3;) {
  alert( i );
  // цикл превратился в аналог while (i<3)
}
Сделать:
for (; i < 3;) {
  alert( i );
  i++;
  // цикл превратился в аналог while (i<3)
}

Потому что если запустить пример, то он превращается в бесконечный цикл!

**Comment by iliakan** [comment]
Не понял ;(
Проблема при запуске примера? Сам пример ок?

**Comment by AndreiSharov** [comment]
Скиншот
http://www.etrubka.com/2.png

Так как пример можно запустить то попадаешь в бесконечный цикл. Приходится перезапускать браузер. Предлагаю либо убрать возможность запуска. Либо добавить i++; в пример. 

Так же выложил скриншот в закрытом issue:
https://github.com/iliakan/javascript-nodejs/issues/758

**Comment by iliakan** [comment]
Пример на скриншоте http://www.etrubka.com/2.png - бесконченый? там же i<3

**Comment by AndreiSharov** [comment]
Не то выделил. Бесконечный чуть ниже.
http://www.etrubka.com/4.png

**Comment by iliakan** [comment]
Поправил. 
Просьба по проблемам в тексте делать issue тут https://github.com/iliakan/javascript-tutorial/issues
