### ISSUE TITLE
strict mode does not allow function declarations in a lexically nested statement

### ISSUE THREAD

**Issue by AndreiSharov** [iliakan/javascript-nodejs#760]
strict mode does not allow function declarations in a lexically nested statement.

Читаю учебник второй раз и вижу что многое поломалось

https://learn.javascript.ru/function-declaration-expression

Условное объявление функции

Скрин:
http://www.etrubka.com/3.png

**Comment by AndreiSharov** [comment]
Ещё одну нашёл. Вам интересны такие ошибки - их постить?

**Comment by AndreiSharov** [comment]
Понял что тут
https://github.com/iliakan/javascript-tutorial/issues

**Comment by iliakan** [comment]
Да.  Я это правил.
