### ISSUE TITLE
Donate webpack (or others)

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#761]
Донейт-модуль универсальный, для вебпака вначале попробуем.

Нарисовать:
http://jmp.sh/mCWsGyB

И блок, который на это ведёт, на странице http://learn.javascript.ru/webpack-screencast

**Comment by Bezart** [comment]
Кнпка донейта на странице скринкаста: http://take.ms/jrjQA 
Дополнительно можно сделать на главном банере: http://take.ms/GmgBx 

Страница с формой: http://take.ms/OApbY
