### ISSUE TITLE
Показ непубличных отзывов на курс

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#763]
Сейчас из отзывов на курс показываются только те, которые помечены авторами как публичные.

Как преподавателю увидеть непубличные? Где показывать их? В профиле? Ещё где-то?

**Comment by iliakan** [comment]
Внизу профиля показываем для зареганного учителя.

**Comment by iliakan** [comment]
https://monosnap.com/file/0NRSzBKY7xDAPxnOAHpeEh1Njq29KY

**Comment by iliakan** [comment]
Твой глазик импортировался в fontello вот так: http://jmp.sh/nYcBTcf

**Comment by Bezart** [comment]
А в чем проблема? Маленький размер?

**Comment by iliakan** [comment]
Не по дизайну

**Comment by Bezart** [comment]
Не вижу никаких проблем с дизайном, на макете у меня так же все: http://take.ms/thSta только инвертированный

**Comment by iliakan** [comment]
То есть, в CSS прописать серый фон и инвертированность, да?
