### ISSUE TITLE
Тест по javascript - в консоли Chrome другой результат

### ISSUE THREAD

**Issue by Floky87** [iliakan/javascript-nodejs#767]
![2015-12-08 9 32 33](https://cloud.githubusercontent.com/assets/5220147/11649295/a731fea6-9d8e-11e5-80f3-0291c12bb610.png)

Для этого вопроса Crhome (47.0.2526.73) выведет 'string1'. 

![2015-12-08 9 37 26](https://cloud.githubusercontent.com/assets/5220147/11649364/5f60c052-9d8f-11e5-9862-01b3742c3f10.png)

**Comment by iliakan** [comment]
Попробуйте на новой странице так сделать.
