### ISSUE TITLE
Поддержка Webpack

### ISSUE THREAD

**Issue by iliakan** [iliakan/javascript-nodejs#773]
По дизайну http://learn.javascript.ru/donate/webpack

Добавил имя (Если вы хотите, чтобы мы указали его вместе с суммой на странице поддержавших проект)

Тут ещё просят ссылку.

> ну мне как донатчику было бы полезнее что бы выводилось не мое имя а ссылка на профиль;
> и сортировать по взносу
> тогда "бизнесс-гуру" и "сео-мастера" будут тебе засылать больше 

Плюс нужен вывод поддержавших проект.

**Comment by Bezart** [comment]
https://monosnap.com/file/D1b4onzkmmydPAVkSvCFSi50LoNavX

**Comment by Bezart** [comment]
На странице: http://take.ms/zvqkx

**Comment by iliakan** [comment]
https://monosnap.com/file/pqOsqsPHYYC1GKwopgHvi3cTyzr9Ou

**Comment by iliakan** [comment]
последний вариант ^
