### ISSUE TITLE
PDF для Sublime Text не работает ссылка

### ISSUE THREAD

**Issue by futu** [iliakan/javascript-nodejs#785]
Файл не скачивается по ссылке http://learn.javascript.ru/sheet.pdf

**Comment by iliakan** [comment]
Проверьте ту же страницу ещё раз?

**Comment by futu** [comment]
Извините, файл не найден.

Если вы убеждены, что он здесь точно должен быть сообщите об этом на github.

**Comment by futu** [comment]
<img width="627" alt="screen shot 2016-01-06 at 18 25 10" src="https://cloud.githubusercontent.com/assets/734508/12146089/ded58d70-b4a2-11e5-86e0-b07e1a194c1c.png">
