### ISSUE TITLE
не сделалась красивой ссылка в разделе про __proto__

### ISSUE THREAD

**Issue by fakedous** [iliakan/javascript-nodejs#798]
https://learn.javascript.ru/prototype#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-proto
<b>"Создание объекта с прототипом: [Object.create(proto, descriptors)\](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Object/create)"</b> - наверно так не должно быть.
Спасибо за ваш труд, это походу огромный труд!

**Comment by iliakan** [comment]
Thanks fixed!
