### ISSUE TITLE
Код в элементе important__content не распарсился

### ISSUE THREAD

**Issue by NikolayGorev** [iliakan/javascript-nodejs#806]
На  [странице](http://learn.javascript.ru/ajax-xmlhttprequest#http-заголовки) в блоке с заголовком "Поставленный заголовок нельзя снять" код похоже не распарсился:
\```js
xhr.setRequestHeader('X-Auth', '123');
xhr.setRequestHeader('X-Auth', '456');

// в результате будет заголовок:
// X-Auth: 123, 456
\```

**Comment by iliakan** [comment]
Thanks!
