### ISSUE TITLE
Учебник, тема Основные операторы

### ISSUE THREAD

**Issue by RomanBayt** [iliakan/javascript-nodejs#809]
Здравствуйте!
На странице Основные операторы (http://learn.javascript.ru/operators#инкремент-декремент) не хватает одного "-" после декремента
![js](https://cloud.githubusercontent.com/assets/14962814/12272865/5d4a1712-b984-11e5-8210-04cec4b7b10f.png)
Спасибо!

**Comment by iliakan** [comment]
thanks fixed
