### ISSUE TITLE
Кнопка Запустить Демо не работает.

### ISSUE THREAD

**Issue by trubenko** [iliakan/javascript-nodejs#810]
Кнопка Запустить Демо не работает http://learn.javascript.ru/drag-and-drop . В самом низу на комментариями.

**Comment by nikolaynizruhin** [comment]
https://learn.javascript.ru/constructor-new#создать-calculator-при-помощи-конструктора 
Запустить Демо тоже не работает

**Comment by iliakan** [comment]
thanks, should be fixed.
