### ISSUE TITLE
Ошибка в тестах

### ISSUE THREAD

**Issue by chekit** [iliakan/javascript-nodejs#813]
**В тестах есть такой вопрос:**

````
Что выведет этот код?

<p id="elem">Привет!</p>

<script>
  elem.textContent = elem.outerHTML
  alert(elem.innerHTML);
</script>
````

**Правильно**
`&lt;p id="elem"&gt;Привет!&lt;/p&gt;`

**А в перечне ответов указано**
`&lt;p id="elem"&gt;Привет, мир!&lt;/p&gt;`

Это может вводить пользователя в сомнения, ведь *"мира"* в вопросе не было.

**Comment by iliakan** [comment]
Да, разумеется, спасибо, исправлено.

**Comment by chekit** [comment]
Спасибо
