### ISSUE TITLE
Не отдается статика.

### ISSUE THREAD

**Issue by OneginMaksim** [iliakan/javascript-nodejs#819]
GET http://javascript.in/pack/styles.css?237c007281e71a1723ea65b40a1927d5 
(index):14 GET http://javascript.in/img/sitetoolbar__logo.svg 404 (Not Found)
(index):14 GET http://javascript.in/img/sitetoolbar__logo_small.svg 404 (Not Found)
(index):4 GET http://javascript.in/pack/head.js?b8aab158846302c05c13 (anonymous function) @ (index):4
(index):14 Uncaught ReferenceError: head is not defined(anonymous function) @ (index):14
(index):14 Uncaught ReferenceError: head is not defined(anonymous function) @ (index):14
(index):8 GET http://javascript.in/pack/tutorial.js?b8aab158846302c05c13 (anonymous function) @ (index):8
(index):12 GET http://javascript.in/pack/footer.js?b8aab158846302c05c13 (anonymous function) @ (index):12
sitetoolbar__logo.svg:1 GET http://javascript.in/img/sitetoolbar__logo.svg 404 (Not Found)
sitetoolbar__logo_small.svg:1 GET http://javascript.in/img/sitetoolbar__logo_small.svg 404 (Not Found)
(index):14 GET http://javascript.in/img/sitetoolbar__logo.svg 404 (Not Found)(anonymous function) @ (index):14(anonymous function) @ (index):14(anonymous function) @ (index):14
(index):24 GET http://javascript.in/img/sitetoolbar__logo_small.svg 404 (Not Found)

Если запускать на порту 3000, то все равно ошибки статики.

**Comment by iliakan** [comment]
Что-то не так с настройкой, мб nginx

**Comment by OneginMaksim** [comment]
Скорее всего, но не могу понять что именно искать. Можете дать какой-нибудь ориентир, куда капать?
Переустанавливал nginx и сам проект, проверял пути и права. Может ли какой-нибудь модуль некорректно работать? (например, несовместимость, устарел и т.п.)

**Comment by iliakan** [comment]
Идти в браузере нужно на порт nginx.
Проверьте, не ругается ли nginx при запуске.
Проверьте, в тот ли хост приходит запрос.
Проверьте, соответствуют ли пути реальные тем, которые в конфиге nginx.

**Comment by OneginMaksim** [comment]
Спасибо, попробовал, но не смог все равно разрешить проблему. Что-то не замечаю видимо.

![2016-01-19 13 12 44](https://cloud.githubusercontent.com/assets/2615626/12415829/e7080642-beae-11e5-9df2-2b4ef1abb8c1.png)
![2016-01-19 13 12 51](https://cloud.githubusercontent.com/assets/2615626/12415827/e705e3bc-beae-11e5-8119-77d2fc188860.png)
![2016-01-19 13 14 37](https://cloud.githubusercontent.com/assets/2615626/12415828/e706381c-beae-11e5-930e-89d5a4f7461a.png)

**Comment by OneginMaksim** [comment]
при запуске nginx не ругается, все команды выполняет без ошибок (перезагрузка, остановка, запуск и т.д.)

**Comment by ORusak** [comment]
1. Проверьте пути к public в nginx/sites-enabled/learn.javascript.ru. 
root = js/javascript-nodejs/public путь относительный. Возможно его nginx найти не может. Я прописывал полный путь.
2. У вас nginx в opt/local/etc/nginx установлен? У меня ставился в etc.

Сам я не опытный в вопросах unix, но как раз с вашей проблемой столкнулся. Может будет полезно.

**Comment by OneginMaksim** [comment]
Спасибо,
1. пробовал, но проверю еще раз
2. да, у меня mac ports поэтому такой путь.

**Comment by OneginMaksim** [comment]
Спасибо, еще раз, первый пункт помог. 
Первый раз забыл перезагрузить nginx.
