### ISSUE TITLE
https://learn.javascript.ru/testing#уточнение-реализации

### ISSUE THREAD

**Issue by VitaliiKor** [iliakan/javascript-nodejs#820]
1) Во всём тексте пустые окошки (см. вложенный файл). По-моему - должно быть какое-то содержание в этих окошках.
![nepoladki](https://cloud.githubusercontent.com/assets/16522578/12381973/5176f5a2-bda5-11e5-9e21-bff12b376079.jpg)
2) Меню навигации слева не подсвечивает местонахождение на странице в текущий момент.

**Comment by iliakan** [comment]
Да, посмотрите сейчас? Если не работает - что в консоли? Какой браузер? По виду - статика у вас отвалилась.

**Comment by VitaliiKor** [comment]
Стало лучше.
1) навигация слева появилась.
![do not work](https://cloud.githubusercontent.com/assets/16522578/12469474/1fd48d34-bffd-11e5-8c36-f94fb1b160c9.jpg)
2) в пустых окошках в верхнем правом углу появился символ пера.
ссылка на это окно: https://learn.javascript.ru/testing#начальная-реализация
3) По-прежнему окно пустое.

Для примера - работающая страница: https://learn.javascript.ru/number#tostring-система-счисления
![it works](https://cloud.githubusercontent.com/assets/16522578/12469538/ac00f4c8-bffd-11e5-92a6-21c0ad9a0b3d.jpg)

Какое окошко на странице под консолью подразумеваете?
Если окно для ввода текста, то текст могу вводить только в комментах.
Браузер: Яндекс. Версия 15.12.0.6160.

**Comment by iliakan** [comment]
Браузерная дев консоль.

**Comment by VitaliiKor** [comment]
![console](https://cloud.githubusercontent.com/assets/16522578/12538137/76f2dd0e-c2e2-11e5-9d29-48bb5529c506.jpg)

**Comment by iliakan** [comment]
Это, похоже, у вас какой-то странный прокси или плагин в браузере, заголовка там быть не должно такого. 
Проверил на http://ru.js.cx/article/testing/pow-1/.

Заголовка X-Frame-Options там нет.

Проверьте?

**Comment by VitaliiKor** [comment]
:)
Илья, если бы я совсем-совсем хорошо понимал то, о чём вы пишите...
Что такое дев панель - и то - не сразу понял.
Яндекс помог понять.
Оказалось - это девелоперская панель.
:)
Я не программист - я только учусь.
Стрельнуло на старости лет.
Если это у меня странный прокси - пусть будет у меня.
Я прошёл эту тематику (тестирование).
И пошёл дальше.
У вас была ссылка, что если что сообщать о неполадках - я сообщил.
На других страниц не было неполадок - не сообщал.

А вообще - спасибо большое за сайт.
Достаточно грамотно и доходчиво про JS написано.

**Comment by iliakan** [comment]
Спасибо, что сообщили об ошибке. Пока не смог её воспроизвести.
