### ISSUE TITLE
В задаче undefined вместо пустой строки

### ISSUE THREAD

**Issue by NikolayGorev** [iliakan/javascript-nodejs#823]
Теперь в задаче http://learn.javascript.ru/task/object-property-this у меня в решении выводит undefined вместо пустой строки.
При чем, если сначала взять код решения и запустить в консоли (выведет пустую строку),
то потом запуск в решении выводит пустую строку.

**Comment by iliakan** [comment]
Описание исправлено. Это из-за перевода учебника в use strict =)
