### ISSUE TITLE
Проблемы с кодировкой

### ISSUE THREAD

**Issue by Gurylev** [iliakan/javascript-nodejs#825]
Читаю сайт читалкой Pocket второй раз. И второй раз понимаю, что покет вырезает все куски кода. Чтоб их посмотреть, я захожу из вида "статья", в вид "страница", то есть загружаю оригинальную статью, а не оптимизированную. Но когда пытаюсь её загрузить (так со всеми статьями на этом сайте, но не на других сайтах), вижу битую кодировку. Это, получается, в режиме браузера (вебвью).
![битая кодировка на learn.javascript.ru](https://lh3.googleusercontent.com/BpjAAIIAiW0jbzT3fNsaHRmasPVMTT1r90LMumJ3sE74qpUhnLzOYkG5sfXux1nAHQqjRfdjDbdKLG0UsZGp8VREtcWFtCVElt4k4e1J43jWwNDMqmRNjWcg3OYPTa5FtVzQqUushFrB8m_qC_lPeVd_sG6HTB6tbql6GyHmvcIt8rvC9JXLZkd8Y3ZIDvDPKyR4cUlRz56Sz95sOeL-KEBSybCkeAUawglKFIOZ0TSShfKaUTVa1jWTOdGtsivuV_fB68iG8AtfzLuBb0QOUyi0OR77-aJcMXKNLK2b6gDKpLk2Pt8ZbeEc7QBS1LvS4nK7VOZ_rjiayzexMl-zHfs-n-vdga1yGpntMctdC9t_v9aRKQjlaFDMJe2KROtuJolGdCcFCwCunXkJZI3MACY9TG2H1AdHywDYlEW21beQj9-fpuNQ4Yy-um41dj5KZo7lEJ9Rj2ia62ibxXwFHcEEhJD8-Y28mD5ChlfLdJ_aUMhnqshTZPC383gzBhISYQMWGreCtX7pjTpRCIktL5kfFQCe2k17bGOEJ9QuAR6voeorGWXO8hIf09vWJSUcK-OC6Q=w640-h960-no)

Я читаю сайт только в метро по пути до дома или работы. И добравшись до точки назначения уже забываю отправить ишью. И в прошлый раз я прочитал все статьи раздела learn, так и не отписав о проблеме. Да и сейчас случайно вспомнил.
Из-за этого многих кусков кода я так и не увидел. Пришлось догадываться. 
Пожалуйста, сделайте что-нибудь с кодировкой! Сейчас я вообще не вижу тега meta charset. 
Всем utf-8! Заранее спасибо!

**Comment by iliakan** [comment]
Скажите пожалуйста, без Pocket всё ок?

**Comment by havenchyk** [comment]
@Gurylev картинку перезалейте, пожалуйста. А вообще было бы здорово PR или хотя бы найти причину и предложение, как это исправить, спасибо!

**Comment by Gurylev** [comment]
Прошу прощения, у меня не получается воспроизвести. Стоило написать, как после обновления статьи всё заработало как следует. Только из кэша брался старый битый результат, но после обновления корректировался. Кстати, возможно и в кэш оно попало перед первым прочтением статей. Тогда, быть может, ещё было что-то с кодировкой.
Сейчас всё хорошо, ещё раз прошу прощения за панику.
