### ISSUE TITLE
По учебнику JS

### ISSUE THREAD

**Issue by OlegPomazkov** [iliakan/javascript-nodejs#826]
В задаче №2 раздела "Мышь Drag'n'Drop" не находит демо - идет alert с ошибкой

**Comment by iliakan** [comment]
Можно ссылку и/или скриншот?

**Comment by OlegPomazkov** [comment]
2016-01-21 11:05 GMT+03:00 Ilya Kantor <notifications@github.com>:

**Comment by iliakan** [comment]
inactivity
