### ISSUE TITLE
Подряд одинаковые ссылки с разными названиями

### ISSUE THREAD

**Issue by nikolaynizruhin** [iliakan/javascript-nodejs#830]
На странице http://learn.javascript.ru/class-inheritance#класс-часы когда открываешь решение - две одинаковые ссылки с разными названиями "Открыть полное решение" и "Открыть решение в песочнице."
Тоже самое(только не в решении, а в условии - одинаковые ссылки "Исходный документ, вместе с тестом" и "Открыть песочницу для задачи."): http://learn.javascript.ru/class-inheritance#меню-с-таймером-для-анимации

**Comment by iliakan** [comment]
hopefully fixed.

**Comment by nikolaynizruhin** [comment]
http://learn.javascript.ru/class-inheritance#меню-с-таймером-для-анимации
В условии и в решении по две одинаковых ссылки
