### ISSUE TITLE
Ссылка на "Учебник" в меню мобильной версии

### ISSUE THREAD

**Issue by etnolover** [iliakan/javascript-nodejs#836]
В мобильной версии нельзя через меню вернуться в "Учебник" из курса/списка курсов.

Детали:
Меню -> Курсы (-> Любой курс) -> Меню показывает, что я на странице "Учебник", т.е. из списка курсов вернуться через меню в учебник нельзя.

Вернуться можно через иконку "Домой", так что проблема некритична.

**Comment by iliakan** [comment]
Спасибо, поправил опечатку.
