### ISSUE TITLE
Не отображаются отзывы

### ISSUE THREAD

**Issue by Opty1712** [iliakan/javascript-nodejs#837]
https://learn.javascript.ru/courses/js/feedback
При попытке что-то выбрать показывает ошибку: "Ошибка на стороне сервера (код 400), попытайтесь позднее."

**Comment by Opty1712** [comment]
Отзывы стали показываться. Но:
1. новые внизу - что очень странно, логично сделать наоборот
2. http://learn.javascript.ru/courses/js/feedback как на эту страницу попасть в принципе с главной? Дружно искали и не нашли прямого линка)

**Comment by iliakan** [comment]
Да, отзывы нужно на страницу курса вынести, это пока не сделано. Пусть штук 100 будет :)

**Comment by Sogl** [comment]
@iliakan Ответ на отзыв, сделанный Вами, не отображается в режиме просмотра без авторизации. Авторизованные пользователи сайта также не видят ответ. В итоге вижу его только я.

С ответами Михаила Гринько такой проблемы не наблюдается.

**Comment by iliakan** [comment]
Спасибо, посмотрю. Могу я попросить убрать ссылку на slack, мы пока не утвердили это как официальный канал, а к отзыву она отношения уж точно не имеет :)

**Comment by Sogl** [comment]
На момент Вашего ответа уже все починилось, по крайней мере сейчас проблема не наблюдается. 

Ссылку из отзыва убрал. 
Хотелось бы, конечно, чтобы поддержали наше начинание в итоге. :wink:

**Comment by iliakan** [comment]
@Sogl дописал скринкаст по gulp, появилось время и посмотрю slack внимательнее.
