### ISSUE TITLE
bug: фотографии в профиле: черный фон в png, кроп возникает не всегда, тяжело кропнуть по краям.

### ISSUE THREAD

**Issue by aalexeev239** [iliakan/javascript-nodejs#842]
На входе у нас 2 фотографии марио 
размером 600x600:
https://monosnap.com/file/69e6ZwRVzzCn4EFXKwz9QrX0gU9hMw
и 600x601:
https://monosnap.com/file/in5c3UmfTrlDGfZQa5YTn53KHWtfYk
Обе фотографии — png с прозрачностью.

При загрузке, как видно , прозрачный png получает черный фон. Более логично устанавливать фон белым.

Если загрузить квадратную фото, не будет предложено ее кропнуть. Это странное поведение, потому что пользователь может хотеть обрезать красные границы, например.

Если загрузить не квадратную фото, появляется окно кропа. Крайне трудно обрезать ровно по всей ширине, не регистрируется обработчик клика вне области кропа. В итоге результат получается неровный. Более того, такой хороший результат, как на скринкасте, получился раза с пятого.

Скринкаст:
https://monosnap.com/file/nVOzO1gS2KJQhD2kgWLcN3iF8nSrwd

**Comment by iliakan** [comment]
Тут, я так вижу, 3 репорта в одном.

1) Кроп требуется только для неквадратной аватарки, это специально сделано, т.к. обычно юзер загружает уже готовую картинку. Т.е. загружая аватар, юзер обычно даже не думает о том, что будет доступна обработка и какая.

2) По ширине на 100% сложно кропнуть - это я понял, надо поправить.

3) Прозрачность при ресайзе - тоже надо поправить.

**Comment by aalexeev239** [comment]
@iliakan все верно. 
По п.1 — если есть возможность кропа, почему бы её не предоставить? 
Так покроется максимум вариантов. А если размеры области кропа по дефолту выставить на всю область, случай с уже готовой аватаркой отлично впишется в картину.
