### ISSUE TITLE
Так , просто предложение ...

### ISSUE THREAD

**Issue by trubenko** [iliakan/javascript-nodejs#844]
http://learn.javascript.ru/ajax-nodejs#основные-методы

в строках ниже я бы предложил упомянуть о том , что мы с серверной стороны рассматриваем  эти 2 объекта  , а не с клиентской , меня лично несколько раз запутывало : 

> req – объект запроса («request»), из него читаем данные.
res – объект ответа («response»), в него пишем данные.

**Comment by iliakan** [comment]
ок
