### ISSUE TITLE
Кавычки

### ISSUE THREAD

**Issue by trubenko** [iliakan/javascript-nodejs#845]
http://learn.javascript.ru/ajax-xmlhttprequest#ie9-и-кеширование
xhr.open('GET', ''service?r=' + Math.random(), false);
**'service?r='** так и надо чтобы был в одинарных кавычках, не в двойных?!

**Comment by iliakan** [comment]
да, спасибо.

**Comment by trubenko** [comment]
тогда у Вас лишняя одна кавычка, если я правильно Вас понял
