### ISSUE TITLE
почта

### ISSUE THREAD

**Issue by roni-ridz** [iliakan/javascript-nodejs#852]
незнаю туда не туда пишу, почта с форума перестала приходить с 27 февраля

**Comment by iliakan** [comment]
c javascript.ru/forum?

**Comment by roni-ridz** [comment]
да javascript.ru/forum? ник рони

**Comment by iliakan** [comment]
А сейчас? :)

**Comment by roni-ridz** [comment]
всё почта заработала, спасибо!!!

**Comment by roni-ridz** [comment]
что-то не до конца ... если пишут в личку ... сообщение на почту стало приходить,  если писать прямо на почту через кнопку E-mail сообщения не приходят

**Comment by iliakan** [comment]
Давайте протестируем, напишите мне на скайп ilya.a.kantor
