### ISSUE TITLE
Ссылки на отдельные видео

### ISSUE THREAD

**Issue by Londeren** [iliakan/javascript-nodejs#876]
Здравствуйте.
Добавьте, пожалуйста, ссылки на отдельные видео на странице https://learn.javascript.ru/screencast/nodejs
За день все не посмотреть, а так можно сохранить себе куда-то ссылку на следующее видео, которое хочешь смотреть.

**Comment by iliakan** [comment]
Видимо, сами ссылки `<a>` нужно сделать на youtube?
