### ISSUE TITLE
Витжет "Отзыв о курсе"

### ISSUE THREAD

**Issue by constantant** [iliakan/javascript-nodejs#881]
https://learn.javascript.ru/courses/typescript/feedback
Косяк в визуализации, как мне кажется. 
Тут бары, похоже, показывают общую статистику на **все курсы**, а не на конкретный

**Comment by iliakan** [comment]
Странно, можно скриншот?

**Comment by constantant** [comment]
Странно, но уже работает как надо... 
Вчера (25.05.2016)  в 2 часа дня точно был такой глюк. Наверно вы ноду перезапустили и изменения применились )

**Comment by iliakan** [comment]
=) да я там кое-что поправил, но не был уверен, что в этом дело.
